// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AccountEmailParams
    {
        public readonly IReadOnlyDictionary<string, string>? Vars;
        public readonly string? Email;
        public readonly string? Password;
        public readonly string? PrevEmail;
        public AccountEmailParams(IReadOnlyDictionary<string, string>? vars = null, string? email = null, string? password = null, string? prevEmail = null)
        {
            Vars = vars;
            Email = email;
            Password = password;
            PrevEmail = prevEmail;
        }
    }
}
