// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class AccountMezonBodyParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.AccountMezon ToProto(in AccountMezonBodyParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.AccountMezon();
            if (p.Vars is not null)
            {
                foreach (var kv in p.Vars)
                    proto.Vars[kv.Key] = kv.Value;
            }
            if (p.PhoneNumber is not null)
                proto.PhoneNumber = p.PhoneNumber;
            return proto;
        }
    }
}
