// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class AccountEmailParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.AccountEmail ToProto(in AccountEmailParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.AccountEmail();
            if (p.Vars is not null)
            {
                foreach (var kv in p.Vars)
                    proto.Vars[kv.Key] = kv.Value;
            }
            if (p.Email is not null)
                proto.Email = p.Email;
            if (p.Password is not null)
                proto.Password = p.Password;
            if (p.PrevEmail is not null)
                proto.PrevEmail = p.PrevEmail;
            return proto;
        }
    }
}
