// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AccountMezonBodyParams
    {
        public readonly IReadOnlyDictionary<string, string>? Vars;
        public readonly string? PhoneNumber;
        public AccountMezonBodyParams(IReadOnlyDictionary<string, string>? vars = null, string? phoneNumber = null)
        {
            Vars = vars;
            PhoneNumber = phoneNumber;
        }
    }
}
