// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ActiveArchivedThreadParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.ActiveArchivedThread ToProto(in ActiveArchivedThreadParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.ActiveArchivedThread();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            return proto;
        }
    }
}
