// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ActiveArchivedThreadParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public ActiveArchivedThreadParams(long? clanId = null, long? channelId = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
        }
    }
}
