// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class AddAppParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.AddAppRequest ToProto(in AddAppParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.AddAppRequest();
            if (p.Appname is not null)
                proto.Appname = p.Appname;
            if (p.Token is not null)
                proto.Token = p.Token;
            if (p.CreatorId.HasValue)
                proto.CreatorId = p.CreatorId.Value;
            if (p.Role.HasValue)
                proto.Role = p.Role.Value;
            if (p.IsShadow.HasValue)
                proto.IsShadow = p.IsShadow.Value;
            if (p.AppUrl is not null)
                proto.AppUrl = p.AppUrl;
            if (p.AppLogo is not null)
                proto.AppLogo = p.AppLogo;
            if (p.AboutMe is not null)
                proto.AboutMe = p.AboutMe;
            return proto;
        }
    }
}
