// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AddAppParams
    {
        public readonly string? Appname;
        public readonly string? Token;
        public readonly long? CreatorId;
        public readonly int? Role;
        public readonly bool? IsShadow;
        public readonly string? AppUrl;
        public readonly string? AppLogo;
        public readonly string? AboutMe;
        public AddAppParams(string? appname = null, string? token = null, long? creatorId = null, int? role = null, bool? isShadow = null, string? appUrl = null, string? appLogo = null, string? aboutMe = null)
        {
            Appname = appname;
            Token = token;
            CreatorId = creatorId;
            Role = role;
            IsShadow = isShadow;
            AppUrl = appUrl;
            AppLogo = appLogo;
            AboutMe = aboutMe;
        }
    }
}
