// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AddFavoriteChannelParams
    {
        public readonly long? ChannelId;
        public readonly long? ClanId;
        public AddFavoriteChannelParams(long? channelId = null, long? clanId = null)
        {
            ChannelId = channelId;
            ClanId = clanId;
        }
    }
}
