// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AddRoleChannelDescParams
    {
        public readonly IEnumerable<long?>? RoleIds;
        public readonly long? ChannelId;
        public AddRoleChannelDescParams(IEnumerable<long?>? roleIds = null, long? channelId = null)
        {
            RoleIds = roleIds;
            ChannelId = channelId;
        }
    }
}
