// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class AllUsersAddChannelParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.AllUsersAddChannelRequest ToProto(in AllUsersAddChannelParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.AllUsersAddChannelRequest();
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Limit.HasValue)
                proto.Limit = p.Limit.Value;
            return proto;
        }
    }
}
