// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CategoryOrderUpdateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CategoryOrderUpdate ToProto(in CategoryOrderUpdateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CategoryOrderUpdate();
            if (p.CategoryId.HasValue)
                proto.CategoryId = p.CategoryId.Value;
            if (p.Order.HasValue)
                proto.Order = p.Order.Value;
            return proto;
        }
    }
}
