// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CategoryOrderUpdateParams
    {
        public readonly long? CategoryId;
        public readonly int? Order;
        public CategoryOrderUpdateParams(long? categoryId = null, int? order = null)
        {
            CategoryId = categoryId;
            Order = order;
        }
    }
}
