// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelAppEventParams
    {
        public readonly long? UserId;
        public readonly string? Username;
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly int? Action;
        public ChannelAppEventParams(long? userId = null, string? username = null, long? clanId = null, long? channelId = null, int? action = null)
        {
            UserId = userId;
            Username = username;
            ClanId = clanId;
            ChannelId = channelId;
            Action = action;
        }
    }
}
