// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageRemoveParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly long? MessageId;
        public readonly int? Mode;
        public readonly bool? IsPublic;
        public readonly bool? HasAttachment;
        public readonly long? TopicId;
        public readonly byte[]? Mentions;
        public readonly byte[]? References;
        public ChannelMessageRemoveParams(long? clanId = null, long? channelId = null, long? messageId = null, int? mode = null, bool? isPublic = null, bool? hasAttachment = null, long? topicId = null, byte[]? mentions = null, byte[]? references = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            MessageId = messageId;
            Mode = mode;
            IsPublic = isPublic;
            HasAttachment = hasAttachment;
            TopicId = topicId;
            Mentions = mentions;
            References = references;
        }
    }
}
