// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ChannelMessageRemoveParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.ChannelMessageRemove ToProto(in ChannelMessageRemoveParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.ChannelMessageRemove();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.Mode.HasValue)
                proto.Mode = p.Mode.Value;
            if (p.IsPublic.HasValue)
                proto.IsPublic = p.IsPublic.Value;
            if (p.HasAttachment.HasValue)
                proto.HasAttachment = p.HasAttachment.Value;
            if (p.TopicId.HasValue)
                proto.TopicId = p.TopicId.Value;
            if (p.Mentions is not null)
                proto.Mentions = Google.Protobuf.ByteString.CopyFrom(p.Mentions);
            if (p.References is not null)
                proto.References = Google.Protobuf.ByteString.CopyFrom(p.References);
            return proto;
        }
    }
}
