// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ChannelJoinParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.ChannelJoin ToProto(in ChannelJoinParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.ChannelJoin();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ChannelType.HasValue)
                proto.ChannelType = p.ChannelType.Value;
            if (p.IsPublic.HasValue)
                proto.IsPublic = p.IsPublic.Value;
            return proto;
        }
    }
}
