// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageUpdateParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly long? MessageId;
        public readonly string? Content;
        public readonly IEnumerable<MessageMentionParams>? Mentions;
        public readonly IEnumerable<MessageAttachmentParams>? Attachments;
        public readonly int? Mode;
        public readonly bool? IsPublic;
        public readonly bool? HideEditted;
        public readonly long? TopicId;
        public readonly bool? IsUpdateMsgTopic;
        public readonly uint? CreateTimeSeconds;
        public ChannelMessageUpdateParams(long? clanId = null, long? channelId = null, long? messageId = null, string? content = null, IEnumerable<MessageMentionParams>? mentions = null, IEnumerable<MessageAttachmentParams>? attachments = null, int? mode = null, bool? isPublic = null, bool? hideEditted = null, long? topicId = null, bool? isUpdateMsgTopic = null, uint? createTimeSeconds = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            MessageId = messageId;
            Content = content;
            Mentions = mentions;
            Attachments = attachments;
            Mode = mode;
            IsPublic = isPublic;
            HideEditted = hideEditted;
            TopicId = topicId;
            IsUpdateMsgTopic = isUpdateMsgTopic;
            CreateTimeSeconds = createTimeSeconds;
        }
    }
}
