// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChanEncryptionMethodParams
    {
        public readonly string? Method;
        public readonly long? ChannelId;
        public ChanEncryptionMethodParams(string? method = null, long? channelId = null)
        {
            Method = method;
            ChannelId = channelId;
        }
    }
}
