// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ChangeChannelPrivateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ChangeChannelPrivateRequest ToProto(in ChangeChannelPrivateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ChangeChannelPrivateRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ChannelPrivate.HasValue)
                proto.ChannelPrivate = p.ChannelPrivate.Value;
            if (p.UserIds is not null)
            {
                foreach (var item in p.UserIds)
                    if (item.HasValue) proto.UserIds.Add(item.Value);
            }
            if (p.RoleIds is not null)
            {
                foreach (var item in p.RoleIds)
                    if (item.HasValue) proto.RoleIds.Add(item.Value);
            }
            return proto;
        }
    }
}
