// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChangeChannelPrivateParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly int? ChannelPrivate;
        public readonly IEnumerable<long?>? UserIds;
        public readonly IEnumerable<long?>? RoleIds;
        public ChangeChannelPrivateParams(long? clanId = null, long? channelId = null, int? channelPrivate = null, IEnumerable<long?>? userIds = null, IEnumerable<long?>? roleIds = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            ChannelPrivate = channelPrivate;
            UserIds = userIds;
            RoleIds = roleIds;
        }
    }
}
