// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ChanEncryptionMethodParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ChanEncryptionMethod ToProto(in ChanEncryptionMethodParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ChanEncryptionMethod();
            if (p.Method is not null)
                proto.Method = p.Method;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            return proto;
        }
    }
}
