// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelTimelineAttachmentParams
    {
        public readonly long? Id;
        public readonly string? FileName;
        public readonly string? FileUrl;
        public readonly string? FileType;
        public readonly long? FileSize;
        public readonly int? Width;
        public readonly int? Height;
        public readonly string? Thumbnail;
        public readonly int? Duration;
        public readonly long? MessageId;
        public ChannelTimelineAttachmentParams(long? id = null, string? fileName = null, string? fileUrl = null, string? fileType = null, long? fileSize = null, int? width = null, int? height = null, string? thumbnail = null, int? duration = null, long? messageId = null)
        {
            Id = id;
            FileName = fileName;
            FileUrl = fileUrl;
            FileType = fileType;
            FileSize = fileSize;
            Width = width;
            Height = height;
            Thumbnail = thumbnail;
            Duration = duration;
            MessageId = messageId;
        }
    }
}
