// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ChannelMessageUpdateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.ChannelMessageUpdate ToProto(in ChannelMessageUpdateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.ChannelMessageUpdate();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.Content is not null)
                proto.Content = p.Content;
            if (p.Mentions is not null)
            {
                foreach (var item in p.Mentions)
                    proto.Mentions.Add(MessageMentionParamsMapper.ToProto(item));
            }
            if (p.Attachments is not null)
            {
                foreach (var item in p.Attachments)
                    proto.Attachments.Add(MessageAttachmentParamsMapper.ToProto(item));
            }
            if (p.Mode.HasValue)
                proto.Mode = p.Mode.Value;
            if (p.IsPublic.HasValue)
                proto.IsPublic = p.IsPublic.Value;
            if (p.HideEditted.HasValue)
                proto.HideEditted = p.HideEditted.Value;
            if (p.TopicId.HasValue)
                proto.TopicId = p.TopicId.Value;
            if (p.IsUpdateMsgTopic.HasValue)
                proto.IsUpdateMsgTopic = p.IsUpdateMsgTopic.Value;
            if (p.CreateTimeSeconds.HasValue)
                proto.CreateTimeSeconds = p.CreateTimeSeconds.Value;
            return proto;
        }
    }
}
