// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ChannelAppEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.ChannelAppEvent ToProto(in ChannelAppEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.ChannelAppEvent();
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.Username is not null)
                proto.Username = p.Username;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Action.HasValue)
                proto.Action = p.Action.Value;
            return proto;
        }
    }
}
