// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelJoinParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly int? ChannelType;
        public readonly bool? IsPublic;
        public ChannelJoinParams(long? clanId = null, long? channelId = null, int? channelType = null, bool? isPublic = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            ChannelType = channelType;
            IsPublic = isPublic;
        }
    }
}
