// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CheckDuplicateNameParams
    {
        public readonly string? Name;
        public readonly int? Type;
        public readonly long? ConditionId;
        public CheckDuplicateNameParams(string? name = null, int? type = null, long? conditionId = null)
        {
            Name = name;
            Type = type;
            ConditionId = conditionId;
        }
    }
}
