// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CheckDuplicateNameParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CheckDuplicateNameRequest ToProto(in CheckDuplicateNameParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CheckDuplicateNameRequest();
            if (p.Name is not null)
                proto.Name = p.Name;
            if (p.Type.HasValue)
                proto.Type = p.Type.Value;
            if (p.ConditionId.HasValue)
                proto.ConditionId = p.ConditionId.Value;
            return proto;
        }
    }
}
