// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ClanWebhookHandlerBodyParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ClanWebhookHandlerBody ToProto(in ClanWebhookHandlerBodyParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ClanWebhookHandlerBody();
            if (p.Content is not null)
                proto.Content = p.Content;
            if (p.Attachments is not null)
            {
                foreach (var item in p.Attachments)
                    proto.Attachments.Add(MessageAttachmentParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
