// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanOrderParams
    {
        public readonly int? Order;
        public readonly long? ClanId;
        public ClanOrderParams(int? order = null, long? clanId = null)
        {
            Order = order;
            ClanId = clanId;
        }
    }
}
