// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanStickerAddParams
    {
        public readonly string? Source;
        public readonly string? Shortname;
        public readonly string? Category;
        public readonly long? ClanId;
        public readonly long? Id;
        public readonly int? MediaType;
        public readonly bool? IsForSale;
        public ClanStickerAddParams(string? source = null, string? shortname = null, string? category = null, long? clanId = null, long? id = null, int? mediaType = null, bool? isForSale = null)
        {
            Source = source;
            Shortname = shortname;
            Category = category;
            ClanId = clanId;
            Id = id;
            MediaType = mediaType;
            IsForSale = isForSale;
        }
    }
}
