// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanWebhookHandlerParams
    {
        public readonly ClanWebhookHandlerBodyParams Body;
        public readonly string? Token;
        public readonly string? Username;
        public ClanWebhookHandlerParams(ClanWebhookHandlerBodyParams body = default, string? token = null, string? username = null)
        {
            Body = body;
            Token = token;
            Username = username;
        }
    }
}
