// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanJoinParams
    {
        public readonly long? ClanId;
        public readonly bool? IsLastField;
        public ClanJoinParams(long? clanId = null, bool? isLastField = null)
        {
            ClanId = clanId;
            IsLastField = isLastField;
        }
    }
}
