// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ClanJoinParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.ClanJoin ToProto(in ClanJoinParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.ClanJoin();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
