// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanWebhookHandlerBodyParams
    {
        public readonly string? Content;
        public readonly IEnumerable<MessageAttachmentParams>? Attachments;
        public ClanWebhookHandlerBodyParams(string? content = null, IEnumerable<MessageAttachmentParams>? attachments = null)
        {
            Content = content;
            Attachments = attachments;
        }
    }
}
