// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ClanEmojiCreateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ClanEmojiCreateRequest ToProto(in ClanEmojiCreateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ClanEmojiCreateRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Source is not null)
                proto.Source = p.Source;
            if (p.Shortname is not null)
                proto.Shortname = p.Shortname;
            if (p.Category is not null)
                proto.Category = p.Category;
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.IsForSale.HasValue)
                proto.IsForSale = p.IsForSale.Value;
            return proto;
        }
    }
}
