// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanJoinParams
    {
        public readonly long? ClanId;
        public ClanJoinParams(long? clanId = null)
        {
            ClanId = clanId;
        }
    }
}
