// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ClanOrderParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateClanOrderRequest.Types.ClanOrder ToProto(in ClanOrderParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateClanOrderRequest.Types.ClanOrder();
            if (p.Order.HasValue)
                proto.Order = p.Order.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
