// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ClanWebhookHandlerParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ClanWebhookHandlerRequest ToProto(in ClanWebhookHandlerParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ClanWebhookHandlerRequest();
            proto.Body = ClanWebhookHandlerBodyParamsMapper.ToProto(p.Body);
            if (p.Token is not null)
                proto.Token = p.Token;
            if (p.Username is not null)
                proto.Username = p.Username;
            return proto;
        }
    }
}
