// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ClanEmojiUpdateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ClanEmojiUpdateRequest ToProto(in ClanEmojiUpdateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ClanEmojiUpdateRequest();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.Shortname is not null)
                proto.Shortname = p.Shortname;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
