// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanEmojiUpdateParams
    {
        public readonly long? Id;
        public readonly string? Shortname;
        public readonly long? ClanId;
        public ClanEmojiUpdateParams(long? id = null, string? shortname = null, long? clanId = null)
        {
            Id = id;
            Shortname = shortname;
            ClanId = clanId;
        }
    }
}
