// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ClosePollParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ClosePollRequest ToProto(in ClosePollParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ClosePollRequest();
            if (p.PollId.HasValue)
                proto.PollId = p.PollId.Value;
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            return proto;
        }
    }
}
