// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ConfirmLoginParams
    {
        public readonly long? LoginId;
        public readonly bool? IsRemember;
        public ConfirmLoginParams(long? loginId = null, bool? isRemember = null)
        {
            LoginId = loginId;
            IsRemember = isRemember;
        }
    }
}
