// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CreateCategoryDescParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CreateCategoryDescRequest ToProto(in CreateCategoryDescParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CreateCategoryDescRequest();
            if (p.CategoryName is not null)
                proto.CategoryName = p.CategoryName;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
