// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CreateEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CreateEventRequest ToProto(in CreateEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CreateEventRequest();
            if (p.Title is not null)
                proto.Title = p.Title;
            if (p.Logo is not null)
                proto.Logo = p.Logo;
            if (p.Description is not null)
                proto.Description = p.Description;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelVoiceId.HasValue)
                proto.ChannelVoiceId = p.ChannelVoiceId.Value;
            if (p.Address is not null)
                proto.Address = p.Address;
            if (p.StartTimeSeconds.HasValue)
                proto.StartTimeSeconds = p.StartTimeSeconds.Value;
            if (p.EndTimeSeconds.HasValue)
                proto.EndTimeSeconds = p.EndTimeSeconds.Value;
            if (p.EventId.HasValue)
                proto.EventId = p.EventId.Value;
            if (p.EventStatus.HasValue)
                proto.EventStatus = p.EventStatus.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Action.HasValue)
                proto.Action = p.Action.Value;
            if (p.RepeatType.HasValue)
                proto.RepeatType = p.RepeatType.Value;
            if (p.CreatorId.HasValue)
                proto.CreatorId = p.CreatorId.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.IsPrivate.HasValue)
                proto.IsPrivate = p.IsPrivate.Value;
            proto.MeetRoom = GenerateMezonMeetResponseParamsMapper.ToProto(p.MeetRoom);
            return proto;
        }
    }
}
