// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreateChannelDescParams
    {
        public readonly long? ClanId;
        public readonly long? ParentId;
        public readonly long? ChannelId;
        public readonly long? CategoryId;
        public readonly int? Type;
        public readonly string? ChannelLabel;
        public readonly int? ChannelPrivate;
        public readonly IEnumerable<long?>? UserIds;
        public readonly long? AppId;
        public CreateChannelDescParams(long? clanId = null, long? parentId = null, long? channelId = null, long? categoryId = null, int? type = null, string? channelLabel = null, int? channelPrivate = null, IEnumerable<long?>? userIds = null, long? appId = null)
        {
            ClanId = clanId;
            ParentId = parentId;
            ChannelId = channelId;
            CategoryId = categoryId;
            Type = type;
            ChannelLabel = channelLabel;
            ChannelPrivate = channelPrivate;
            UserIds = userIds;
            AppId = appId;
        }
    }
}
