// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreateOnboardingParams
    {
        public readonly long? ClanId;
        public readonly IEnumerable<OnboardingContentParams>? Contents;
        public CreateOnboardingParams(long? clanId = null, IEnumerable<OnboardingContentParams>? contents = null)
        {
            ClanId = clanId;
            Contents = contents;
        }
    }
}
