// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreateCategoryDescParams
    {
        public readonly string? CategoryName;
        public readonly long? ClanId;
        public CreateCategoryDescParams(string? categoryName = null, long? clanId = null)
        {
            CategoryName = categoryName;
            ClanId = clanId;
        }
    }
}
