// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreateActivityParams
    {
        public readonly string? ActivityName;
        public readonly int? ActivityType;
        public readonly string? ActivityDescription;
        public readonly uint? StartTimeSeconds;
        public readonly long? ApplicationId;
        public readonly int? Status;
        public CreateActivityParams(string? activityName = null, int? activityType = null, string? activityDescription = null, uint? startTimeSeconds = null, long? applicationId = null, int? status = null)
        {
            ActivityName = activityName;
            ActivityType = activityType;
            ActivityDescription = activityDescription;
            StartTimeSeconds = startTimeSeconds;
            ApplicationId = applicationId;
            Status = status;
        }
    }
}
