// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CreateOnboardingParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CreateOnboardingRequest ToProto(in CreateOnboardingParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CreateOnboardingRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Contents is not null)
            {
                foreach (var item in p.Contents)
                    proto.Contents.Add(OnboardingContentParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
