// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CreateChannelTimelineParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CreateChannelTimelineRequest ToProto(in CreateChannelTimelineParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CreateChannelTimelineRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.StartTimeSeconds.HasValue)
                proto.StartTimeSeconds = p.StartTimeSeconds.Value;
            if (p.Title is not null)
                proto.Title = p.Title;
            if (p.Description is not null)
                proto.Description = p.Description;
            if (p.EndTimeSeconds.HasValue)
                proto.EndTimeSeconds = p.EndTimeSeconds.Value;
            if (p.Location is not null)
                proto.Location = p.Location;
            if (p.Type.HasValue)
                proto.Type = p.Type.Value;
            if (p.Attachments is not null)
            {
                foreach (var item in p.Attachments)
                    proto.Attachments.Add(ChannelTimelineAttachmentParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
