// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreatePollParams
    {
        public readonly long? ChannelId;
        public readonly long? ClanId;
        public readonly string? Question;
        public readonly IEnumerable<string?>? Answers;
        public readonly int? ExpireHours;
        public readonly global::Mezon.Net.Internal.Api.PollType? Type;
        public CreatePollParams(long? channelId = null, long? clanId = null, string? question = null, IEnumerable<string?>? answers = null, int? expireHours = null, global::Mezon.Net.Internal.Api.PollType? type = null)
        {
            ChannelId = channelId;
            ClanId = clanId;
            Question = question;
            Answers = answers;
            ExpireHours = expireHours;
            Type = type;
        }
    }
}
