// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CreatePollParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CreatePollRequest ToProto(in CreatePollParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CreatePollRequest();
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Question is not null)
                proto.Question = p.Question;
            if (p.Answers is not null)
                proto.Answers.AddRange(p.Answers);
            if (p.ExpireHours.HasValue)
                proto.ExpireHours = p.ExpireHours.Value;
            if (p.Type.HasValue)
                proto.Type = p.Type.Value;
            return proto;
        }
    }
}
