// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CreateActivityParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.CreateActivityRequest ToProto(in CreateActivityParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.CreateActivityRequest();
            if (p.ActivityName is not null)
                proto.ActivityName = p.ActivityName;
            if (p.ActivityType.HasValue)
                proto.ActivityType = p.ActivityType.Value;
            if (p.ActivityDescription is not null)
                proto.ActivityDescription = p.ActivityDescription;
            if (p.StartTimeSeconds.HasValue)
                proto.StartTimeSeconds = p.StartTimeSeconds.Value;
            if (p.ApplicationId.HasValue)
                proto.ApplicationId = p.ApplicationId.Value;
            if (p.Status.HasValue)
                proto.Status = p.Status.Value;
            return proto;
        }
    }
}
