// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class CustomStatusEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.CustomStatusEvent ToProto(in CustomStatusEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.CustomStatusEvent();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.Username is not null)
                proto.Username = p.Username;
            if (p.Status is not null)
                proto.Status = p.Status;
            if (p.TimeReset.HasValue)
                proto.TimeReset = p.TimeReset.Value;
            if (p.NoClear.HasValue)
                proto.NoClear = p.NoClear.Value;
            return proto;
        }
    }
}
