// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CustomStatusEventParams
    {
        public readonly long? ClanId;
        public readonly long? UserId;
        public readonly string? Username;
        public readonly string? Status;
        public readonly int? TimeReset;
        public readonly bool? NoClear;
        public CustomStatusEventParams(long? clanId = null, long? userId = null, string? username = null, string? status = null, int? timeReset = null, bool? noClear = null)
        {
            ClanId = clanId;
            UserId = userId;
            Username = username;
            Status = status;
            TimeReset = timeReset;
            NoClear = noClear;
        }
    }
}
