// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class DefaultNotificationCategoryParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.DefaultNotificationCategory ToProto(in DefaultNotificationCategoryParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.DefaultNotificationCategory();
            if (p.CategoryId.HasValue)
                proto.CategoryId = p.CategoryId.Value;
            return proto;
        }
    }
}
