// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct DefaultNotificationCategoryParams
    {
        public readonly long? CategoryId;
        public DefaultNotificationCategoryParams(long? categoryId = null)
        {
            CategoryId = categoryId;
        }
    }
}
