// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class DeleteSdTopicParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.DeleteSdTopicRequest ToProto(in DeleteSdTopicParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.DeleteSdTopicRequest();
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
