// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct DeleteSdTopicParams
    {
        public readonly long? ChannelId;
        public readonly long? Id;
        public readonly long? ClanId;
        public DeleteSdTopicParams(long? channelId = null, long? id = null, long? clanId = null)
        {
            ChannelId = channelId;
            Id = id;
            ClanId = clanId;
        }
    }
}
