// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct DropdownBoxSelectedParams
    {
        public readonly long? MessageId;
        public readonly long? ChannelId;
        public readonly string? SelectboxId;
        public readonly long? SenderId;
        public readonly long? UserId;
        public readonly IEnumerable<string?>? Values;
        public DropdownBoxSelectedParams(long? messageId = null, long? channelId = null, string? selectboxId = null, long? senderId = null, long? userId = null, IEnumerable<string?>? values = null)
        {
            MessageId = messageId;
            ChannelId = channelId;
            SelectboxId = selectboxId;
            SenderId = senderId;
            UserId = userId;
            Values = values;
        }
    }
}
