// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class DropdownBoxSelectedParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.DropdownBoxSelected ToProto(in DropdownBoxSelectedParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.DropdownBoxSelected();
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.SelectboxId is not null)
                proto.SelectboxId = p.SelectboxId;
            if (p.SenderId.HasValue)
                proto.SenderId = p.SenderId.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.Values is not null)
                proto.Values.AddRange(p.Values);
            return proto;
        }
    }
}
