// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EditChannelCanvasParams
    {
        public readonly long? Id;
        public readonly long? ChannelId;
        public readonly long? ClanId;
        public readonly string? Title;
        public readonly string? Content;
        public readonly bool? IsDefault;
        public readonly int? Status;
        public EditChannelCanvasParams(long? id = null, long? channelId = null, long? clanId = null, string? title = null, string? content = null, bool? isDefault = null, int? status = null)
        {
            Id = id;
            ChannelId = channelId;
            ClanId = clanId;
            Title = title;
            Content = content;
            IsDefault = isDefault;
            Status = status;
        }
    }
}
