// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class EditChannelCanvasParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.EditChannelCanvasRequest ToProto(in EditChannelCanvasParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.EditChannelCanvasRequest();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Title is not null)
                proto.Title = p.Title;
            if (p.Content is not null)
                proto.Content = p.Content;
            if (p.IsDefault.HasValue)
                proto.IsDefault = p.IsDefault.Value;
            if (p.Status.HasValue)
                proto.Status = p.Status.Value;
            return proto;
        }
    }
}
