// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct FilterParamParams
    {
        public readonly string? FieldName;
        public readonly string? FieldValue;
        public FilterParamParams(string? fieldName = null, string? fieldValue = null)
        {
            FieldName = fieldName;
            FieldValue = fieldValue;
        }
    }
}
