// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class FilterParamParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.FilterParam ToProto(in FilterParamParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.FilterParam();
            if (p.FieldName is not null)
                proto.FieldName = p.FieldName;
            if (p.FieldValue is not null)
                proto.FieldValue = p.FieldValue;
            return proto;
        }
    }
}
