// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class GenerateMeetTokenParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.GenerateMeetTokenRequest ToProto(in GenerateMeetTokenParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.GenerateMeetTokenRequest();
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.RoomName is not null)
                proto.RoomName = p.RoomName;
            return proto;
        }
    }
}
