// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class GenerateMezonMeetResponseParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.GenerateMezonMeetResponse ToProto(in GenerateMezonMeetResponseParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.GenerateMezonMeetResponse();
            if (p.MeetId.HasValue)
                proto.MeetId = p.MeetId.Value;
            if (p.RoomName is not null)
                proto.RoomName = p.RoomName;
            if (p.ExternalLink is not null)
                proto.ExternalLink = p.ExternalLink;
            if (p.CreatorId.HasValue)
                proto.CreatorId = p.CreatorId.Value;
            if (p.EventId.HasValue)
                proto.EventId = p.EventId.Value;
            return proto;
        }
    }
}
