// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateHashChannelAppsParams
    {
        public readonly long? AppId;
        public GenerateHashChannelAppsParams(long? appId = null)
        {
            AppId = appId;
        }
    }
}
