// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class GenerateHashChannelAppsParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.GenerateHashChannelAppsRequest ToProto(in GenerateHashChannelAppsParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.GenerateHashChannelAppsRequest();
            if (p.AppId.HasValue)
                proto.AppId = p.AppId.Value;
            return proto;
        }
    }
}
