// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class GenerateCDNSignatureParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.GenerateCDNSignatureRequest ToProto(in GenerateCDNSignatureParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.GenerateCDNSignatureRequest();
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            return proto;
        }
    }
}
