// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateMeetTokenParams
    {
        public readonly long? ChannelId;
        public readonly string? RoomName;
        public readonly string? Metadata;
        public GenerateMeetTokenParams(long? channelId = null, string? roomName = null, string? metadata = null)
        {
            ChannelId = channelId;
            RoomName = roomName;
            Metadata = metadata;
        }
    }
}
