// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateMezonMeetResponseParams
    {
        public readonly long? MeetId;
        public readonly string? RoomName;
        public readonly string? ExternalLink;
        public readonly long? CreatorId;
        public readonly long? EventId;
        public GenerateMezonMeetResponseParams(long? meetId = null, string? roomName = null, string? externalLink = null, long? creatorId = null, long? eventId = null)
        {
            MeetId = meetId;
            RoomName = roomName;
            ExternalLink = externalLink;
            CreatorId = creatorId;
            EventId = eventId;
        }
    }
}
