// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class GenerateClanWebhookParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.GenerateClanWebhookRequest ToProto(in GenerateClanWebhookParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.GenerateClanWebhookRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.WebhookName is not null)
                proto.WebhookName = p.WebhookName;
            if (p.Avatar is not null)
                proto.Avatar = p.Avatar;
            return proto;
        }
    }
}
