// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GetMezonOauthClientParams
    {
        public readonly string? ClientId;
        public readonly string? ClientName;
        public GetMezonOauthClientParams(string? clientId = null, string? clientName = null)
        {
            ClientId = clientId;
            ClientName = clientName;
        }
    }
}
