// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class GetMezonOauthClientParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.GetMezonOauthClientRequest ToProto(in GetMezonOauthClientParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.GetMezonOauthClientRequest();
            if (p.ClientId is not null)
                proto.ClientId = p.ClientId;
            if (p.ClientName is not null)
                proto.ClientName = p.ClientName;
            return proto;
        }
    }
}
