// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class IncomingCallPushParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.IncomingCallPush ToProto(in IncomingCallPushParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.IncomingCallPush();
            if (p.ReceiverId.HasValue)
                proto.ReceiverId = p.ReceiverId.Value;
            if (p.JsonData is not null)
                proto.JsonData = p.JsonData;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.CallerId.HasValue)
                proto.CallerId = p.CallerId.Value;
            return proto;
        }
    }
}
