// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class IsFollowerParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.IsFollowerRequest ToProto(in IsFollowerParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.IsFollowerRequest();
            if (p.FollowId.HasValue)
                proto.FollowId = p.FollowId.Value;
            return proto;
        }
    }
}
