// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct IsFollowerParams
    {
        public readonly long? FollowId;
        public IsFollowerParams(long? followId = null)
        {
            FollowId = followId;
        }
    }
}
