// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class LastPinMessageEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.LastPinMessageEvent ToProto(in LastPinMessageEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.LastPinMessageEvent();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.Mode.HasValue)
                proto.Mode = p.Mode.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.TimestampSeconds.HasValue)
                proto.TimestampSeconds = p.TimestampSeconds.Value;
            if (p.Operation.HasValue)
                proto.Operation = p.Operation.Value;
            if (p.IsPublic.HasValue)
                proto.IsPublic = p.IsPublic.Value;
            if (p.MessageSenderAvatar is not null)
                proto.MessageSenderAvatar = p.MessageSenderAvatar;
            if (p.MessageSenderId is not null)
                proto.MessageSenderId = p.MessageSenderId;
            if (p.MessageSenderUsername is not null)
                proto.MessageSenderUsername = p.MessageSenderUsername;
            if (p.MessageContent is not null)
                proto.MessageContent = p.MessageContent;
            if (p.MessageAttachment is not null)
                proto.MessageAttachment = p.MessageAttachment;
            if (p.MessageCreatedTime is not null)
                proto.MessageCreatedTime = p.MessageCreatedTime;
            return proto;
        }
    }
}
