// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LastPinMessageEventParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly long? MessageId;
        public readonly int? Mode;
        public readonly long? UserId;
        public readonly uint? TimestampSeconds;
        public readonly int? Operation;
        public readonly bool? IsPublic;
        public readonly string? MessageSenderAvatar;
        public readonly string? MessageSenderId;
        public readonly string? MessageSenderUsername;
        public readonly string? MessageContent;
        public readonly string? MessageAttachment;
        public readonly string? MessageCreatedTime;
        public LastPinMessageEventParams(long? clanId = null, long? channelId = null, long? messageId = null, int? mode = null, long? userId = null, uint? timestampSeconds = null, int? operation = null, bool? isPublic = null, string? messageSenderAvatar = null, string? messageSenderId = null, string? messageSenderUsername = null, string? messageContent = null, string? messageAttachment = null, string? messageCreatedTime = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            MessageId = messageId;
            Mode = mode;
            UserId = userId;
            TimestampSeconds = timestampSeconds;
            Operation = operation;
            IsPublic = isPublic;
            MessageSenderAvatar = messageSenderAvatar;
            MessageSenderId = messageSenderId;
            MessageSenderUsername = messageSenderUsername;
            MessageContent = messageContent;
            MessageAttachment = messageAttachment;
            MessageCreatedTime = messageCreatedTime;
        }
    }
}
