// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class LastSeenMessageEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.LastSeenMessageEvent ToProto(in LastSeenMessageEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.LastSeenMessageEvent();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.Mode.HasValue)
                proto.Mode = p.Mode.Value;
            if (p.TimestampSeconds.HasValue)
                proto.TimestampSeconds = p.TimestampSeconds.Value;
            if (p.BadgeCount.HasValue)
                proto.BadgeCount = p.BadgeCount.Value;
            return proto;
        }
    }
}
