// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LastSeenMessageEventParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly long? MessageId;
        public readonly int? Mode;
        public readonly uint? TimestampSeconds;
        public readonly int? BadgeCount;
        public LastSeenMessageEventParams(long? clanId = null, long? channelId = null, long? messageId = null, int? mode = null, uint? timestampSeconds = null, int? badgeCount = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            MessageId = messageId;
            Mode = mode;
            TimestampSeconds = timestampSeconds;
            BadgeCount = badgeCount;
        }
    }
}
