// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LinkInviteUserParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly int? ExpiryTime;
        public LinkInviteUserParams(long? clanId = null, long? channelId = null, int? expiryTime = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            ExpiryTime = expiryTime;
        }
    }
}
