// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LinkAccountConfirmParams
    {
        public readonly string? ReqId;
        public readonly int? Status;
        public readonly string? OtpCode;
        public LinkAccountConfirmParams(string? reqId = null, int? status = null, string? otpCode = null)
        {
            ReqId = reqId;
            Status = status;
            OtpCode = otpCode;
        }
    }
}
