// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class LinkInviteUserParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.LinkInviteUserRequest ToProto(in LinkInviteUserParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.LinkInviteUserRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ExpiryTime.HasValue)
                proto.ExpiryTime = p.ExpiryTime.Value;
            return proto;
        }
    }
}
