// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class LinkAccountConfirmParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.LinkAccountConfirmRequest ToProto(in LinkAccountConfirmParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.LinkAccountConfirmRequest();
            if (p.ReqId is not null)
                proto.ReqId = p.ReqId;
            if (p.Status.HasValue)
                proto.Status = p.Status.Value;
            if (p.OtpCode is not null)
                proto.OtpCode = p.OtpCode;
            return proto;
        }
    }
}
