// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ListForSaleItemsParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ListForSaleItemsRequest ToProto(in ListForSaleItemsParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ListForSaleItemsRequest();
            if (p.Page.HasValue)
                proto.Page = p.Page.Value;
            return proto;
        }
    }
}
