// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ListChannelTimelineParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ListChannelTimelineRequest ToProto(in ListChannelTimelineParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ListChannelTimelineRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Year.HasValue)
                proto.Year = p.Year.Value;
            if (p.StartTime.HasValue)
                proto.StartTime = p.StartTime.Value;
            if (p.EndTime.HasValue)
                proto.EndTime = p.EndTime.Value;
            if (p.Limit.HasValue)
                proto.Limit = p.Limit.Value;
            return proto;
        }
    }
}
