// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ListChannelDescsParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ListChannelDescsRequest ToProto(in ListChannelDescsParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ListChannelDescsRequest();
            if (p.Limit.HasValue)
                proto.Limit = p.Limit.Value;
            if (p.State.HasValue)
                proto.State = p.State.Value;
            if (p.Cursor is not null)
                proto.Cursor = p.Cursor;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelType.HasValue)
                proto.ChannelType = p.ChannelType.Value;
            if (p.IsMobile.HasValue)
                proto.IsMobile = p.IsMobile.Value;
            if (p.Page.HasValue)
                proto.Page = p.Page.Value;
            return proto;
        }
    }
}
