// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListChannelTimelineParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly int? Year;
        public readonly uint? StartTime;
        public readonly uint? EndTime;
        public readonly int? Limit;
        public ListChannelTimelineParams(long? clanId = null, long? channelId = null, int? year = null, uint? startTime = null, uint? endTime = null, int? limit = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            Year = year;
            StartTime = startTime;
            EndTime = endTime;
            Limit = limit;
        }
    }
}
