// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ListRoleUsersParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ListRoleUsersRequest ToProto(in ListRoleUsersParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ListRoleUsersRequest();
            if (p.RoleId.HasValue)
                proto.RoleId = p.RoleId.Value;
            if (p.Limit.HasValue)
                proto.Limit = p.Limit.Value;
            if (p.Cursor is not null)
                proto.Cursor = p.Cursor;
            return proto;
        }
    }
}
