// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ListClanDescParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ListClanDescRequest ToProto(in ListClanDescParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ListClanDescRequest();
            if (p.Limit.HasValue)
                proto.Limit = p.Limit.Value;
            if (p.State.HasValue)
                proto.State = p.State.Value;
            if (p.Cursor is not null)
                proto.Cursor = p.Cursor;
            return proto;
        }
    }
}
