// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ListSdTopicParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ListSdTopicRequest ToProto(in ListSdTopicParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ListSdTopicRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Limit.HasValue)
                proto.Limit = p.Limit.Value;
            return proto;
        }
    }
}
