// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListRoleUsersParams
    {
        public readonly long? RoleId;
        public readonly int? Limit;
        public readonly string? Cursor;
        public ListRoleUsersParams(long? roleId = null, int? limit = null, string? cursor = null)
        {
            RoleId = roleId;
            Limit = limit;
            Cursor = cursor;
        }
    }
}
