// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListClanDescParams
    {
        public readonly int? Limit;
        public readonly int? State;
        public readonly string? Cursor;
        public ListClanDescParams(int? limit = null, int? state = null, string? cursor = null)
        {
            Limit = limit;
            State = state;
            Cursor = cursor;
        }
    }
}
