// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListSdTopicParams
    {
        public readonly long? ClanId;
        public readonly int? Limit;
        public readonly int? Page;
        public ListSdTopicParams(long? clanId = null, int? limit = null, int? page = null)
        {
            ClanId = clanId;
            Limit = limit;
            Page = page;
        }
    }
}
