// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class LoginParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.LoginRequest ToProto(in LoginParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.LoginRequest();
            if (p.Platform is not null)
                proto.Platform = p.Platform;
            if (p.Address is not null)
                proto.Address = p.Address;
            return proto;
        }
    }
}
