// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LoginParams
    {
        public readonly string? Platform;
        public readonly string? Address;
        public LoginParams(string? platform = null, string? address = null)
        {
            Platform = platform;
            Address = address;
        }
    }
}
