// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MarkAsReadParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MarkAsReadRequest ToProto(in MarkAsReadParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MarkAsReadRequest();
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.CategoryId.HasValue)
                proto.CategoryId = p.CategoryId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
