// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MarkAsReadParams
    {
        public readonly long? ChannelId;
        public readonly long? CategoryId;
        public readonly long? ClanId;
        public MarkAsReadParams(long? channelId = null, long? categoryId = null, long? clanId = null)
        {
            ChannelId = channelId;
            CategoryId = categoryId;
            ClanId = clanId;
        }
    }
}
