// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MeetParticipantParams
    {
        public readonly long? UserId;
        public readonly long? ChannelId;
        public readonly long? ClanId;
        public MeetParticipantParams(long? userId = null, long? channelId = null, long? clanId = null)
        {
            UserId = userId;
            ChannelId = channelId;
            ClanId = clanId;
        }
    }
}
