// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MeetParticipantParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MeetParticipantRequest ToProto(in MeetParticipantParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MeetParticipantRequest();
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
