// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageTypingEventParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly long? SenderId;
        public readonly int? Mode;
        public readonly bool? IsPublic;
        public readonly string? SenderUsername;
        public readonly string? SenderDisplayName;
        public readonly long? TopicId;
        public MessageTypingEventParams(long? clanId = null, long? channelId = null, long? senderId = null, int? mode = null, bool? isPublic = null, string? senderUsername = null, string? senderDisplayName = null, long? topicId = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            SenderId = senderId;
            Mode = mode;
            IsPublic = isPublic;
            SenderUsername = senderUsername;
            SenderDisplayName = senderDisplayName;
            TopicId = topicId;
        }
    }
}
