// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageAttachmentParams
    {
        public readonly string? Filename;
        public readonly int? Size;
        public readonly string? Url;
        public readonly string? Filetype;
        public readonly int? Width;
        public readonly int? Height;
        public readonly string? Thumbnail;
        public readonly int? Duration;
        public MessageAttachmentParams(string? filename = null, int? size = null, string? url = null, string? filetype = null, int? width = null, int? height = null, string? thumbnail = null, int? duration = null)
        {
            Filename = filename;
            Size = size;
            Url = url;
            Filetype = filetype;
            Width = width;
            Height = height;
            Thumbnail = thumbnail;
            Duration = duration;
        }
    }
}
