// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageReactionParams
    {
        public readonly long? Id;
        public readonly long? EmojiId;
        public readonly string? Emoji;
        public readonly long? SenderId;
        public readonly string? SenderName;
        public readonly string? SenderAvatar;
        public readonly bool? Action;
        public readonly int? Count;
        public readonly long? ChannelId;
        public readonly long? MessageId;
        public readonly long? ClanId;
        public readonly int? Mode;
        public readonly long? MessageSenderId;
        public readonly bool? IsPublic;
        public readonly long? TopicId;
        public readonly long? EmojiRecentId;
        public MessageReactionParams(long? id = null, long? emojiId = null, string? emoji = null, long? senderId = null, string? senderName = null, string? senderAvatar = null, bool? action = null, int? count = null, long? channelId = null, long? messageId = null, long? clanId = null, int? mode = null, long? messageSenderId = null, bool? isPublic = null, long? topicId = null, long? emojiRecentId = null)
        {
            Id = id;
            EmojiId = emojiId;
            Emoji = emoji;
            SenderId = senderId;
            SenderName = senderName;
            SenderAvatar = senderAvatar;
            Action = action;
            Count = count;
            ChannelId = channelId;
            MessageId = messageId;
            ClanId = clanId;
            Mode = mode;
            MessageSenderId = messageSenderId;
            IsPublic = isPublic;
            TopicId = topicId;
            EmojiRecentId = emojiRecentId;
        }
    }
}
