// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageMentionParams
    {
        public readonly long? Id;
        public readonly long? UserId;
        public readonly string? Username;
        public readonly long? RoleId;
        public readonly string? Rolename;
        public readonly uint? CreateTimeSeconds;
        public readonly int? S;
        public readonly int? E;
        public MessageMentionParams(long? id = null, long? userId = null, string? username = null, long? roleId = null, string? rolename = null, uint? createTimeSeconds = null, int? s = null, int? e = null)
        {
            Id = id;
            UserId = userId;
            Username = username;
            RoleId = roleId;
            Rolename = rolename;
            CreateTimeSeconds = createTimeSeconds;
            S = s;
            E = e;
        }
    }
}
