// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class Message2InboxParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.Message2InboxRequest ToProto(in Message2InboxParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.Message2InboxRequest();
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Avatar is not null)
                proto.Avatar = p.Avatar;
            if (p.Content is not null)
                proto.Content = p.Content;
            if (p.Mentions is not null)
            {
                foreach (var item in p.Mentions)
                    proto.Mentions.Add(MessageMentionParamsMapper.ToProto(item));
            }
            if (p.Attachments is not null)
            {
                foreach (var item in p.Attachments)
                    proto.Attachments.Add(MessageAttachmentParamsMapper.ToProto(item));
            }
            if (p.Reactions is not null)
            {
                foreach (var item in p.Reactions)
                    proto.Reactions.Add(MessageReactionParamsMapper.ToProto(item));
            }
            if (p.References is not null)
            {
                foreach (var item in p.References)
                    proto.References.Add(MessageRefParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
