// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MessageButtonClickedParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.MessageButtonClicked ToProto(in MessageButtonClickedParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.MessageButtonClicked();
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ButtonId is not null)
                proto.ButtonId = p.ButtonId;
            if (p.SenderId.HasValue)
                proto.SenderId = p.SenderId.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.ExtraData is not null)
                proto.ExtraData = p.ExtraData;
            return proto;
        }
    }
}
