// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageButtonClickedParams
    {
        public readonly long? MessageId;
        public readonly long? ChannelId;
        public readonly string? ButtonId;
        public readonly long? SenderId;
        public readonly long? UserId;
        public readonly string? ExtraData;
        public MessageButtonClickedParams(long? messageId = null, long? channelId = null, string? buttonId = null, long? senderId = null, long? userId = null, string? extraData = null)
        {
            MessageId = messageId;
            ChannelId = channelId;
            ButtonId = buttonId;
            SenderId = senderId;
            UserId = userId;
            ExtraData = extraData;
        }
    }
}
