// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MessageMentionParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MessageMention ToProto(in MessageMentionParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MessageMention();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.Username is not null)
                proto.Username = p.Username;
            if (p.RoleId.HasValue)
                proto.RoleId = p.RoleId.Value;
            if (p.Rolename is not null)
                proto.Rolename = p.Rolename;
            if (p.CreateTimeSeconds.HasValue)
                proto.CreateTimeSeconds = p.CreateTimeSeconds.Value;
            if (p.S.HasValue)
                proto.S = p.S.Value;
            if (p.E.HasValue)
                proto.E = p.E.Value;
            return proto;
        }
    }
}
