// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MessageRefParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MessageRef ToProto(in MessageRefParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MessageRef();
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.MessageRefId.HasValue)
                proto.MessageRefId = p.MessageRefId.Value;
            if (p.Content is not null)
                proto.Content = p.Content;
            if (p.HasAttachment.HasValue)
                proto.HasAttachment = p.HasAttachment.Value;
            if (p.RefType.HasValue)
                proto.RefType = p.RefType.Value;
            if (p.MessageSenderId.HasValue)
                proto.MessageSenderId = p.MessageSenderId.Value;
            if (p.MessageSenderUsername is not null)
                proto.MessageSenderUsername = p.MessageSenderUsername;
            if (p.MessageSenderAvatar is not null)
                proto.MessageSenderAvatar = p.MessageSenderAvatar;
            if (p.MessageSenderClanNick is not null)
                proto.MessageSenderClanNick = p.MessageSenderClanNick;
            if (p.MessageSenderDisplayName is not null)
                proto.MessageSenderDisplayName = p.MessageSenderDisplayName;
            return proto;
        }
    }
}
