// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MessageReactionParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MessageReaction ToProto(in MessageReactionParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MessageReaction();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.EmojiId.HasValue)
                proto.EmojiId = p.EmojiId.Value;
            if (p.Emoji is not null)
                proto.Emoji = p.Emoji;
            if (p.SenderId.HasValue)
                proto.SenderId = p.SenderId.Value;
            if (p.SenderName is not null)
                proto.SenderName = p.SenderName;
            if (p.SenderAvatar is not null)
                proto.SenderAvatar = p.SenderAvatar;
            if (p.Action.HasValue)
                proto.Action = p.Action.Value;
            if (p.Count.HasValue)
                proto.Count = p.Count.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Mode.HasValue)
                proto.Mode = p.Mode.Value;
            if (p.MessageSenderId.HasValue)
                proto.MessageSenderId = p.MessageSenderId.Value;
            if (p.IsPublic.HasValue)
                proto.IsPublic = p.IsPublic.Value;
            if (p.TopicId.HasValue)
                proto.TopicId = p.TopicId.Value;
            if (p.EmojiRecentId.HasValue)
                proto.EmojiRecentId = p.EmojiRecentId.Value;
            return proto;
        }
    }
}
