// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageRefParams
    {
        public readonly long? MessageId;
        public readonly long? MessageRefId;
        public readonly string? Content;
        public readonly bool? HasAttachment;
        public readonly int? RefType;
        public readonly long? MessageSenderId;
        public readonly string? MessageSenderUsername;
        public readonly string? MessageSenderAvatar;
        public readonly string? MessageSenderClanNick;
        public readonly string? MessageSenderDisplayName;
        public MessageRefParams(long? messageId = null, long? messageRefId = null, string? content = null, bool? hasAttachment = null, int? refType = null, long? messageSenderId = null, string? messageSenderUsername = null, string? messageSenderAvatar = null, string? messageSenderClanNick = null, string? messageSenderDisplayName = null)
        {
            MessageId = messageId;
            MessageRefId = messageRefId;
            Content = content;
            HasAttachment = hasAttachment;
            RefType = refType;
            MessageSenderId = messageSenderId;
            MessageSenderUsername = messageSenderUsername;
            MessageSenderAvatar = messageSenderAvatar;
            MessageSenderClanNick = messageSenderClanNick;
            MessageSenderDisplayName = messageSenderDisplayName;
        }
    }
}
