// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MessageAttachmentParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MessageAttachment ToProto(in MessageAttachmentParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MessageAttachment();
            if (p.Filename is not null)
                proto.Filename = p.Filename;
            if (p.Size.HasValue)
                proto.Size = p.Size.Value;
            if (p.Url is not null)
                proto.Url = p.Url;
            if (p.Filetype is not null)
                proto.Filetype = p.Filetype;
            if (p.Width.HasValue)
                proto.Width = p.Width.Value;
            if (p.Height.HasValue)
                proto.Height = p.Height.Value;
            if (p.Thumbnail is not null)
                proto.Thumbnail = p.Thumbnail;
            if (p.Duration.HasValue)
                proto.Duration = p.Duration.Value;
            return proto;
        }
    }
}
