// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct Message2InboxParams
    {
        public readonly long? MessageId;
        public readonly long? ChannelId;
        public readonly long? ClanId;
        public readonly string? Avatar;
        public readonly string? Content;
        public readonly IEnumerable<MessageMentionParams>? Mentions;
        public readonly IEnumerable<MessageAttachmentParams>? Attachments;
        public readonly IEnumerable<MessageReactionParams>? Reactions;
        public readonly IEnumerable<MessageRefParams>? References;
        public Message2InboxParams(long? messageId = null, long? channelId = null, long? clanId = null, string? avatar = null, string? content = null, IEnumerable<MessageMentionParams>? mentions = null, IEnumerable<MessageAttachmentParams>? attachments = null, IEnumerable<MessageReactionParams>? reactions = null, IEnumerable<MessageRefParams>? references = null)
        {
            MessageId = messageId;
            ChannelId = channelId;
            ClanId = clanId;
            Avatar = avatar;
            Content = content;
            Mentions = mentions;
            Attachments = attachments;
            Reactions = reactions;
            References = references;
        }
    }
}
