// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MezonOauthClientParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MezonOauthClient ToProto(in MezonOauthClientParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MezonOauthClient();
            if (p.AccessTokenStrategy is not null)
                proto.AccessTokenStrategy = p.AccessTokenStrategy;
            if (p.AllowedCorsOrigins is not null)
                proto.AllowedCorsOrigins.AddRange(p.AllowedCorsOrigins);
            if (p.Audience is not null)
                proto.Audience.AddRange(p.Audience);
            if (p.AuthorizationCodeGrantAccessTokenLifespan is not null)
                proto.AuthorizationCodeGrantAccessTokenLifespan = p.AuthorizationCodeGrantAccessTokenLifespan;
            if (p.AuthorizationCodeGrantIdTokenLifespan is not null)
                proto.AuthorizationCodeGrantIdTokenLifespan = p.AuthorizationCodeGrantIdTokenLifespan;
            if (p.AuthorizationCodeGrantRefreshTokenLifespan is not null)
                proto.AuthorizationCodeGrantRefreshTokenLifespan = p.AuthorizationCodeGrantRefreshTokenLifespan;
            if (p.BackchannelLogoutSessionRequired.HasValue)
                proto.BackchannelLogoutSessionRequired = p.BackchannelLogoutSessionRequired.Value;
            if (p.BackchannelLogoutUri is not null)
                proto.BackchannelLogoutUri = p.BackchannelLogoutUri;
            if (p.ClientCredentialsGrantAccessTokenLifespan is not null)
                proto.ClientCredentialsGrantAccessTokenLifespan = p.ClientCredentialsGrantAccessTokenLifespan;
            if (p.ClientId is not null)
                proto.ClientId = p.ClientId;
            if (p.ClientName is not null)
                proto.ClientName = p.ClientName;
            if (p.ClientSecret is not null)
                proto.ClientSecret = p.ClientSecret;
            if (p.ClientSecretExpiresAt.HasValue)
                proto.ClientSecretExpiresAt = p.ClientSecretExpiresAt.Value;
            if (p.ClientUri is not null)
                proto.ClientUri = p.ClientUri;
            if (p.Contacts is not null)
                proto.Contacts.AddRange(p.Contacts);
            if (p.CreatedAtSeconds.HasValue)
                proto.CreatedAtSeconds = p.CreatedAtSeconds.Value;
            if (p.FrontchannelLogoutSessionRequired.HasValue)
                proto.FrontchannelLogoutSessionRequired = p.FrontchannelLogoutSessionRequired.Value;
            if (p.FrontchannelLogoutUri is not null)
                proto.FrontchannelLogoutUri = p.FrontchannelLogoutUri;
            if (p.GrantTypes is not null)
                proto.GrantTypes.AddRange(p.GrantTypes);
            if (p.ImplicitGrantAccessTokenLifespan is not null)
                proto.ImplicitGrantAccessTokenLifespan = p.ImplicitGrantAccessTokenLifespan;
            if (p.ImplicitGrantIdTokenLifespan is not null)
                proto.ImplicitGrantIdTokenLifespan = p.ImplicitGrantIdTokenLifespan;
            if (p.Jwks is not null)
                proto.Jwks.AddRange(p.Jwks);
            if (p.JwksUri is not null)
                proto.JwksUri = p.JwksUri;
            if (p.JwtBearerGrantAccessTokenLifespan is not null)
                proto.JwtBearerGrantAccessTokenLifespan = p.JwtBearerGrantAccessTokenLifespan;
            if (p.LogoUri is not null)
                proto.LogoUri = p.LogoUri;
            if (p.Owner is not null)
                proto.Owner = p.Owner;
            if (p.PolicyUri is not null)
                proto.PolicyUri = p.PolicyUri;
            if (p.PostLogoutRedirectUris is not null)
                proto.PostLogoutRedirectUris.AddRange(p.PostLogoutRedirectUris);
            if (p.RedirectUris is not null)
                proto.RedirectUris.AddRange(p.RedirectUris);
            if (p.RefreshTokenGrantAccessTokenLifespan is not null)
                proto.RefreshTokenGrantAccessTokenLifespan = p.RefreshTokenGrantAccessTokenLifespan;
            if (p.RefreshTokenGrantIdTokenLifespan is not null)
                proto.RefreshTokenGrantIdTokenLifespan = p.RefreshTokenGrantIdTokenLifespan;
            if (p.RefreshTokenGrantRefreshTokenLifespan is not null)
                proto.RefreshTokenGrantRefreshTokenLifespan = p.RefreshTokenGrantRefreshTokenLifespan;
            if (p.RegistrationAccessToken is not null)
                proto.RegistrationAccessToken = p.RegistrationAccessToken;
            if (p.RegistrationClientUri is not null)
                proto.RegistrationClientUri = p.RegistrationClientUri;
            if (p.RequestObjectSigningAlg is not null)
                proto.RequestObjectSigningAlg = p.RequestObjectSigningAlg;
            if (p.RequestUris is not null)
                proto.RequestUris.AddRange(p.RequestUris);
            if (p.ResponseTypes is not null)
                proto.ResponseTypes.AddRange(p.ResponseTypes);
            if (p.Scope is not null)
                proto.Scope = p.Scope;
            if (p.SectorIdentifierUri is not null)
                proto.SectorIdentifierUri = p.SectorIdentifierUri;
            if (p.SkipConsent.HasValue)
                proto.SkipConsent = p.SkipConsent.Value;
            if (p.SkipLogoutConsent.HasValue)
                proto.SkipLogoutConsent = p.SkipLogoutConsent.Value;
            if (p.SubjectType is not null)
                proto.SubjectType = p.SubjectType;
            if (p.TokenEndpointAuthMethod is not null)
                proto.TokenEndpointAuthMethod = p.TokenEndpointAuthMethod;
            if (p.TokenEndpointAuthSigningAlg is not null)
                proto.TokenEndpointAuthSigningAlg = p.TokenEndpointAuthSigningAlg;
            if (p.TosUri is not null)
                proto.TosUri = p.TosUri;
            if (p.UpdatedAtSeconds.HasValue)
                proto.UpdatedAtSeconds = p.UpdatedAtSeconds.Value;
            if (p.UserinfoSignedResponseAlg is not null)
                proto.UserinfoSignedResponseAlg = p.UserinfoSignedResponseAlg;
            return proto;
        }
    }
}
