// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MezonOauthClientParams
    {
        public readonly string? AccessTokenStrategy;
        public readonly IEnumerable<string?>? AllowedCorsOrigins;
        public readonly IEnumerable<string?>? Audience;
        public readonly string? AuthorizationCodeGrantAccessTokenLifespan;
        public readonly string? AuthorizationCodeGrantIdTokenLifespan;
        public readonly string? AuthorizationCodeGrantRefreshTokenLifespan;
        public readonly bool? BackchannelLogoutSessionRequired;
        public readonly string? BackchannelLogoutUri;
        public readonly string? ClientCredentialsGrantAccessTokenLifespan;
        public readonly string? ClientId;
        public readonly string? ClientName;
        public readonly string? ClientSecret;
        public readonly int? ClientSecretExpiresAt;
        public readonly string? ClientUri;
        public readonly IEnumerable<string?>? Contacts;
        public readonly uint? CreatedAtSeconds;
        public readonly bool? FrontchannelLogoutSessionRequired;
        public readonly string? FrontchannelLogoutUri;
        public readonly IEnumerable<string?>? GrantTypes;
        public readonly string? ImplicitGrantAccessTokenLifespan;
        public readonly string? ImplicitGrantIdTokenLifespan;
        public readonly IEnumerable<string?>? Jwks;
        public readonly string? JwksUri;
        public readonly string? JwtBearerGrantAccessTokenLifespan;
        public readonly string? LogoUri;
        public readonly string? Owner;
        public readonly string? PolicyUri;
        public readonly IEnumerable<string?>? PostLogoutRedirectUris;
        public readonly IEnumerable<string?>? RedirectUris;
        public readonly string? RefreshTokenGrantAccessTokenLifespan;
        public readonly string? RefreshTokenGrantIdTokenLifespan;
        public readonly string? RefreshTokenGrantRefreshTokenLifespan;
        public readonly string? RegistrationAccessToken;
        public readonly string? RegistrationClientUri;
        public readonly string? RequestObjectSigningAlg;
        public readonly IEnumerable<string?>? RequestUris;
        public readonly IEnumerable<string?>? ResponseTypes;
        public readonly string? Scope;
        public readonly string? SectorIdentifierUri;
        public readonly bool? SkipConsent;
        public readonly bool? SkipLogoutConsent;
        public readonly string? SubjectType;
        public readonly string? TokenEndpointAuthMethod;
        public readonly string? TokenEndpointAuthSigningAlg;
        public readonly string? TosUri;
        public readonly uint? UpdatedAtSeconds;
        public readonly string? UserinfoSignedResponseAlg;
        public MezonOauthClientParams(string? accessTokenStrategy = null, IEnumerable<string?>? allowedCorsOrigins = null, IEnumerable<string?>? audience = null, string? authorizationCodeGrantAccessTokenLifespan = null, string? authorizationCodeGrantIdTokenLifespan = null, string? authorizationCodeGrantRefreshTokenLifespan = null, bool? backchannelLogoutSessionRequired = null, string? backchannelLogoutUri = null, string? clientCredentialsGrantAccessTokenLifespan = null, string? clientId = null, string? clientName = null, string? clientSecret = null, int? clientSecretExpiresAt = null, string? clientUri = null, IEnumerable<string?>? contacts = null, uint? createdAtSeconds = null, bool? frontchannelLogoutSessionRequired = null, string? frontchannelLogoutUri = null, IEnumerable<string?>? grantTypes = null, string? implicitGrantAccessTokenLifespan = null, string? implicitGrantIdTokenLifespan = null, IEnumerable<string?>? jwks = null, string? jwksUri = null, string? jwtBearerGrantAccessTokenLifespan = null, string? logoUri = null, string? owner = null, string? policyUri = null, IEnumerable<string?>? postLogoutRedirectUris = null, IEnumerable<string?>? redirectUris = null, string? refreshTokenGrantAccessTokenLifespan = null, string? refreshTokenGrantIdTokenLifespan = null, string? refreshTokenGrantRefreshTokenLifespan = null, string? registrationAccessToken = null, string? registrationClientUri = null, string? requestObjectSigningAlg = null, IEnumerable<string?>? requestUris = null, IEnumerable<string?>? responseTypes = null, string? scope = null, string? sectorIdentifierUri = null, bool? skipConsent = null, bool? skipLogoutConsent = null, string? subjectType = null, string? tokenEndpointAuthMethod = null, string? tokenEndpointAuthSigningAlg = null, string? tosUri = null, uint? updatedAtSeconds = null, string? userinfoSignedResponseAlg = null)
        {
            AccessTokenStrategy = accessTokenStrategy;
            AllowedCorsOrigins = allowedCorsOrigins;
            Audience = audience;
            AuthorizationCodeGrantAccessTokenLifespan = authorizationCodeGrantAccessTokenLifespan;
            AuthorizationCodeGrantIdTokenLifespan = authorizationCodeGrantIdTokenLifespan;
            AuthorizationCodeGrantRefreshTokenLifespan = authorizationCodeGrantRefreshTokenLifespan;
            BackchannelLogoutSessionRequired = backchannelLogoutSessionRequired;
            BackchannelLogoutUri = backchannelLogoutUri;
            ClientCredentialsGrantAccessTokenLifespan = clientCredentialsGrantAccessTokenLifespan;
            ClientId = clientId;
            ClientName = clientName;
            ClientSecret = clientSecret;
            ClientSecretExpiresAt = clientSecretExpiresAt;
            ClientUri = clientUri;
            Contacts = contacts;
            CreatedAtSeconds = createdAtSeconds;
            FrontchannelLogoutSessionRequired = frontchannelLogoutSessionRequired;
            FrontchannelLogoutUri = frontchannelLogoutUri;
            GrantTypes = grantTypes;
            ImplicitGrantAccessTokenLifespan = implicitGrantAccessTokenLifespan;
            ImplicitGrantIdTokenLifespan = implicitGrantIdTokenLifespan;
            Jwks = jwks;
            JwksUri = jwksUri;
            JwtBearerGrantAccessTokenLifespan = jwtBearerGrantAccessTokenLifespan;
            LogoUri = logoUri;
            Owner = owner;
            PolicyUri = policyUri;
            PostLogoutRedirectUris = postLogoutRedirectUris;
            RedirectUris = redirectUris;
            RefreshTokenGrantAccessTokenLifespan = refreshTokenGrantAccessTokenLifespan;
            RefreshTokenGrantIdTokenLifespan = refreshTokenGrantIdTokenLifespan;
            RefreshTokenGrantRefreshTokenLifespan = refreshTokenGrantRefreshTokenLifespan;
            RegistrationAccessToken = registrationAccessToken;
            RegistrationClientUri = registrationClientUri;
            RequestObjectSigningAlg = requestObjectSigningAlg;
            RequestUris = requestUris;
            ResponseTypes = responseTypes;
            Scope = scope;
            SectorIdentifierUri = sectorIdentifierUri;
            SkipConsent = skipConsent;
            SkipLogoutConsent = skipLogoutConsent;
            SubjectType = subjectType;
            TokenEndpointAuthMethod = tokenEndpointAuthMethod;
            TokenEndpointAuthSigningAlg = tokenEndpointAuthSigningAlg;
            TosUri = tosUri;
            UpdatedAtSeconds = updatedAtSeconds;
            UserinfoSignedResponseAlg = userinfoSignedResponseAlg;
        }
    }
}
