// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MultipartUploadAttachmentPartParams
    {
        public readonly int? PartNumber;
        public readonly string? ETag;
        public MultipartUploadAttachmentPartParams(int? partNumber = null, string? eTag = null)
        {
            PartNumber = partNumber;
            ETag = eTag;
        }
    }
}
