// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class MultipartUploadAttachmentFinishParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.MultipartUploadAttachmentFinishRequest ToProto(in MultipartUploadAttachmentFinishParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.MultipartUploadAttachmentFinishRequest();
            if (p.UploadId is not null)
                proto.UploadId = p.UploadId;
            if (p.Parts is not null)
            {
                foreach (var item in p.Parts)
                    proto.Parts.Add(MultipartUploadAttachmentPartParamsMapper.ToProto(item));
            }
            if (p.Filename is not null)
                proto.Filename = p.Filename;
            return proto;
        }
    }
}
