// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MultipartUploadAttachmentFinishParams
    {
        public readonly string? UploadId;
        public readonly IEnumerable<MultipartUploadAttachmentPartParams>? Parts;
        public readonly string? Filename;
        public MultipartUploadAttachmentFinishParams(string? uploadId = null, IEnumerable<MultipartUploadAttachmentPartParams>? parts = null, string? filename = null)
        {
            UploadId = uploadId;
            Parts = parts;
            Filename = filename;
        }
    }
}
