// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class NotificationChannelParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.NotificationChannel ToProto(in NotificationChannelParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.NotificationChannel();
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            return proto;
        }
    }
}
