// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationChannelParams
    {
        public readonly long? ChannelId;
        public NotificationChannelParams(long? channelId = null)
        {
            ChannelId = channelId;
        }
    }
}
