// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class OnboardingAnswerParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.OnboardingAnswer ToProto(in OnboardingAnswerParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.OnboardingAnswer();
            if (p.Title is not null)
                proto.Title = p.Title;
            if (p.Description is not null)
                proto.Description = p.Description;
            if (p.Emoji is not null)
                proto.Emoji = p.Emoji;
            if (p.ImageUrl is not null)
                proto.ImageUrl = p.ImageUrl;
            return proto;
        }
    }
}
