// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct OnboardingAnswerParams
    {
        public readonly string? Title;
        public readonly string? Description;
        public readonly string? Emoji;
        public readonly string? ImageUrl;
        public OnboardingAnswerParams(string? title = null, string? description = null, string? emoji = null, string? imageUrl = null)
        {
            Title = title;
            Description = description;
            Emoji = emoji;
            ImageUrl = imageUrl;
        }
    }
}
