// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class PermissionRoleChannelListEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.PermissionRoleChannelListEventRequest ToProto(in PermissionRoleChannelListEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.PermissionRoleChannelListEventRequest();
            if (p.RoleId.HasValue)
                proto.RoleId = p.RoleId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            return proto;
        }
    }
}
