// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PermissionUpdateParams
    {
        public readonly long? PermissionId;
        public readonly string? Slug;
        public readonly int? Type;
        public PermissionUpdateParams(long? permissionId = null, string? slug = null, int? type = null)
        {
            PermissionId = permissionId;
            Slug = slug;
            Type = type;
        }
    }
}
