// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class PermissionUpdateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.PermissionUpdate ToProto(in PermissionUpdateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.PermissionUpdate();
            if (p.PermissionId.HasValue)
                proto.PermissionId = p.PermissionId.Value;
            if (p.Slug is not null)
                proto.Slug = p.Slug;
            if (p.Type.HasValue)
                proto.Type = p.Type.Value;
            return proto;
        }
    }
}
