// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PermissionRoleChannelListEventParams
    {
        public readonly long? RoleId;
        public readonly long? ChannelId;
        public readonly long? UserId;
        public PermissionRoleChannelListEventParams(long? roleId = null, long? channelId = null, long? userId = null)
        {
            RoleId = roleId;
            ChannelId = channelId;
            UserId = userId;
        }
    }
}
