// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PinMessageParams
    {
        public readonly long? MessageId;
        public readonly long? ChannelId;
        public readonly long? ClanId;
        public PinMessageParams(long? messageId = null, long? channelId = null, long? clanId = null)
        {
            MessageId = messageId;
            ChannelId = channelId;
            ClanId = clanId;
        }
    }
}
