// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class PinMessageParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.PinMessageRequest ToProto(in PinMessageParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.PinMessageRequest();
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
