// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class PubKeyParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.PubKey ToProto(in PubKeyParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.PubKey();
            if (p.Encr is not null)
                proto.Encr = Google.Protobuf.ByteString.CopyFrom(p.Encr);
            if (p.Sign is not null)
                proto.Sign = Google.Protobuf.ByteString.CopyFrom(p.Sign);
            return proto;
        }
    }
}
