// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PubKeyParams
    {
        public readonly byte[]? Encr;
        public readonly byte[]? Sign;
        public PubKeyParams(byte[]? encr = null, byte[]? sign = null)
        {
            Encr = encr;
            Sign = sign;
        }
    }
}
