// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PushPubKeyParams
    {
        public readonly PubKeyParams PK;
        public PushPubKeyParams(PubKeyParams pK = default)
        {
            PK = pK;
        }
    }
}
