// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class PushPubKeyParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.PushPubKeyRequest ToProto(in PushPubKeyParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.PushPubKeyRequest();
            proto.PK = PubKeyParamsMapper.ToProto(p.PK);
            return proto;
        }
    }
}
