// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class QuickMenuAccessParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.QuickMenuAccess ToProto(in QuickMenuAccessParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.QuickMenuAccess();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.BotId.HasValue)
                proto.BotId = p.BotId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.MenuName is not null)
                proto.MenuName = p.MenuName;
            if (p.Background is not null)
                proto.Background = p.Background;
            if (p.ActionMsg is not null)
                proto.ActionMsg = p.ActionMsg;
            if (p.MenuType.HasValue)
                proto.MenuType = p.MenuType.Value;
            return proto;
        }
    }
}
