// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RegistFcmDeviceTokenParams
    {
        public readonly string? Token;
        public readonly string? DeviceId;
        public readonly string? Platform;
        public readonly string? VoipToken;
        public RegistFcmDeviceTokenParams(string? token = null, string? deviceId = null, string? platform = null, string? voipToken = null)
        {
            Token = token;
            DeviceId = deviceId;
            Platform = platform;
            VoipToken = voipToken;
        }
    }
}
