// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class RegistFcmDeviceTokenParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.RegistFcmDeviceTokenRequest ToProto(in RegistFcmDeviceTokenParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.RegistFcmDeviceTokenRequest();
            if (p.Token is not null)
                proto.Token = p.Token;
            if (p.DeviceId is not null)
                proto.DeviceId = p.DeviceId;
            if (p.Platform is not null)
                proto.Platform = p.Platform;
            if (p.VoipToken is not null)
                proto.VoipToken = p.VoipToken;
            return proto;
        }
    }
}
