// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RegistrationEmailParams
    {
        public readonly IReadOnlyDictionary<string, string>? Vars;
        public readonly string? Email;
        public readonly string? Password;
        public readonly string? OldPassword;
        public readonly string? Username;
        public readonly string? DisplayName;
        public readonly string? AvatarUrl;
        public readonly string? Dob;
        public RegistrationEmailParams(IReadOnlyDictionary<string, string>? vars = null, string? email = null, string? password = null, string? oldPassword = null, string? username = null, string? displayName = null, string? avatarUrl = null, string? dob = null)
        {
            Vars = vars;
            Email = email;
            Password = password;
            OldPassword = oldPassword;
            Username = username;
            DisplayName = displayName;
            AvatarUrl = avatarUrl;
            Dob = dob;
        }
    }
}
