// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class ReportMessageAbuseReqestParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.ReportMessageAbuseReqest ToProto(in ReportMessageAbuseReqestParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.ReportMessageAbuseReqest();
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.AbuseType is not null)
                proto.AbuseType = p.AbuseType;
            return proto;
        }
    }
}
