// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ReportMessageAbuseReqestParams
    {
        public readonly long? MessageId;
        public readonly string? AbuseType;
        public ReportMessageAbuseReqestParams(long? messageId = null, string? abuseType = null)
        {
            MessageId = messageId;
            AbuseType = abuseType;
        }
    }
}
