// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class RoleListEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.RoleListEventRequest ToProto(in RoleListEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.RoleListEventRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Limit.HasValue)
                proto.Limit = p.Limit.Value;
            if (p.State.HasValue)
                proto.State = p.State.Value;
            if (p.Cursor is not null)
                proto.Cursor = p.Cursor;
            return proto;
        }
    }
}
