// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleListEventParams
    {
        public readonly long? ClanId;
        public readonly int? Limit;
        public readonly int? State;
        public readonly string? Cursor;
        public RoleListEventParams(long? clanId = null, int? limit = null, int? state = null, string? cursor = null)
        {
            ClanId = clanId;
            Limit = limit;
            State = state;
            Cursor = cursor;
        }
    }
}
