// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleOrderUpdateParams
    {
        public readonly long? RoleId;
        public readonly int? Order;
        public RoleOrderUpdateParams(long? roleId = null, int? order = null)
        {
            RoleId = roleId;
            Order = order;
        }
    }
}
