// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class RoleOrderUpdateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.RoleOrderUpdate ToProto(in RoleOrderUpdateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.RoleOrderUpdate();
            if (p.RoleId.HasValue)
                proto.RoleId = p.RoleId.Value;
            if (p.Order.HasValue)
                proto.Order = p.Order.Value;
            return proto;
        }
    }
}
