// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SdTopicDetailParams
    {
        public readonly long? TopicId;
        public SdTopicDetailParams(long? topicId = null)
        {
            TopicId = topicId;
        }
    }
}
