// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SdTopicParams
    {
        public readonly long? MessageId;
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public SdTopicParams(long? messageId = null, long? clanId = null, long? channelId = null)
        {
            MessageId = messageId;
            ClanId = clanId;
            ChannelId = channelId;
        }
    }
}
