// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SdTopicDetailParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SdTopicDetailRequest ToProto(in SdTopicDetailParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SdTopicDetailRequest();
            if (p.TopicId.HasValue)
                proto.TopicId = p.TopicId.Value;
            return proto;
        }
    }
}
