// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SearchMentionUsersParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly string? Text;
        public SearchMentionUsersParams(long? clanId = null, long? channelId = null, string? text = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            Text = text;
        }
    }
}
