// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SearchMessageParams
    {
        public readonly IEnumerable<FilterParamParams>? Filters;
        public readonly int? From;
        public readonly int? Size;
        public readonly IEnumerable<SortParamParams>? Sorts;
        public SearchMessageParams(IEnumerable<FilterParamParams>? filters = null, int? from = null, int? size = null, IEnumerable<SortParamParams>? sorts = null)
        {
            Filters = filters;
            From = from;
            Size = size;
            Sorts = sorts;
        }
    }
}
