// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SearchMentionUsersParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SearchMentionUsersRequest ToProto(in SearchMentionUsersParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SearchMentionUsersRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Text is not null)
                proto.Text = p.Text;
            return proto;
        }
    }
}
