// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SearchThreadParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly string? Label;
        public SearchThreadParams(long? clanId = null, long? channelId = null, string? label = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            Label = label;
        }
    }
}
