// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SearchCtrlKParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SearchCtrlKRequest ToProto(in SearchCtrlKParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SearchCtrlKRequest();
            if (p.Text is not null)
                proto.Text = p.Text;
            if (p.Type.HasValue)
                proto.Type = p.Type.Value;
            return proto;
        }
    }
}
