// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SearchMessageParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SearchMessageRequest ToProto(in SearchMessageParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SearchMessageRequest();
            if (p.Filters is not null)
            {
                foreach (var item in p.Filters)
                    proto.Filters.Add(FilterParamParamsMapper.ToProto(item));
            }
            if (p.From.HasValue)
                proto.From = p.From.Value;
            if (p.Size.HasValue)
                proto.Size = p.Size.Value;
            if (p.Sorts is not null)
            {
                foreach (var item in p.Sorts)
                    proto.Sorts.Add(SortParamParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
