// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SearchCtrlKParams
    {
        public readonly string? Text;
        public readonly int? Type;
        public SearchCtrlKParams(string? text = null, int? type = null)
        {
            Text = text;
            Type = type;
        }
    }
}
