// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SessionLogoutParams
    {
        public readonly string? Token;
        public readonly string? RefreshToken;
        public readonly string? DeviceId;
        public readonly string? FcmToken;
        public readonly string? Platform;
        public SessionLogoutParams(string? token = null, string? refreshToken = null, string? deviceId = null, string? fcmToken = null, string? platform = null)
        {
            Token = token;
            RefreshToken = refreshToken;
            DeviceId = deviceId;
            FcmToken = fcmToken;
            Platform = platform;
        }
    }
}
