// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SessionLogoutParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SessionLogoutRequest ToProto(in SessionLogoutParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SessionLogoutRequest();
            if (p.Token is not null)
                proto.Token = p.Token;
            if (p.RefreshToken is not null)
                proto.RefreshToken = p.RefreshToken;
            if (p.DeviceId is not null)
                proto.DeviceId = p.DeviceId;
            if (p.FcmToken is not null)
                proto.FcmToken = p.FcmToken;
            if (p.Platform is not null)
                proto.Platform = p.Platform;
            return proto;
        }
    }
}
