// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SetDefaultNotificationParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SetDefaultNotificationRequest ToProto(in SetDefaultNotificationParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SetDefaultNotificationRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.NotificationType.HasValue)
                proto.NotificationType = p.NotificationType.Value;
            if (p.CategoryId.HasValue)
                proto.CategoryId = p.CategoryId.Value;
            return proto;
        }
    }
}
