// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SetDefaultNotificationParams
    {
        public readonly long? ClanId;
        public readonly int? NotificationType;
        public readonly long? CategoryId;
        public SetDefaultNotificationParams(long? clanId = null, int? notificationType = null, long? categoryId = null)
        {
            ClanId = clanId;
            NotificationType = notificationType;
            CategoryId = categoryId;
        }
    }
}
