// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SetMuteParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SetMuteRequest ToProto(in SetMuteParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SetMuteRequest();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.MuteTime.HasValue)
                proto.MuteTime = p.MuteTime.Value;
            if (p.Active.HasValue)
                proto.Active = p.Active.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
