// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SetMuteParams
    {
        public readonly long? Id;
        public readonly int? MuteTime;
        public readonly int? Active;
        public readonly long? ClanId;
        public SetMuteParams(long? id = null, int? muteTime = null, int? active = null, long? clanId = null)
        {
            Id = id;
            MuteTime = muteTime;
            Active = active;
            ClanId = clanId;
        }
    }
}
