// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SetNotificationParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SetNotificationRequest ToProto(in SetNotificationParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SetNotificationRequest();
            if (p.ChannelCategoryId.HasValue)
                proto.ChannelCategoryId = p.ChannelCategoryId.Value;
            if (p.NotificationType.HasValue)
                proto.NotificationType = p.NotificationType.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
