// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SetNotificationParams
    {
        public readonly long? ChannelCategoryId;
        public readonly int? NotificationType;
        public readonly long? ClanId;
        public SetNotificationParams(long? channelCategoryId = null, int? notificationType = null, long? clanId = null)
        {
            ChannelCategoryId = channelCategoryId;
            NotificationType = notificationType;
            ClanId = clanId;
        }
    }
}
