// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SortParamParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SortParam ToProto(in SortParamParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SortParam();
            if (p.FieldName is not null)
                proto.FieldName = p.FieldName;
            if (p.Order is not null)
                proto.Order = p.Order;
            return proto;
        }
    }
}
