// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SortParamParams
    {
        public readonly string? FieldName;
        public readonly string? Order;
        public SortParamParams(string? fieldName = null, string? order = null)
        {
            FieldName = fieldName;
            Order = order;
        }
    }
}
