// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class StatusUnfollowParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.StatusUnfollow ToProto(in StatusUnfollowParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.StatusUnfollow();
            if (p.UserIds is not null)
            {
                foreach (var item in p.UserIds)
                    if (item.HasValue) proto.UserIds.Add(item.Value);
            }
            return proto;
        }
    }
}
