// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class StatusFollowParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.StatusFollow ToProto(in StatusFollowParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.StatusFollow();
            if (p.UserIds is not null)
            {
                foreach (var item in p.UserIds)
                    if (item.HasValue) proto.UserIds.Add(item.Value);
            }
            if (p.Usernames is not null)
                proto.Usernames.AddRange(p.Usernames);
            return proto;
        }
    }
}
