// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusFollowParams
    {
        public readonly IEnumerable<long?>? UserIds;
        public readonly IEnumerable<string?>? Usernames;
        public StatusFollowParams(IEnumerable<long?>? userIds = null, IEnumerable<string?>? usernames = null)
        {
            UserIds = userIds;
            Usernames = usernames;
        }
    }
}
