// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusUpdateParams
    {
        public readonly string? Status;
        public StatusUpdateParams(string? status = null)
        {
            Status = status;
        }
    }
}
