// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusUnfollowParams
    {
        public readonly IEnumerable<long?>? UserIds;
        public StatusUnfollowParams(IEnumerable<long?>? userIds = null)
        {
            UserIds = userIds;
        }
    }
}
