// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class StatusUpdateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.StatusUpdate ToProto(in StatusUpdateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.StatusUpdate();
            if (p.Status is not null)
                proto.Status = p.Status;
            return proto;
        }
    }
}
