// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamHttpCallbackParams
    {
        public readonly long? Id;
        public readonly long? ClientId;
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly long? UserId;
        public readonly int? Action;
        public readonly bool? IsPublisher;
        public readonly string? Token;
        public StreamHttpCallbackParams(long? id = null, long? clientId = null, long? clanId = null, long? channelId = null, long? userId = null, int? action = null, bool? isPublisher = null, string? token = null)
        {
            Id = id;
            ClientId = clientId;
            ClanId = clanId;
            ChannelId = channelId;
            UserId = userId;
            Action = action;
            IsPublisher = isPublisher;
            Token = token;
        }
    }
}
