// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class StreamHttpCallbackParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.StreamHttpCallbackRequest ToProto(in StreamHttpCallbackParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.StreamHttpCallbackRequest();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.ClientId.HasValue)
                proto.ClientId = p.ClientId.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.Action.HasValue)
                proto.Action = p.Action.Value;
            if (p.IsPublisher.HasValue)
                proto.IsPublisher = p.IsPublisher.Value;
            if (p.Token is not null)
                proto.Token = p.Token;
            return proto;
        }
    }
}
