// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class SystemMessageParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.SystemMessageRequest ToProto(in SystemMessageParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.SystemMessageRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.WelcomeRandom is not null)
                proto.WelcomeRandom = p.WelcomeRandom;
            if (p.WelcomeSticker is not null)
                proto.WelcomeSticker = p.WelcomeSticker;
            if (p.BoostMessage is not null)
                proto.BoostMessage = p.BoostMessage;
            if (p.SetupTips is not null)
                proto.SetupTips = p.SetupTips;
            if (p.HideAuditLog.HasValue)
                proto.HideAuditLog = p.HideAuditLog.Value;
            return proto;
        }
    }
}
