// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SystemMessageParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly string? WelcomeRandom;
        public readonly string? WelcomeSticker;
        public readonly string? BoostMessage;
        public readonly string? SetupTips;
        public readonly bool? HideAuditLog;
        public SystemMessageParams(long? clanId = null, long? channelId = null, string? welcomeRandom = null, string? welcomeSticker = null, string? boostMessage = null, string? setupTips = null, bool? hideAuditLog = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            WelcomeRandom = welcomeRandom;
            WelcomeSticker = welcomeSticker;
            BoostMessage = boostMessage;
            SetupTips = setupTips;
            HideAuditLog = hideAuditLog;
        }
    }
}
