// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class TransferOwnershipParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.TransferOwnershipRequest ToProto(in TransferOwnershipParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.TransferOwnershipRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.NewOwnerId.HasValue)
                proto.NewOwnerId = p.NewOwnerId.Value;
            return proto;
        }
    }
}
