// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct TransferOwnershipParams
    {
        public readonly long? ClanId;
        public readonly long? NewOwnerId;
        public TransferOwnershipParams(long? clanId = null, long? newOwnerId = null)
        {
            ClanId = clanId;
            NewOwnerId = newOwnerId;
        }
    }
}
