// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateUsernameParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateUsernameRequest ToProto(in UpdateUsernameParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateUsernameRequest();
            if (p.Username is not null)
                proto.Username = p.Username;
            if (p.DisplayName is not null)
                proto.DisplayName = p.DisplayName;
            return proto;
        }
    }
}
