// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateClanDescParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateClanDescRequest ToProto(in UpdateClanDescParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateClanDescRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ClanName is not null)
                proto.ClanName = p.ClanName;
            if (p.Logo is not null)
                proto.Logo = p.Logo;
            if (p.Banner is not null)
                proto.Banner = p.Banner;
            if (p.Status.HasValue)
                proto.Status = p.Status.Value;
            if (p.IsOnboarding.HasValue)
                proto.IsOnboarding = p.IsOnboarding.Value;
            if (p.WelcomeChannelId.HasValue)
                proto.WelcomeChannelId = p.WelcomeChannelId.Value;
            if (p.OnboardingBanner is not null)
                proto.OnboardingBanner = p.OnboardingBanner;
            if (p.IsCommunity.HasValue)
                proto.IsCommunity = p.IsCommunity.Value;
            if (p.CommunityBanner is not null)
                proto.CommunityBanner = p.CommunityBanner;
            if (p.Description is not null)
                proto.Description = p.Description;
            if (p.About is not null)
                proto.About = p.About;
            if (p.ShortUrl is not null)
                proto.ShortUrl = p.ShortUrl;
            if (p.PreventAnonymous.HasValue)
                proto.PreventAnonymous = p.PreventAnonymous.Value;
            return proto;
        }
    }
}
