// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateEventParams
    {
        public readonly string? Title;
        public readonly string? Logo;
        public readonly string? Description;
        public readonly long? EventId;
        public readonly long? ChannelId;
        public readonly string? Address;
        public readonly uint? StartTimeSeconds;
        public readonly uint? EndTimeSeconds;
        public readonly long? ClanId;
        public readonly long? CreatorId;
        public readonly long? ChannelVoiceId;
        public readonly long? ChannelIdOld;
        public readonly int? RepeatType;
        public UpdateEventParams(string? title = null, string? logo = null, string? description = null, long? eventId = null, long? channelId = null, string? address = null, uint? startTimeSeconds = null, uint? endTimeSeconds = null, long? clanId = null, long? creatorId = null, long? channelVoiceId = null, long? channelIdOld = null, int? repeatType = null)
        {
            Title = title;
            Logo = logo;
            Description = description;
            EventId = eventId;
            ChannelId = channelId;
            Address = address;
            StartTimeSeconds = startTimeSeconds;
            EndTimeSeconds = endTimeSeconds;
            ClanId = clanId;
            CreatorId = creatorId;
            ChannelVoiceId = channelVoiceId;
            ChannelIdOld = channelIdOld;
            RepeatType = repeatType;
        }
    }
}
