// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateRoleOrderParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateRoleOrderRequest ToProto(in UpdateRoleOrderParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateRoleOrderRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Roles is not null)
            {
                foreach (var item in p.Roles)
                    proto.Roles.Add(RoleOrderUpdateParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
