// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateChannelDescParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly string? ChannelLabel;
        public readonly long? CategoryId;
        public readonly long? AppId;
        public readonly string? Topic;
        public readonly int? AgeRestricted;
        public readonly int? E2ee;
        public readonly string? ChannelAvatar;
        public UpdateChannelDescParams(long? clanId = null, long? channelId = null, string? channelLabel = null, long? categoryId = null, long? appId = null, string? topic = null, int? ageRestricted = null, int? e2ee = null, string? channelAvatar = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            ChannelLabel = channelLabel;
            CategoryId = categoryId;
            AppId = appId;
            Topic = topic;
            AgeRestricted = ageRestricted;
            E2ee = e2ee;
            ChannelAvatar = channelAvatar;
        }
    }
}
