// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateClanWebhookParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateClanWebhookRequest ToProto(in UpdateClanWebhookParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateClanWebhookRequest();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.WebhookName is not null)
                proto.WebhookName = p.WebhookName;
            if (p.Avatar is not null)
                proto.Avatar = p.Avatar;
            if (p.ResetToken.HasValue)
                proto.ResetToken = p.ResetToken.Value;
            return proto;
        }
    }
}
