// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateRoleParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateRoleRequest ToProto(in UpdateRoleParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateRoleRequest();
            if (p.RoleId.HasValue)
                proto.RoleId = p.RoleId.Value;
            if (p.Title is not null)
                proto.Title = p.Title;
            if (p.Color is not null)
                proto.Color = p.Color;
            if (p.RoleIcon is not null)
                proto.RoleIcon = p.RoleIcon;
            if (p.Description is not null)
                proto.Description = p.Description;
            if (p.DisplayOnline.HasValue)
                proto.DisplayOnline = p.DisplayOnline.Value;
            if (p.AllowMention.HasValue)
                proto.AllowMention = p.AllowMention.Value;
            if (p.AddUserIds is not null)
            {
                foreach (var item in p.AddUserIds)
                    if (item.HasValue) proto.AddUserIds.Add(item.Value);
            }
            if (p.ActivePermissionIds is not null)
            {
                foreach (var item in p.ActivePermissionIds)
                    if (item.HasValue) proto.ActivePermissionIds.Add(item.Value);
            }
            if (p.RemoveUserIds is not null)
            {
                foreach (var item in p.RemoveUserIds)
                    if (item.HasValue) proto.RemoveUserIds.Add(item.Value);
            }
            if (p.RemovePermissionIds is not null)
            {
                foreach (var item in p.RemovePermissionIds)
                    if (item.HasValue) proto.RemovePermissionIds.Add(item.Value);
            }
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.MaxPermissionId.HasValue)
                proto.MaxPermissionId = p.MaxPermissionId.Value;
            return proto;
        }
    }
}
