// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateOnboardingStepParams
    {
        public readonly long? ClanId;
        public readonly int? OnboardingStep;
        public UpdateOnboardingStepParams(long? clanId = null, int? onboardingStep = null)
        {
            ClanId = clanId;
            OnboardingStep = onboardingStep;
        }
    }
}
