// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateRoleOrderParams
    {
        public readonly long? ClanId;
        public readonly IEnumerable<RoleOrderUpdateParams>? Roles;
        public UpdateRoleOrderParams(long? clanId = null, IEnumerable<RoleOrderUpdateParams>? roles = null)
        {
            ClanId = clanId;
            Roles = roles;
        }
    }
}
