// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateCategoryDescParams
    {
        public readonly long? CategoryId;
        public readonly string? CategoryName;
        public readonly long? ClanId;
        public UpdateCategoryDescParams(long? categoryId = null, string? categoryName = null, long? clanId = null)
        {
            CategoryId = categoryId;
            CategoryName = categoryName;
            ClanId = clanId;
        }
    }
}
