// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateOnboardingStepParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateOnboardingStepRequest ToProto(in UpdateOnboardingStepParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateOnboardingStepRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.OnboardingStep.HasValue)
                proto.OnboardingStep = p.OnboardingStep.Value;
            return proto;
        }
    }
}
