// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateCategoryOrderParams
    {
        public readonly long? ClanId;
        public readonly IEnumerable<CategoryOrderUpdateParams>? Categories;
        public UpdateCategoryOrderParams(long? clanId = null, IEnumerable<CategoryOrderUpdateParams>? categories = null)
        {
            ClanId = clanId;
            Categories = categories;
        }
    }
}
