// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateOnboardingParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateOnboardingRequest ToProto(in UpdateOnboardingParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateOnboardingRequest();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.TaskType.HasValue)
                proto.TaskType = p.TaskType.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Title is not null)
                proto.Title = p.Title;
            if (p.Content is not null)
                proto.Content = p.Content;
            if (p.ImageUrl is not null)
                proto.ImageUrl = p.ImageUrl;
            if (p.Answers is not null)
            {
                foreach (var item in p.Answers)
                    proto.Answers.Add(OnboardingAnswerParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
