// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateUsersParams
    {
        public readonly string? DisplayName;
        public readonly string? AvatarUrl;
        public UpdateUsersParams(string? displayName = null, string? avatarUrl = null)
        {
            DisplayName = displayName;
            AvatarUrl = avatarUrl;
        }
    }
}
