// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateAppParams
    {
        public readonly long? Id;
        public readonly string? Appname;
        public readonly string? Metadata;
        public readonly string? Applogo;
        public readonly string? Token;
        public readonly string? About;
        public readonly string? AppUrl;
        public readonly string? IsShadow;
        public UpdateAppParams(long? id = null, string? appname = null, string? metadata = null, string? applogo = null, string? token = null, string? about = null, string? appUrl = null, string? isShadow = null)
        {
            Id = id;
            Appname = appname;
            Metadata = metadata;
            Applogo = applogo;
            Token = token;
            About = about;
            AppUrl = appUrl;
            IsShadow = isShadow;
        }
    }
}
