// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateRoleChannelParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateRoleChannelRequest ToProto(in UpdateRoleChannelParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateRoleChannelRequest();
            if (p.RoleId.HasValue)
                proto.RoleId = p.RoleId.Value;
            if (p.PermissionUpdate is not null)
            {
                foreach (var item in p.PermissionUpdate)
                    proto.PermissionUpdate.Add(PermissionUpdateParamsMapper.ToProto(item));
            }
            if (p.MaxPermissionId.HasValue)
                proto.MaxPermissionId = p.MaxPermissionId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.UserId.HasValue)
                proto.UserId = p.UserId.Value;
            if (p.RoleLabel is not null)
                proto.RoleLabel = p.RoleLabel;
            return proto;
        }
    }
}
