// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateAppParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateAppRequest ToProto(in UpdateAppParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateAppRequest();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.Appname is not null)
                proto.Appname = p.Appname;
            if (p.Metadata is not null)
                proto.Metadata = p.Metadata;
            if (p.Applogo is not null)
                proto.Applogo = p.Applogo;
            if (p.Token is not null)
                proto.Token = p.Token;
            if (p.About is not null)
                proto.About = p.About;
            if (p.AppUrl is not null)
                proto.AppUrl = p.AppUrl;
            if (p.IsShadow is not null)
                proto.IsShadow = p.IsShadow;
            return proto;
        }
    }
}
