// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateClanDescParams
    {
        public readonly long? ClanId;
        public readonly string? ClanName;
        public readonly string? Logo;
        public readonly string? Banner;
        public readonly int? Status;
        public readonly bool? IsOnboarding;
        public readonly long? WelcomeChannelId;
        public readonly string? OnboardingBanner;
        public readonly bool? IsCommunity;
        public readonly string? CommunityBanner;
        public readonly string? Description;
        public readonly string? About;
        public readonly string? ShortUrl;
        public readonly bool? PreventAnonymous;
        public UpdateClanDescParams(long? clanId = null, string? clanName = null, string? logo = null, string? banner = null, int? status = null, bool? isOnboarding = null, long? welcomeChannelId = null, string? onboardingBanner = null, bool? isCommunity = null, string? communityBanner = null, string? description = null, string? about = null, string? shortUrl = null, bool? preventAnonymous = null)
        {
            ClanId = clanId;
            ClanName = clanName;
            Logo = logo;
            Banner = banner;
            Status = status;
            IsOnboarding = isOnboarding;
            WelcomeChannelId = welcomeChannelId;
            OnboardingBanner = onboardingBanner;
            IsCommunity = isCommunity;
            CommunityBanner = communityBanner;
            Description = description;
            About = about;
            ShortUrl = shortUrl;
            PreventAnonymous = preventAnonymous;
        }
    }
}
