// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateClanProfileParams
    {
        public readonly long? ClanId;
        public readonly string? NickName;
        public readonly string? Avatar;
        public UpdateClanProfileParams(long? clanId = null, string? nickName = null, string? avatar = null)
        {
            ClanId = clanId;
            NickName = nickName;
            Avatar = avatar;
        }
    }
}
