// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateAccountParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateAccountRequest ToProto(in UpdateAccountParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateAccountRequest();
            if (p.DisplayName is not null)
                proto.DisplayName = p.DisplayName;
            if (p.AvatarUrl is not null)
                proto.AvatarUrl = p.AvatarUrl;
            if (p.LangTag is not null)
                proto.LangTag = p.LangTag;
            if (p.Location is not null)
                proto.Location = p.Location;
            if (p.Timezone is not null)
                proto.Timezone = p.Timezone;
            if (p.AboutMe is not null)
                proto.AboutMe = p.AboutMe;
            if (p.DobSeconds.HasValue)
                proto.DobSeconds = p.DobSeconds.Value;
            if (p.Logo is not null)
                proto.Logo = p.Logo;
            if (p.SplashScreen is not null)
                proto.SplashScreen = p.SplashScreen;
            if (p.EncryptPrivateKey is not null)
                proto.EncryptPrivateKey = p.EncryptPrivateKey;
            if (p.Email is not null)
                proto.Email = p.Email;
            return proto;
        }
    }
}
