// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateChannelTimelineParams
    {
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public readonly long? Id;
        public readonly uint? StartTimeSeconds;
        public readonly string? Title;
        public readonly string? Description;
        public readonly string? Location;
        public readonly int? Type;
        public readonly IEnumerable<ChannelTimelineAttachmentParams>? Attachments;
        public UpdateChannelTimelineParams(long? clanId = null, long? channelId = null, long? id = null, uint? startTimeSeconds = null, string? title = null, string? description = null, string? location = null, int? type = null, IEnumerable<ChannelTimelineAttachmentParams>? attachments = null)
        {
            ClanId = clanId;
            ChannelId = channelId;
            Id = id;
            StartTimeSeconds = startTimeSeconds;
            Title = title;
            Description = description;
            Location = location;
            Type = type;
            Attachments = attachments;
        }
    }
}
