// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateAccountParams
    {
        public readonly string? DisplayName;
        public readonly string? AvatarUrl;
        public readonly string? LangTag;
        public readonly string? Location;
        public readonly string? Timezone;
        public readonly string? AboutMe;
        public readonly uint? DobSeconds;
        public readonly string? Logo;
        public readonly string? SplashScreen;
        public readonly string? EncryptPrivateKey;
        public readonly string? Email;
        public UpdateAccountParams(string? displayName = null, string? avatarUrl = null, string? langTag = null, string? location = null, string? timezone = null, string? aboutMe = null, uint? dobSeconds = null, string? logo = null, string? splashScreen = null, string? encryptPrivateKey = null, string? email = null)
        {
            DisplayName = displayName;
            AvatarUrl = avatarUrl;
            LangTag = langTag;
            Location = location;
            Timezone = timezone;
            AboutMe = aboutMe;
            DobSeconds = dobSeconds;
            Logo = logo;
            SplashScreen = splashScreen;
            EncryptPrivateKey = encryptPrivateKey;
            Email = email;
        }
    }
}
