// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateCategoryOrderParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateCategoryOrderRequest ToProto(in UpdateCategoryOrderParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateCategoryOrderRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.Categories is not null)
            {
                foreach (var item in p.Categories)
                    proto.Categories.Add(CategoryOrderUpdateParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
