// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateUsersParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateUsersRequest ToProto(in UpdateUsersParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateUsersRequest();
            if (p.DisplayName is not null)
                proto.DisplayName = p.DisplayName;
            if (p.AvatarUrl is not null)
                proto.AvatarUrl = p.AvatarUrl;
            return proto;
        }
    }
}
