// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateRoleParams
    {
        public readonly long? RoleId;
        public readonly string? Title;
        public readonly string? Color;
        public readonly string? RoleIcon;
        public readonly string? Description;
        public readonly int? DisplayOnline;
        public readonly int? AllowMention;
        public readonly IEnumerable<long?>? AddUserIds;
        public readonly IEnumerable<long?>? ActivePermissionIds;
        public readonly IEnumerable<long?>? RemoveUserIds;
        public readonly IEnumerable<long?>? RemovePermissionIds;
        public readonly long? ClanId;
        public readonly long? MaxPermissionId;
        public UpdateRoleParams(long? roleId = null, string? title = null, string? color = null, string? roleIcon = null, string? description = null, int? displayOnline = null, int? allowMention = null, IEnumerable<long?>? addUserIds = null, IEnumerable<long?>? activePermissionIds = null, IEnumerable<long?>? removeUserIds = null, IEnumerable<long?>? removePermissionIds = null, long? clanId = null, long? maxPermissionId = null)
        {
            RoleId = roleId;
            Title = title;
            Color = color;
            RoleIcon = roleIcon;
            Description = description;
            DisplayOnline = displayOnline;
            AllowMention = allowMention;
            AddUserIds = addUserIds;
            ActivePermissionIds = activePermissionIds;
            RemoveUserIds = removeUserIds;
            RemovePermissionIds = removePermissionIds;
            ClanId = clanId;
            MaxPermissionId = maxPermissionId;
        }
    }
}
