// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateEventRequest ToProto(in UpdateEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateEventRequest();
            if (p.Title is not null)
                proto.Title = p.Title;
            if (p.Logo is not null)
                proto.Logo = p.Logo;
            if (p.Description is not null)
                proto.Description = p.Description;
            if (p.EventId.HasValue)
                proto.EventId = p.EventId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Address is not null)
                proto.Address = p.Address;
            if (p.StartTimeSeconds.HasValue)
                proto.StartTimeSeconds = p.StartTimeSeconds.Value;
            if (p.EndTimeSeconds.HasValue)
                proto.EndTimeSeconds = p.EndTimeSeconds.Value;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.CreatorId.HasValue)
                proto.CreatorId = p.CreatorId.Value;
            if (p.ChannelVoiceId.HasValue)
                proto.ChannelVoiceId = p.ChannelVoiceId.Value;
            if (p.ChannelIdOld.HasValue)
                proto.ChannelIdOld = p.ChannelIdOld.Value;
            if (p.RepeatType.HasValue)
                proto.RepeatType = p.RepeatType.Value;
            return proto;
        }
    }
}
