// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateClanOrderParams
    {
        public readonly IEnumerable<ClanOrderParams>? ClansOrder;
        public UpdateClanOrderParams(IEnumerable<ClanOrderParams>? clansOrder = null)
        {
            ClansOrder = clansOrder;
        }
    }
}
