// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateClanOrderParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateClanOrderRequest ToProto(in UpdateClanOrderParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateClanOrderRequest();
            if (p.ClansOrder is not null)
            {
                foreach (var item in p.ClansOrder)
                    proto.ClansOrder.Add(ClanOrderParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
