// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateRoleChannelParams
    {
        public readonly long? RoleId;
        public readonly IEnumerable<PermissionUpdateParams>? PermissionUpdate;
        public readonly long? MaxPermissionId;
        public readonly long? ChannelId;
        public readonly long? UserId;
        public readonly string? RoleLabel;
        public UpdateRoleChannelParams(long? roleId = null, IEnumerable<PermissionUpdateParams>? permissionUpdate = null, long? maxPermissionId = null, long? channelId = null, long? userId = null, string? roleLabel = null)
        {
            RoleId = roleId;
            PermissionUpdate = permissionUpdate;
            MaxPermissionId = maxPermissionId;
            ChannelId = channelId;
            UserId = userId;
            RoleLabel = roleLabel;
        }
    }
}
