// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateOnboardingParams
    {
        public readonly long? Id;
        public readonly long? ClanId;
        public readonly int? TaskType;
        public readonly long? ChannelId;
        public readonly string? Title;
        public readonly string? Content;
        public readonly string? ImageUrl;
        public readonly IEnumerable<OnboardingAnswerParams>? Answers;
        public UpdateOnboardingParams(long? id = null, long? clanId = null, int? taskType = null, long? channelId = null, string? title = null, string? content = null, string? imageUrl = null, IEnumerable<OnboardingAnswerParams>? answers = null)
        {
            Id = id;
            ClanId = clanId;
            TaskType = taskType;
            ChannelId = channelId;
            Title = title;
            Content = content;
            ImageUrl = imageUrl;
            Answers = answers;
        }
    }
}
