// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateChannelDescParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateChannelDescRequest ToProto(in UpdateChannelDescParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateChannelDescRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.ChannelLabel is not null)
                proto.ChannelLabel = p.ChannelLabel;
            if (p.CategoryId.HasValue)
                proto.CategoryId = p.CategoryId.Value;
            if (p.AppId.HasValue)
                proto.AppId = p.AppId.Value;
            if (p.Topic is not null)
                proto.Topic = p.Topic;
            if (p.AgeRestricted.HasValue)
                proto.AgeRestricted = p.AgeRestricted.Value;
            if (p.E2ee.HasValue)
                proto.E2Ee = p.E2ee.Value;
            if (p.ChannelAvatar is not null)
                proto.ChannelAvatar = p.ChannelAvatar;
            return proto;
        }
    }
}
