// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateUsernameParams
    {
        public readonly string? Username;
        public readonly string? DisplayName;
        public UpdateUsernameParams(string? username = null, string? displayName = null)
        {
            Username = username;
            DisplayName = displayName;
        }
    }
}
