// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UpdateClanProfileParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UpdateClanProfileRequest ToProto(in UpdateClanProfileParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UpdateClanProfileRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.NickName is not null)
                proto.NickName = p.NickName;
            if (p.Avatar is not null)
                proto.Avatar = p.Avatar;
            return proto;
        }
    }
}
