// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UploadBatchAttachmentParams
    {
        public readonly IEnumerable<UploadAttachmentParams>? UploadFiles;
        public UploadBatchAttachmentParams(IEnumerable<UploadAttachmentParams>? uploadFiles = null)
        {
            UploadFiles = uploadFiles;
        }
    }
}
