// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UploadAttachmentParams
    {
        public readonly string? Filename;
        public readonly string? Filetype;
        public readonly int? Size;
        public readonly int? Width;
        public readonly int? Height;
        public readonly int? PartCount;
        public UploadAttachmentParams(string? filename = null, string? filetype = null, int? size = null, int? width = null, int? height = null, int? partCount = null)
        {
            Filename = filename;
            Filetype = filetype;
            Size = size;
            Width = width;
            Height = height;
            PartCount = partCount;
        }
    }
}
