// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UploadAttachmentParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UploadAttachmentRequest ToProto(in UploadAttachmentParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UploadAttachmentRequest();
            if (p.Filename is not null)
                proto.Filename = p.Filename;
            if (p.Filetype is not null)
                proto.Filetype = p.Filetype;
            if (p.Size.HasValue)
                proto.Size = p.Size.Value;
            if (p.Width.HasValue)
                proto.Width = p.Width.Value;
            if (p.Height.HasValue)
                proto.Height = p.Height.Value;
            if (p.PartCount.HasValue)
                proto.PartCount = p.PartCount.Value;
            return proto;
        }
    }
}
