// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UploadBatchAttachmentParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UploadBatchAttachmentRequest ToProto(in UploadBatchAttachmentParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UploadBatchAttachmentRequest();
            if (p.UploadFiles is not null)
            {
                foreach (var item in p.UploadFiles)
                    proto.UploadFiles.Add(UploadAttachmentParamsMapper.ToProto(item));
            }
            return proto;
        }
    }
}
