// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UserEventParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UserEventRequest ToProto(in UserEventParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UserEventRequest();
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            if (p.EventId.HasValue)
                proto.EventId = p.EventId.Value;
            return proto;
        }
    }
}
