// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UserParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.User ToProto(in UserParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.User();
            if (p.Id.HasValue)
                proto.Id = p.Id.Value;
            if (p.Username is not null)
                proto.Username = p.Username;
            if (p.DisplayName is not null)
                proto.DisplayName = p.DisplayName;
            if (p.AvatarUrl is not null)
                proto.AvatarUrl = p.AvatarUrl;
            if (p.LangTag is not null)
                proto.LangTag = p.LangTag;
            if (p.Location is not null)
                proto.Location = p.Location;
            if (p.Timezone is not null)
                proto.Timezone = p.Timezone;
            if (p.UserStatus is not null)
                proto.UserStatus = p.UserStatus;
            if (p.Online.HasValue)
                proto.Online = p.Online.Value;
            if (p.PhoneNumber is not null)
                proto.PhoneNumber = p.PhoneNumber;
            if (p.EdgeCount.HasValue)
                proto.EdgeCount = p.EdgeCount.Value;
            if (p.CreateTimeSeconds.HasValue)
                proto.CreateTimeSeconds = p.CreateTimeSeconds.Value;
            if (p.UpdateTimeSeconds.HasValue)
                proto.UpdateTimeSeconds = p.UpdateTimeSeconds.Value;
            if (p.AboutMe is not null)
                proto.AboutMe = p.AboutMe;
            if (p.JoinTimeSeconds.HasValue)
                proto.JoinTimeSeconds = p.JoinTimeSeconds.Value;
            if (p.IsMobile.HasValue)
                proto.IsMobile = p.IsMobile.Value;
            if (p.DobSeconds.HasValue)
                proto.DobSeconds = p.DobSeconds.Value;
            if (p.MezonId is not null)
                proto.MezonId = p.MezonId;
            if (p.ListNickNames is not null)
                proto.ListNickNames.AddRange(p.ListNickNames);
            if (p.Status is not null)
                proto.Status = p.Status;
            return proto;
        }
    }
}
