// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserParams
    {
        public readonly long? Id;
        public readonly string? Username;
        public readonly string? DisplayName;
        public readonly string? AvatarUrl;
        public readonly string? LangTag;
        public readonly string? Location;
        public readonly string? Timezone;
        public readonly string? UserStatus;
        public readonly bool? Online;
        public readonly string? PhoneNumber;
        public readonly int? EdgeCount;
        public readonly uint? CreateTimeSeconds;
        public readonly uint? UpdateTimeSeconds;
        public readonly string? AboutMe;
        public readonly uint? JoinTimeSeconds;
        public readonly bool? IsMobile;
        public readonly uint? DobSeconds;
        public readonly string? MezonId;
        public readonly IEnumerable<string?>? ListNickNames;
        public readonly string? Status;
        public UserParams(long? id = null, string? username = null, string? displayName = null, string? avatarUrl = null, string? langTag = null, string? location = null, string? timezone = null, string? userStatus = null, bool? online = null, string? phoneNumber = null, int? edgeCount = null, uint? createTimeSeconds = null, uint? updateTimeSeconds = null, string? aboutMe = null, uint? joinTimeSeconds = null, bool? isMobile = null, uint? dobSeconds = null, string? mezonId = null, IEnumerable<string?>? listNickNames = null, string? status = null)
        {
            Id = id;
            Username = username;
            DisplayName = displayName;
            AvatarUrl = avatarUrl;
            LangTag = langTag;
            Location = location;
            Timezone = timezone;
            UserStatus = userStatus;
            Online = online;
            PhoneNumber = phoneNumber;
            EdgeCount = edgeCount;
            CreateTimeSeconds = createTimeSeconds;
            UpdateTimeSeconds = updateTimeSeconds;
            AboutMe = aboutMe;
            JoinTimeSeconds = joinTimeSeconds;
            IsMobile = isMobile;
            DobSeconds = dobSeconds;
            MezonId = mezonId;
            ListNickNames = listNickNames;
            Status = status;
        }
    }
}
