// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class UserStatusUpdateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.UserStatusUpdate ToProto(in UserStatusUpdateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.UserStatusUpdate();
            if (p.Status is not null)
                proto.Status = p.Status;
            if (p.Minutes.HasValue)
                proto.Minutes = p.Minutes.Value;
            if (p.UntilTurnOn.HasValue)
                proto.UntilTurnOn = p.UntilTurnOn.Value;
            return proto;
        }
    }
}
