// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserStatusUpdateParams
    {
        public readonly string? Status;
        public readonly int? Minutes;
        public readonly bool? UntilTurnOn;
        public UserStatusUpdateParams(string? status = null, int? minutes = null, bool? untilTurnOn = null)
        {
            Status = status;
            Minutes = minutes;
            UntilTurnOn = untilTurnOn;
        }
    }
}
