// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserEventParams
    {
        public readonly long? ClanId;
        public readonly long? EventId;
        public UserEventParams(long? clanId = null, long? eventId = null)
        {
            ClanId = clanId;
            EventId = eventId;
        }
    }
}
