// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceReactionSendParams
    {
        public readonly IEnumerable<string?>? Emojis;
        public readonly long? ChannelId;
        public readonly long? SenderId;
        public readonly int? MediaType;
        public VoiceReactionSendParams(IEnumerable<string?>? emojis = null, long? channelId = null, long? senderId = null, int? mediaType = null)
        {
            Emojis = emojis;
            ChannelId = channelId;
            SenderId = senderId;
            MediaType = mediaType;
        }
    }
}
