// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class VoiceReactionSendParamsMapper
    {
        internal static global::Mezon.Net.Internal.Realtime.VoiceReactionSend ToProto(in VoiceReactionSendParams p)
        {
            var proto = new global::Mezon.Net.Internal.Realtime.VoiceReactionSend();
            if (p.Emojis is not null)
                proto.Emojis.AddRange(p.Emojis);
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.SenderId.HasValue)
                proto.SenderId = p.SenderId.Value;
            if (p.MediaType.HasValue)
                proto.MediaType = p.MediaType.Value;
            return proto;
        }
    }
}
