// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class VotePollParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.VotePollRequest ToProto(in VotePollParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.VotePollRequest();
            if (p.PollId.HasValue)
                proto.PollId = p.PollId.Value;
            if (p.MessageId.HasValue)
                proto.MessageId = p.MessageId.Value;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.AnswerIndices is not null)
            {
                foreach (var item in p.AnswerIndices)
                    if (item.HasValue) proto.AnswerIndices.Add(item.Value);
            }
            return proto;
        }
    }
}
