// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VotePollParams
    {
        public readonly long? PollId;
        public readonly long? MessageId;
        public readonly long? ChannelId;
        public readonly IEnumerable<int?>? AnswerIndices;
        public VotePollParams(long? pollId = null, long? messageId = null, long? channelId = null, IEnumerable<int?>? answerIndices = null)
        {
            PollId = pollId;
            MessageId = messageId;
            ChannelId = channelId;
            AnswerIndices = answerIndices;
        }
    }
}
