// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct WebhookUpdateRequestByIdParams
    {
        public readonly long? Id;
        public readonly string? WebhookName;
        public readonly long? ChannelIdUpdate;
        public readonly string? Avatar;
        public readonly long? ChannelId;
        public readonly long? ClanId;
        public WebhookUpdateRequestByIdParams(long? id = null, string? webhookName = null, long? channelIdUpdate = null, string? avatar = null, long? channelId = null, long? clanId = null)
        {
            Id = id;
            WebhookName = webhookName;
            ChannelIdUpdate = channelIdUpdate;
            Avatar = avatar;
            ChannelId = channelId;
            ClanId = clanId;
        }
    }
}
