// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct WebhookDeleteRequestByIdParams
    {
        public readonly long? Id;
        public readonly long? ClanId;
        public readonly long? ChannelId;
        public WebhookDeleteRequestByIdParams(long? id = null, long? clanId = null, long? channelId = null)
        {
            Id = id;
            ClanId = clanId;
            ChannelId = channelId;
        }
    }
}
