// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct WebhookCreateParams
    {
        public readonly string? WebhookName;
        public readonly long? ChannelId;
        public readonly string? Avatar;
        public readonly long? ClanId;
        public WebhookCreateParams(string? webhookName = null, long? channelId = null, string? avatar = null, long? clanId = null)
        {
            WebhookName = webhookName;
            ChannelId = channelId;
            Avatar = avatar;
            ClanId = clanId;
        }
    }
}
