// <auto-generated />
#nullable enable
using System.Linq;
using Mezon.Net.Internal.Api;
using Mezon.Net.Internal.Realtime;
using Mezon.Net.Models;

namespace Mezon.Net.Client.Models.Internal
{
    internal static class WebhookCreateParamsMapper
    {
        internal static global::Mezon.Net.Internal.Api.WebhookCreateRequest ToProto(in WebhookCreateParams p)
        {
            var proto = new global::Mezon.Net.Internal.Api.WebhookCreateRequest();
            if (p.WebhookName is not null)
                proto.WebhookName = p.WebhookName;
            if (p.ChannelId.HasValue)
                proto.ChannelId = p.ChannelId.Value;
            if (p.Avatar is not null)
                proto.Avatar = p.Avatar;
            if (p.ClanId.HasValue)
                proto.ClanId = p.ClanId.Value;
            return proto;
        }
    }
}
