// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct WebrtcSignalingFwdParams
    {
        public readonly long? ReceiverId;
        public readonly int? DataType;
        public readonly string? JsonData;
        public readonly long? ChannelId;
        public readonly long? CallerId;
        public WebrtcSignalingFwdParams(long? receiverId = null, int? dataType = null, string? jsonData = null, long? channelId = null, long? callerId = null)
        {
            ReceiverId = receiverId;
            DataType = dataType;
            JsonData = jsonData;
            ChannelId = channelId;
            CallerId = callerId;
        }
    }
}
