using System;
using System.Collections.Generic;
#if NET8_0_OR_GREATER
using System.Collections.Frozen;
#endif

namespace Mezon.Net.Core.Protocol
{
    public static class ApiNameIndexMap
    {
        private static readonly Dictionary<string, int> Entries = new Dictionary<string, int>
        {
            ["ListChannelDescs"] = 0,
            ["GetAccount"] = 1,
            ["ListClanDescs"] = 2,
            ["ListClanUsers"] = 3,
            ["ListRoles"] = 4,
            ["ListEvents"] = 5,
            ["GetRoleOfUserInTheClan"] = 6,
            ["GetListPermission"] = 7,
            ["ListUserPermissionInChannel"] = 8,
            ["GetNotificationClan"] = 9,
            ["ListMutedChannel"] = 10,
            ["ListStreamingChannelUsers"] = 11,
            ["ListQuickMenuAccess"] = 12,
            ["GetNotificationChannel"] = 13,
            ["ListFriends"] = 14,
            ["EmojiRecentList"] = 15,
            ["GetListEmojisByUserId"] = 16,
            ["ListClanBadgeCount"] = 17,
            ["ListChannelBadgeCount"] = 18,
            ["ListLogedDevice"] = 19,
            ["ListClanUsersStatus"] = 20,
            ["ListChannelApps"] = 21,
            ["GetListFavoriteChannel"] = 22,
            ["ListCategoryDescs"] = 23,
            ["ListOnboarding"] = 24,
            ["GetListStickersByUserId"] = 25,
            ["GetSystemMessageByClanId"] = 26,
            ["GetPinMessagesList"] = 27,
            ["GetChannelCanvasList"] = 28,
            ["ListChannelTimeline"] = 29,
            ["ListChannelMessages"] = 30,
            ["ListActivity"] = 31,
            ["ListChannelByUserId"] = 32,
            ["ListUserClansByUserId"] = 33,
            ["GetUserProfileOnClan"] = 34,
            ["RegistFCMDeviceToken"] = 35,
            ["IsBanned"] = 36,
            ["ListThreadDescs"] = 37,
            ["ListArchivedChannelDescs"] = 38,
            ["ListChannelDetail"] = 39,
            ["GetChannelCategoryNotiSettingsList"] = 40,
            ["ListRoleUsers"] = 41,
            ["ListChannelUsers"] = 42,
            ["ListChannelAttachment"] = 43,
            ["ListChannelVoiceUsers"] = 44,
            ["ListUserOnline"] = 45,
            ["ListNotifications"] = 46,
            ["ListChannelUsersUC"] = 47,
            ["ListWebhookByChannelId"] = 48,
            ["GetPermissionByRoleIdChannelId"] = 49,
            ["ListChannelSetting"] = 50,
            ["ListApps"] = 51,
            ["GetApp"] = 52,
            ["ListForSaleItems"] = 53,
            ["ListClanWebhook"] = 54,
            ["GetUserStatus"] = 55,
            ["ListSdTopic"] = 56,
            ["AddFriends"] = 57,
            ["AddChannelUsers"] = 58,
            ["RegistrationEmail"] = 59,
            ["BlockFriends"] = 60,
            ["UnblockFriends"] = 61,
            ["UploadAttachmentFile"] = 62,
            ["UploadOauthFile"] = 63,
            ["AddRolesChannelDesc"] = 64,
            ["CreateCategoryDesc"] = 65,
            ["CreateChannelDesc"] = 66,
            ["CreateRole"] = 67,
            ["CreateEvent"] = 68,
            ["DeleteRole"] = 69,
            ["DeleteEvent"] = 70,
            ["DeleteRoleChannelDesc"] = 71,
            ["DeleteChannelDesc"] = 72,
            ["CloseDMByChannelId"] = 73,
            ["OpenDMByChannelId"] = 74,
            ["DeleteAccount"] = 75,
            ["DeleteFriends"] = 76,
            ["DeleteCategoryDesc"] = 77,
            ["DeleteNotifications"] = 78,
            ["DeleteClanDesc"] = 79,
            ["UpdateUser"] = 80,
            ["UpdateUserProfileByClan"] = 81,
            ["UpdateClanOrder"] = 82,
            ["RemoveChannelUsers"] = 83,
            ["LeaveThread"] = 84,
            ["ArchiveChannel"] = 85,
            ["LinkSMS"] = 86,
            ["ConfirmLinkMezonOTP"] = 87,
            ["LinkEmail"] = 88,
            ["CreateClanDesc"] = 89,
            ["RemoveClanUsers"] = 90,
            ["BanClanUsers"] = 91,
            ["CreateLinkInviteUser"] = 92,
            ["InviteUser"] = 93,
            ["SetRoleChannelPermission"] = 94,
            ["SetNotificationChannelSetting"] = 95,
            ["SetMuteChannel"] = 96,
            ["SetMuteCategory"] = 97,
            ["SetNotificationClanSetting"] = 98,
            ["SetNotificationCategorySetting"] = 99,
            ["DeleteNotificationCategorySetting"] = 100,
            ["DeleteNotificationChannel"] = 101,
            ["CreatePinMessage"] = 102,
            ["CreateMessage2Inbox"] = 103,
            ["UnlinkMezon"] = 104,
            ["UnlinkEmail"] = 105,
            ["UpdateAccount"] = 106,
            ["UpdateUsername"] = 107,
            ["UpdateCategory"] = 108,
            ["UpdateCategoryOrder"] = 109,
            ["UpdateRoleOrder"] = 110,
            ["UpdateClanDesc"] = 111,
            ["UpdateChannelDesc"] = 112,
            ["UpdateChannelPrivate"] = 113,
            ["UpdateRole"] = 114,
            ["UpdateEvent"] = 115,
            ["SearchMessage"] = 116,
            ["CreateClanEmoji"] = 117,
            ["DeleteByIdClanEmoji"] = 118,
            ["UpdateClanEmojiById"] = 119,
            ["GenerateWebhook"] = 120,
            ["HandleWebhook"] = 121,
            ["UpdateWebhookById"] = 122,
            ["DeleteWebhookById"] = 123,
            ["AddClanSticker"] = 124,
            ["UpdateClanStickerById"] = 125,
            ["DeleteClanStickerById"] = 126,
            ["ChangeChannelCategory"] = 127,
            ["CheckDuplicateName"] = 128,
            ["AddApp"] = 129,
            ["DeleteApp"] = 130,
            ["UpdateApp"] = 131,
            ["AddAppToClan"] = 132,
            ["CreateSystemMessage"] = 133,
            ["UpdateSystemMessage"] = 134,
            ["DeleteSystemMessage"] = 135,
            ["StreamingServerCallback"] = 136,
            ["EditChannelCanvases"] = 137,
            ["GetChannelCanvasDetail"] = 138,
            ["DeleteChannelCanvas"] = 139,
            ["AddChannelFavorite"] = 140,
            ["RemoveChannelFavorite"] = 141,
            ["CreateActiviy"] = 142,
            ["GetPubKeys"] = 143,
            ["PushPubKey"] = 144,
            ["GetChanEncryptionMethod"] = 145,
            ["SetChanEncryptionMethod"] = 146,
            ["GetKeyServer"] = 147,
            ["ListAuditLog"] = 148,
            ["GetOnboardingDetail"] = 149,
            ["CreateOnboarding"] = 150,
            ["UpdateOnboarding"] = 151,
            ["DeleteOnboarding"] = 152,
            ["ListOnboardingStep"] = 153,
            ["UpdateOnboardingStep"] = 154,
            ["GenerateClanWebhook"] = 155,
            ["UpdateClanWebhookById"] = 156,
            ["DeleteClanWebhookById"] = 157,
            ["HandleClanWebhook"] = 158,
            ["UpdateUserStatus"] = 159,
            ["UpdateUserCustomStatus"] = 160,
            ["GetTopicDetail"] = 161,
            ["CreateSdTopic"] = 162,
            ["DeleteSdTopic"] = 163,
            ["CreateExternalMezonMeet"] = 164,
            ["GenerateMeetToken"] = 165,
            ["RemoveParticipantMezonMeet"] = 166,
            ["MuteParticipantMezonMeet"] = 167,
            ["CreateRoomChannelApps"] = 168,
            ["GetMezonOauthClient"] = 169,
            ["DeleteMezonOauthClient"] = 170,
            ["UpdateMezonOauthClient"] = 171,
            ["SearchThread"] = 172,
            ["GenerateHashChannelApps"] = 173,
            ["DeleteUserEvent"] = 174,
            ["AddUserEvent"] = 175,
            ["DeleteQuickMenuAccess"] = 176,
            ["AddQuickMenuAccess"] = 177,
            ["UpdateQuickMenuAccess"] = 178,
            ["TransferOwnership"] = 179,
            ["SendChannelMessage"] = 180,
            ["UpdateChannelMessage"] = 181,
            ["DeleteChannelMessage"] = 182,
            ["ReportMessageAbuse"] = 183,
            ["MessageButtonClick"] = 184,
            ["DropdownBoxSelected"] = 185,
            ["ActiveArchivedThread"] = 186,
            ["UpdateChannelTimeline"] = 187,
            ["AddAgentToChannel"] = 188,
            ["DisconnectAgent"] = 189,
            ["CreateChannelTimeline"] = 190,
            ["DetailChannelTimeline"] = 191,
            ["CreatePoll"] = 192,
            ["VotePoll"] = 193,
            ["ClosePoll"] = 194,
            ["GetPoll"] = 195,
            ["ReactChannelMessage"] = 196,
            ["MultipartUploadAttachmentFileStart"] = 197,
            ["MultipartUploadAttachmentFileFinish"] = 198,
            ["SessionRefresh"] = 199,
            ["SessionLogout"] = 200,
            ["Healthcheck"] = 201,
            ["UnbanClanUsers"] = 202,
            ["ListBannedUsers"] = 203,
            ["GetNotificationCategory"] = 204,
            ["ListRolePermissions"] = 205,
            ["IsFollower"] = 206,
            ["DeletePinMessage"] = 207,
            ["MarkAsRead"] = 208,
            ["UploadBatchAttachmentFile"] = 209,
        };

#if NET8_0_OR_GREATER
        public static readonly FrozenDictionary<string, int> NameToIndex = Entries.ToFrozenDictionary();
#else
        public static readonly IReadOnlyDictionary<string, int> NameToIndex = Entries;
#endif

        public static bool TryGetIndex(string apiName, out int index)
        {
            if (NameToIndex.TryGetValue(apiName, out index))
            {
                return true;
            }

            // Protocol typo alias: grpc rpc is CreateActiviy but clients may use correct spelling.
            if (string.Equals(apiName, "CreateActivity", StringComparison.Ordinal))
            {
                return NameToIndex.TryGetValue("CreateActiviy", out index);
            }

            index = default;
            return false;
        }
    }
}
