// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AccountData
    {
        private readonly global::Mezon.Net.Internal.Api.Account _proto;
        internal AccountData(global::Mezon.Net.Internal.Api.Account proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.Account Proto => _proto;

        public UserData User => new UserData(_proto.User);
        public string Email => _proto.Email;
        public string QrCode => _proto.QrCode;
        public uint VerifyTimeSeconds => _proto.VerifyTimeSeconds;
        public uint DisableTimeSeconds => _proto.DisableTimeSeconds;
        public string Logo => _proto.Logo;
        public string SplashScreen => _proto.SplashScreen;
        public string EncryptPrivateKey => _proto.EncryptPrivateKey;
        public bool PasswordSetted => _proto.PasswordSetted;
    }
}
