// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AddClanUserEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.AddClanUserEvent _proto;
        internal AddClanUserEventResponse(global::Mezon.Net.Internal.Realtime.AddClanUserEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.AddClanUserEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public UserProfileRedisResponse User => new UserProfileRedisResponse(_proto.User);
        public string Invitor => _proto.Invitor;
    }
}
