// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AddFavoriteChannelResponse
    {
        private readonly global::Mezon.Net.Internal.Api.AddFavoriteChannelResponse _proto;
        internal AddFavoriteChannelResponse(global::Mezon.Net.Internal.Api.AddFavoriteChannelResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AddFavoriteChannelResponse Proto => _proto;

        public long ChannelId => _proto.ChannelId;
    }
}
