// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AddFriendsResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.AddFriendsResponse _proto;
        internal AddFriendsResponseData(global::Mezon.Net.Internal.Api.AddFriendsResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AddFriendsResponse Proto => _proto;

        public ProtoListView<long> Ids => ProtoListView<long>.FromRepeated(_proto.Ids);
        public ProtoListView<string> Usernames => ProtoListView<string>.FromRepeated(_proto.Usernames);
    }
}
