// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AllUserClansData
    {
        private readonly global::Mezon.Net.Internal.Api.AllUserClans _proto;
        internal AllUserClansData(global::Mezon.Net.Internal.Api.AllUserClans proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AllUserClans Proto => _proto;

        public ProtoListView<UserData> Users => ProtoListView<UserData>.FromRepeated(_proto.Users, x => new UserData(x));
    }
}
