// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AllUsersAddChannelResponse
    {
        private readonly global::Mezon.Net.Internal.Api.AllUsersAddChannelResponse _proto;
        internal AllUsersAddChannelResponse(global::Mezon.Net.Internal.Api.AllUsersAddChannelResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AllUsersAddChannelResponse Proto => _proto;

        public long ChannelId => _proto.ChannelId;
        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
        public int Limit => _proto.Limit;
        public ProtoListView<string> Usernames => ProtoListView<string>.FromRepeated(_proto.Usernames);
        public ProtoListView<string> DisplayNames => ProtoListView<string>.FromRepeated(_proto.DisplayNames);
        public ProtoListView<string> Avatars => ProtoListView<string>.FromRepeated(_proto.Avatars);
    }
}
