// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AllUserClansResponse
    {
        private readonly global::Mezon.Net.Internal.Api.AllUserClans _proto;
        internal AllUserClansResponse(global::Mezon.Net.Internal.Api.AllUserClans proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AllUserClans Proto => _proto;

        public ProtoListView<UserResponse> Users => ProtoListView<UserResponse>.FromRepeated(_proto.Users, x => new UserResponse(x));
    }
}
