// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ApiRequestEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ApiRequestEvent _proto;
        internal ApiRequestEventData(global::Mezon.Net.Internal.Realtime.ApiRequestEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ApiRequestEvent Proto => _proto;

        public string ApiName => _proto.ApiName;
        public byte[] Body => _proto.Body.ToByteArray();
    }
}
