// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AppListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.AppList _proto;
        internal AppListResponse(global::Mezon.Net.Internal.Api.AppList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AppList Proto => _proto;

        public ProtoListView<AppResponse> Apps => ProtoListView<AppResponse>.FromRepeated(_proto.Apps, x => new AppResponse(x));
        public int TotalCount => _proto.TotalCount;
        public string NextCursor => _proto.NextCursor;
    }
}
