// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AppListData
    {
        private readonly global::Mezon.Net.Internal.Api.AppList _proto;
        internal AppListData(global::Mezon.Net.Internal.Api.AppList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AppList Proto => _proto;

        public ProtoListView<AppData> Apps => ProtoListView<AppData>.FromRepeated(_proto.Apps, x => new AppData(x));
        public int TotalCount => _proto.TotalCount;
        public string NextCursor => _proto.NextCursor;
    }
}
