// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AppResponse
    {
        private readonly global::Mezon.Net.Internal.Api.App _proto;
        internal AppResponse(global::Mezon.Net.Internal.Api.App proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.App Proto => _proto;

        public long Id => _proto.Id;
        public string Appname => _proto.Appname;
        public long CreatorId => _proto.CreatorId;
        public string Applogo => _proto.Applogo;
        public bool IsShadow => _proto.IsShadow;
        public uint DisableTimeSeconds => _proto.DisableTimeSeconds;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public string Token => _proto.Token;
        public int Role => _proto.Role;
        public string About => _proto.About;
        public string AppUrl => _proto.AppUrl;
    }
}
