// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct AuditLogResponse
    {
        private readonly global::Mezon.Net.Internal.Api.AuditLog _proto;
        internal AuditLogResponse(global::Mezon.Net.Internal.Api.AuditLog proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.AuditLog Proto => _proto;

        public long Id => _proto.Id;
        public long UserId => _proto.UserId;
        public long ClanId => _proto.ClanId;
        public string ActionLog => _proto.ActionLog;
        public string EntityName => _proto.EntityName;
        public long EntityId => _proto.EntityId;
        public string Details => _proto.Details;
        public uint TimeLogSeconds => _proto.TimeLogSeconds;
        public long ChannelId => _proto.ChannelId;
        public string ChannelLabel => _proto.ChannelLabel;
    }
}
