// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct BannedUserListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.BannedUserList _proto;
        internal BannedUserListResponse(global::Mezon.Net.Internal.Api.BannedUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.BannedUserList Proto => _proto;

        public ProtoListView<BannedUserResponse> BannedUsers => ProtoListView<BannedUserResponse>.FromRepeated(_proto.BannedUsers, x => new BannedUserResponse(x));
    }
}
