// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct BannedUserData
    {
        private readonly global::Mezon.Net.Internal.Api.BannedUser _proto;
        internal BannedUserData(global::Mezon.Net.Internal.Api.BannedUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.BannedUser Proto => _proto;

        public long ChannelId => _proto.ChannelId;
        public long BannedId => _proto.BannedId;
        public long BannerId => _proto.BannerId;
        public int BanTime => _proto.BanTime;
        public string Reason => _proto.Reason;
    }
}
