// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct BannedUserListData
    {
        private readonly global::Mezon.Net.Internal.Api.BannedUserList _proto;
        internal BannedUserListData(global::Mezon.Net.Internal.Api.BannedUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.BannedUserList Proto => _proto;

        public ProtoListView<BannedUserData> BannedUsers => ProtoListView<BannedUserData>.FromRepeated(_proto.BannedUsers, x => new BannedUserData(x));
    }
}
