// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CategoryDescListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.CategoryDescList _proto;
        internal CategoryDescListResponse(global::Mezon.Net.Internal.Api.CategoryDescList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.CategoryDescList Proto => _proto;

        public ProtoListView<CategoryDescResponse> Categorydesc => ProtoListView<CategoryDescResponse>.FromRepeated(_proto.Categorydesc, x => new CategoryDescResponse(x));
    }
}
