// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CategoryDescListData
    {
        private readonly global::Mezon.Net.Internal.Api.CategoryDescList _proto;
        internal CategoryDescListData(global::Mezon.Net.Internal.Api.CategoryDescList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.CategoryDescList Proto => _proto;

        public ProtoListView<CategoryDescData> Categorydesc => ProtoListView<CategoryDescData>.FromRepeated(_proto.Categorydesc, x => new CategoryDescData(x));
    }
}
