// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelTimelineDetailResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelTimelineDetailResponse _proto;
        internal ChannelTimelineDetailResponseData(global::Mezon.Net.Internal.Api.ChannelTimelineDetailResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelTimelineDetailResponse Proto => _proto;

        public ChannelTimelineData Event => new ChannelTimelineData(_proto.Event);
    }
}
