// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChanEncryptionMethodData
    {
        private readonly global::Mezon.Net.Internal.Api.ChanEncryptionMethod _proto;
        internal ChanEncryptionMethodData(global::Mezon.Net.Internal.Api.ChanEncryptionMethod proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChanEncryptionMethod Proto => _proto;

        public string Method => _proto.Method;
        public long ChannelId => _proto.ChannelId;
    }
}
