// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageSendData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelMessageSend _proto;
        internal ChannelMessageSendData(global::Mezon.Net.Internal.Realtime.ChannelMessageSend proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelMessageSend Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public string Content => _proto.Content;
        public ProtoListView<MessageMentionData> Mentions => ProtoListView<MessageMentionData>.FromRepeated(_proto.Mentions, x => new MessageMentionData(x));
        public ProtoListView<MessageAttachmentData> Attachments => ProtoListView<MessageAttachmentData>.FromRepeated(_proto.Attachments, x => new MessageAttachmentData(x));
        public ProtoListView<MessageRefData> References => ProtoListView<MessageRefData>.FromRepeated(_proto.References, x => new MessageRefData(x));
        public int Mode => _proto.Mode;
        public bool AnonymousMessage => _proto.AnonymousMessage;
        public bool MentionEveryone => _proto.MentionEveryone;
        public string Avatar => _proto.Avatar;
        public bool IsPublic => _proto.IsPublic;
        public int Code => _proto.Code;
        public long TopicId => _proto.TopicId;
        public long Id => _proto.Id;
    }
}
