// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageSendResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelMessageSend _proto;
        internal ChannelMessageSendResponse(global::Mezon.Net.Internal.Realtime.ChannelMessageSend proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelMessageSend Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public string Content => _proto.Content;
        public ProtoListView<MessageMentionResponse> Mentions => ProtoListView<MessageMentionResponse>.FromRepeated(_proto.Mentions, x => new MessageMentionResponse(x));
        public ProtoListView<MessageAttachmentResponse> Attachments => ProtoListView<MessageAttachmentResponse>.FromRepeated(_proto.Attachments, x => new MessageAttachmentResponse(x));
        public ProtoListView<MessageRefResponse> References => ProtoListView<MessageRefResponse>.FromRepeated(_proto.References, x => new MessageRefResponse(x));
        public int Mode => _proto.Mode;
        public bool AnonymousMessage => _proto.AnonymousMessage;
        public bool MentionEveryone => _proto.MentionEveryone;
        public string Avatar => _proto.Avatar;
        public bool IsPublic => _proto.IsPublic;
        public int Code => _proto.Code;
        public long TopicId => _proto.TopicId;
        public long Id => _proto.Id;
    }
}
