// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelSettingItemData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelSettingItem _proto;
        internal ChannelSettingItemData(global::Mezon.Net.Internal.Api.ChannelSettingItem proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelSettingItem Proto => _proto;

        public long Id => _proto.Id;
        public long CreatorId => _proto.CreatorId;
        public long ParentId => _proto.ParentId;
        public string ChannelLabel => _proto.ChannelLabel;
        public long CategoryId => _proto.CategoryId;
        public string MeetingCode => _proto.MeetingCode;
        public int ChannelPrivate => _proto.ChannelPrivate;
        public int ChannelType => _proto.ChannelType;
        public int Active => _proto.Active;
        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
        public long MessageCount => _proto.MessageCount;
        public ChannelMessageHeaderData LastSentMessage => new ChannelMessageHeaderData(_proto.LastSentMessage);
    }
}
