// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageListData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelMessageList _proto;
        internal ChannelMessageListData(global::Mezon.Net.Internal.Api.ChannelMessageList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelMessageList Proto => _proto;

        public ProtoListView<ChannelMessageData> Messages => ProtoListView<ChannelMessageData>.FromRepeated(_proto.Messages, x => new ChannelMessageData(x));
        public ChannelMessageHeaderData LastSeenMessage => new ChannelMessageHeaderData(_proto.LastSeenMessage);
        public ChannelMessageHeaderData LastSentMessage => new ChannelMessageHeaderData(_proto.LastSentMessage);
    }
}
