// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelCanvasListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelCanvasListResponse _proto;
        internal ChannelCanvasListResponse(global::Mezon.Net.Internal.Api.ChannelCanvasListResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelCanvasListResponse Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public ProtoListView<ChannelCanvasItemResponse> ChannelCanvases => ProtoListView<ChannelCanvasItemResponse>.FromRepeated(_proto.ChannelCanvases, x => new ChannelCanvasItemResponse(x));
        public int Count => _proto.Count;
    }
}
