// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelData
    {
        private readonly global::Mezon.Net.Internal.Realtime.Channel _proto;
        internal ChannelData(global::Mezon.Net.Internal.Realtime.Channel proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.Channel Proto => _proto;

        public long Id => _proto.Id;
        public ProtoListView<UserPresenceData> Presences => ProtoListView<UserPresenceData>.FromRepeated(_proto.Presences, x => new UserPresenceData(x));
        public UserPresenceData Self => new UserPresenceData(_proto.Self);
        public string ChanelLabel => _proto.ChanelLabel;
        public string ClanLogo => _proto.ClanLogo;
        public string CategoryName => _proto.CategoryName;
    }
}
