// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelTimelineData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelTimeline _proto;
        internal ChannelTimelineData(global::Mezon.Net.Internal.Api.ChannelTimeline proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelTimeline Proto => _proto;

        public long Id => _proto.Id;
        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public uint StartTimeSeconds => _proto.StartTimeSeconds;
        public string Title => _proto.Title;
        public string Description => _proto.Description;
        public uint EndTimeSeconds => _proto.EndTimeSeconds;
        public string Location => _proto.Location;
        public int Status => _proto.Status;
        public long CreatorId => _proto.CreatorId;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
        public int Type => _proto.Type;
        public byte[] Attachments => _proto.Attachments.ToByteArray();
        public byte[] PreviewImgs => _proto.PreviewImgs.ToByteArray();
    }
}
