// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelTimelineDetailResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelTimelineDetailResponse _proto;
        internal ChannelTimelineDetailResponse(global::Mezon.Net.Internal.Api.ChannelTimelineDetailResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelTimelineDetailResponse Proto => _proto;

        public ChannelTimelineResponse Event => new ChannelTimelineResponse(_proto.Event);
    }
}
