// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelDeletedEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelDeletedEvent _proto;
        internal ChannelDeletedEventData(global::Mezon.Net.Internal.Realtime.ChannelDeletedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelDeletedEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long CategoryId => _proto.CategoryId;
        public long ParentId => _proto.ParentId;
        public long ChannelId => _proto.ChannelId;
        public string Deletor => _proto.Deletor;
    }
}
