// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelCanvasItemData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelCanvasItem _proto;
        internal ChannelCanvasItemData(global::Mezon.Net.Internal.Api.ChannelCanvasItem proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelCanvasItem Proto => _proto;

        public long Id => _proto.Id;
        public string Title => _proto.Title;
        public bool IsDefault => _proto.IsDefault;
        public string Content => _proto.Content;
        public long CreatorId => _proto.CreatorId;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
    }
}
