// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelCreatedEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelCreatedEvent _proto;
        internal ChannelCreatedEventData(global::Mezon.Net.Internal.Realtime.ChannelCreatedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelCreatedEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long CategoryId => _proto.CategoryId;
        public long CreatorId => _proto.CreatorId;
        public long ParentId => _proto.ParentId;
        public long ChannelId => _proto.ChannelId;
        public string ChannelLabel => _proto.ChannelLabel;
        public int ChannelPrivate => _proto.ChannelPrivate;
        public int ChannelType => _proto.ChannelType;
        public int Status => _proto.Status;
        public long AppId => _proto.AppId;
        public string ClanName => _proto.ClanName;
        public string ChannelAvatar => _proto.ChannelAvatar;
    }
}
