// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelMessageList _proto;
        internal ChannelMessageListResponse(global::Mezon.Net.Internal.Api.ChannelMessageList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelMessageList Proto => _proto;

        public ProtoListView<ChannelMessageResponse> Messages => ProtoListView<ChannelMessageResponse>.FromRepeated(_proto.Messages, x => new ChannelMessageResponse(x));
        public ChannelMessageHeaderResponse LastSeenMessage => new ChannelMessageHeaderResponse(_proto.LastSeenMessage);
        public ChannelMessageHeaderResponse LastSentMessage => new ChannelMessageHeaderResponse(_proto.LastSentMessage);
    }
}
