// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelLeaveData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelLeave _proto;
        internal ChannelLeaveData(global::Mezon.Net.Internal.Realtime.ChannelLeave proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelLeave Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public int ChannelType => _proto.ChannelType;
        public bool IsPublic => _proto.IsPublic;
    }
}
