// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageRemoveData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelMessageRemove _proto;
        internal ChannelMessageRemoveData(global::Mezon.Net.Internal.Realtime.ChannelMessageRemove proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelMessageRemove Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public long MessageId => _proto.MessageId;
        public int Mode => _proto.Mode;
        public bool IsPublic => _proto.IsPublic;
        public bool HasAttachment => _proto.HasAttachment;
        public long TopicId => _proto.TopicId;
        public byte[] Mentions => _proto.Mentions.ToByteArray();
        public byte[] References => _proto.References.ToByteArray();
    }
}
