// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelDescListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelDescList _proto;
        internal ChannelDescListResponse(global::Mezon.Net.Internal.Api.ChannelDescList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelDescList Proto => _proto;

        public ProtoListView<ChannelDescriptionResponse> Channeldesc => ProtoListView<ChannelDescriptionResponse>.FromRepeated(_proto.Channeldesc, x => new ChannelDescriptionResponse(x));
    }
}
