// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelSettingListResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelSettingListResponse _proto;
        internal ChannelSettingListResponseData(global::Mezon.Net.Internal.Api.ChannelSettingListResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelSettingListResponse Proto => _proto;

        public long ClanId => _proto.ClanId;
        public int ChannelCount => _proto.ChannelCount;
        public int ThreadCount => _proto.ThreadCount;
        public ProtoListView<ChannelSettingItemData> ChannelSettingList => ProtoListView<ChannelSettingItemData>.FromRepeated(_proto.ChannelSettingList, x => new ChannelSettingItemData(x));
    }
}
