// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelAttachmentListData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelAttachmentList _proto;
        internal ChannelAttachmentListData(global::Mezon.Net.Internal.Api.ChannelAttachmentList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelAttachmentList Proto => _proto;

        public ProtoListView<ChannelAttachmentData> Attachments => ProtoListView<ChannelAttachmentData>.FromRepeated(_proto.Attachments, x => new ChannelAttachmentData(x));
    }
}
