// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelDescListNoPoolData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelDescListNoPool _proto;
        internal ChannelDescListNoPoolData(global::Mezon.Net.Internal.Api.ChannelDescListNoPool proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelDescListNoPool Proto => _proto;

        public ProtoListView<ChannelDescriptionData> Channeldesc => ProtoListView<ChannelDescriptionData>.FromRepeated(_proto.Channeldesc, x => new ChannelDescriptionData(x));
        public int Page => _proto.Page;
    }
}
