// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelUserData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelUserList.Types.ChannelUser _proto;
        internal ChannelUserData(global::Mezon.Net.Internal.Api.ChannelUserList.Types.ChannelUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelUserList.Types.ChannelUser Proto => _proto;

        public long UserId => _proto.UserId;
        public ProtoListView<long> RoleId => ProtoListView<long>.FromRepeated(_proto.RoleId);
        public long Id => _proto.Id;
        public long ThreadId => _proto.ThreadId;
        public string ClanNick => _proto.ClanNick;
        public string ClanAvatar => _proto.ClanAvatar;
        public long ClanId => _proto.ClanId;
        public long AddedBy => _proto.AddedBy;
        public bool IsBanned => _proto.IsBanned;
        public int ExpiredBanTime => _proto.ExpiredBanTime;
    }
}
