// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelAppResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelAppResponse _proto;
        internal ChannelAppResponse(global::Mezon.Net.Internal.Api.ChannelAppResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelAppResponse Proto => _proto;

        public long Id => _proto.Id;
        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public long AppId => _proto.AppId;
        public string AppUrl => _proto.AppUrl;
        public string AppName => _proto.AppName;
        public string AppLogo => _proto.AppLogo;
    }
}
