// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelJoinResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelJoin _proto;
        internal ChannelJoinResponse(global::Mezon.Net.Internal.Realtime.ChannelJoin proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelJoin Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public int ChannelType => _proto.ChannelType;
        public bool IsPublic => _proto.IsPublic;
    }
}
