// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelDescriptionData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelDescription _proto;
        internal ChannelDescriptionData(global::Mezon.Net.Internal.Api.ChannelDescription proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelDescription Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ParentId => _proto.ParentId;
        public long ChannelId => _proto.ChannelId;
        public long CategoryId => _proto.CategoryId;
        public string CategoryName => _proto.CategoryName;
        public int Type => _proto.Type;
        public long CreatorId => _proto.CreatorId;
        public string ChannelLabel => _proto.ChannelLabel;
        public int ChannelPrivate => _proto.ChannelPrivate;
        public ProtoListView<string> Avatars => ProtoListView<string>.FromRepeated(_proto.Avatars);
        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
        public ChannelMessageHeaderData LastSentMessage => new ChannelMessageHeaderData(_proto.LastSentMessage);
        public ChannelMessageHeaderData LastSeenMessage => new ChannelMessageHeaderData(_proto.LastSeenMessage);
        public string MeetingCode => _proto.MeetingCode;
        public int CountMessUnread => _proto.CountMessUnread;
        public int Active => _proto.Active;
        public string LastPinMessage => _proto.LastPinMessage;
        public ProtoListView<string> Usernames => ProtoListView<string>.FromRepeated(_proto.Usernames);
        public string CreatorName => _proto.CreatorName;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
        public ProtoListView<string> DisplayNames => ProtoListView<string>.FromRepeated(_proto.DisplayNames);
        public string ChannelAvatar => _proto.ChannelAvatar;
        public string ClanName => _proto.ClanName;
        public long AppId => _proto.AppId;
        public bool IsMute => _proto.IsMute;
        public int AgeRestricted => _proto.AgeRestricted;
        public string Topic => _proto.Topic;
        public int E2Ee => _proto.E2Ee;
        public int MemberCount => _proto.MemberCount;
    }
}
