// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelMessage _proto;
        internal ChannelMessageResponse(global::Mezon.Net.Internal.Api.ChannelMessage proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelMessage Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public long MessageId => _proto.MessageId;
        public int Code => _proto.Code;
        public long SenderId => _proto.SenderId;
        public string Username => _proto.Username;
        public string Avatar => _proto.Avatar;
        public string Content => _proto.Content;
        public string ChannelLabel => _proto.ChannelLabel;
        public string ClanLogo => _proto.ClanLogo;
        public string CategoryName => _proto.CategoryName;
        public string DisplayName => _proto.DisplayName;
        public string ClanNick => _proto.ClanNick;
        public string ClanAvatar => _proto.ClanAvatar;
        public byte[] Reactions => _proto.Reactions.ToByteArray();
        public byte[] Mentions => _proto.Mentions.ToByteArray();
        public byte[] Attachments => _proto.Attachments.ToByteArray();
        public byte[] References => _proto.References.ToByteArray();
        public byte[] ReferencedMessage => _proto.ReferencedMessage.ToByteArray();
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
        public int Mode => _proto.Mode;
        public bool HideEditted => _proto.HideEditted;
        public bool IsPublic => _proto.IsPublic;
        public long TopicId => _proto.TopicId;
    }
}
