// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelPresenceEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelPresenceEvent _proto;
        internal ChannelPresenceEventResponse(global::Mezon.Net.Internal.Realtime.ChannelPresenceEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelPresenceEvent Proto => _proto;

        public long ChannelId => _proto.ChannelId;
        public ProtoListView<UserPresenceResponse> Joins => ProtoListView<UserPresenceResponse>.FromRepeated(_proto.Joins, x => new UserPresenceResponse(x));
        public ProtoListView<UserPresenceResponse> Leaves => ProtoListView<UserPresenceResponse>.FromRepeated(_proto.Leaves, x => new UserPresenceResponse(x));
        public string ClanLogo => _proto.ClanLogo;
        public string CategoryName => _proto.CategoryName;
        public int Mode => _proto.Mode;
    }
}
