// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageHeaderData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelMessageHeader _proto;
        internal ChannelMessageHeaderData(global::Mezon.Net.Internal.Api.ChannelMessageHeader proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelMessageHeader Proto => _proto;

        public long Id => _proto.Id;
        public uint TimestampSeconds => _proto.TimestampSeconds;
        public long SenderId => _proto.SenderId;
        public string Content => _proto.Content;
    }
}
