// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelDescListNoPoolResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelDescListNoPool _proto;
        internal ChannelDescListNoPoolResponse(global::Mezon.Net.Internal.Api.ChannelDescListNoPool proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelDescListNoPool Proto => _proto;

        public ProtoListView<ChannelDescriptionResponse> Channeldesc => ProtoListView<ChannelDescriptionResponse>.FromRepeated(_proto.Channeldesc, x => new ChannelDescriptionResponse(x));
        public int Page => _proto.Page;
    }
}
