// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelArchiveEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ChannelArchiveEvent _proto;
        internal ChannelArchiveEventData(global::Mezon.Net.Internal.Realtime.ChannelArchiveEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ChannelArchiveEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long CategoryId => _proto.CategoryId;
        public long CreatorId => _proto.CreatorId;
        public long ParentId => _proto.ParentId;
        public long ChannelId => _proto.ChannelId;
        public string ChannelLabel => _proto.ChannelLabel;
        public int ChannelType => _proto.ChannelType;
        public int Status => _proto.Status;
        public string MeetingCode => _proto.MeetingCode;
        public bool IsError => _proto.IsError;
        public bool ChannelPrivate => _proto.ChannelPrivate;
        public long AppId => _proto.AppId;
        public int E2Ee => _proto.E2Ee;
        public string Topic => _proto.Topic;
        public int AgeRestricted => _proto.AgeRestricted;
        public int Active => _proto.Active;
        public int CountMessUnread => _proto.CountMessUnread;
        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
        public ProtoListView<long> RoleIds => ProtoListView<long>.FromRepeated(_proto.RoleIds);
        public string ChannelAvatar => _proto.ChannelAvatar;
    }
}
