// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelUserListData
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelUserList _proto;
        internal ChannelUserListData(global::Mezon.Net.Internal.Api.ChannelUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelUserList Proto => _proto;

        public ProtoListView<ChannelUserData> ChannelUsers => ProtoListView<ChannelUserData>.FromRepeated(_proto.ChannelUsers, x => new ChannelUserData(x));
        public string Cursor => _proto.Cursor;
        public long ChannelId => _proto.ChannelId;
    }
}
