// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ChannelUserListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ChannelUserList _proto;
        internal ChannelUserListResponse(global::Mezon.Net.Internal.Api.ChannelUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ChannelUserList Proto => _proto;

        public ProtoListView<ChannelUserResponse> ChannelUsers => ProtoListView<ChannelUserResponse>.FromRepeated(_proto.ChannelUsers, x => new ChannelUserResponse(x));
        public string Cursor => _proto.Cursor;
        public long ChannelId => _proto.ChannelId;
    }
}
