// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CheckDuplicateNameResponse
    {
        private readonly global::Mezon.Net.Internal.Api.CheckDuplicateNameResponse _proto;
        internal CheckDuplicateNameResponse(global::Mezon.Net.Internal.Api.CheckDuplicateNameResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.CheckDuplicateNameResponse Proto => _proto;

        public bool IsDuplicate => _proto.IsDuplicate;
    }
}
