// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanUserStatusListData
    {
        private readonly global::Mezon.Net.Internal.Api.ClanUserStatusList _proto;
        internal ClanUserStatusListData(global::Mezon.Net.Internal.Api.ClanUserStatusList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanUserStatusList Proto => _proto;

        public ProtoListView<ClanUserStatusEntryData> ClanUserStatuses => ProtoListView<ClanUserStatusEntryData>.FromRepeated(_proto.ClanUserStatuses, x => new ClanUserStatusEntryData(x));
    }
}
