// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanEmojiResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ClanEmoji _proto;
        internal ClanEmojiResponse(global::Mezon.Net.Internal.Api.ClanEmoji proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanEmoji Proto => _proto;

        public long Id => _proto.Id;
        public string Src => _proto.Src;
        public string Shortname => _proto.Shortname;
        public string Category => _proto.Category;
        public long CreatorId => _proto.CreatorId;
        public long ClanId => _proto.ClanId;
        public string Logo => _proto.Logo;
        public string ClanName => _proto.ClanName;
        public bool IsForSale => _proto.IsForSale;
    }
}
