// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanDescListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ClanDescList _proto;
        internal ClanDescListResponse(global::Mezon.Net.Internal.Api.ClanDescList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanDescList Proto => _proto;

        public ProtoListView<ClanDescResponse> Clandesc => ProtoListView<ClanDescResponse>.FromRepeated(_proto.Clandesc, x => new ClanDescResponse(x));
    }
}
