// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanUserData
    {
        private readonly global::Mezon.Net.Internal.Api.ClanUserList.Types.ClanUser _proto;
        internal ClanUserData(global::Mezon.Net.Internal.Api.ClanUserList.Types.ClanUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanUserList.Types.ClanUser Proto => _proto;

        public UserData User => new UserData(_proto.User);
        public ProtoListView<long> RoleId => ProtoListView<long>.FromRepeated(_proto.RoleId);
        public string ClanNick => _proto.ClanNick;
        public string ClanAvatar => _proto.ClanAvatar;
        public long ClanId => _proto.ClanId;
    }
}
