// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanProfileData
    {
        private readonly global::Mezon.Net.Internal.Api.ClanProfile _proto;
        internal ClanProfileData(global::Mezon.Net.Internal.Api.ClanProfile proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanProfile Proto => _proto;

        public long UserId => _proto.UserId;
        public string NickName => _proto.NickName;
        public string Avatar => _proto.Avatar;
        public long ClanId => _proto.ClanId;
        public string About => _proto.About;
    }
}
