// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanStickerResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ClanSticker _proto;
        internal ClanStickerResponse(global::Mezon.Net.Internal.Api.ClanSticker proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanSticker Proto => _proto;

        public long Id => _proto.Id;
        public string Source => _proto.Source;
        public string Shortname => _proto.Shortname;
        public string Category => _proto.Category;
        public long CreatorId => _proto.CreatorId;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public long ClanId => _proto.ClanId;
        public string Logo => _proto.Logo;
        public string ClanName => _proto.ClanName;
        public int MediaType => _proto.MediaType;
        public bool IsForSale => _proto.IsForSale;
    }
}
