// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanDescResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ClanDesc _proto;
        internal ClanDescResponse(global::Mezon.Net.Internal.Api.ClanDesc proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanDesc Proto => _proto;

        public long CreatorId => _proto.CreatorId;
        public string ClanName => _proto.ClanName;
        public string Logo => _proto.Logo;
        public string Banner => _proto.Banner;
        public long ClanId => _proto.ClanId;
        public int Status => _proto.Status;
        public int BadgeCount => _proto.BadgeCount;
        public bool IsOnboarding => _proto.IsOnboarding;
        public long WelcomeChannelId => _proto.WelcomeChannelId;
        public string OnboardingBanner => _proto.OnboardingBanner;
        public int ClanOrder => _proto.ClanOrder;
        public bool IsCommunity => _proto.IsCommunity;
        public string CommunityBanner => _proto.CommunityBanner;
        public string Description => _proto.Description;
        public string About => _proto.About;
        public string ShortUrl => _proto.ShortUrl;
        public bool PreventAnonymous => _proto.PreventAnonymous;
        public bool HasUnreadMessage => _proto.HasUnreadMessage;
    }
}
