// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanBadgeCountResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ClanBadgeCount _proto;
        internal ClanBadgeCountResponse(global::Mezon.Net.Internal.Api.ClanBadgeCount proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanBadgeCount Proto => _proto;

        public long ClanId => _proto.ClanId;
        public int Badge => _proto.Badge;
        public bool HasUnread => _proto.HasUnread;
    }
}
