// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanUserStatusEntryData
    {
        private readonly global::Mezon.Net.Internal.Api.ClanUserStatusEntry _proto;
        internal ClanUserStatusEntryData(global::Mezon.Net.Internal.Api.ClanUserStatusEntry proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanUserStatusEntry Proto => _proto;

        public long UserId => _proto.UserId;
        public string UserStatus => _proto.UserStatus;
    }
}
