// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanUserListData
    {
        private readonly global::Mezon.Net.Internal.Api.ClanUserList _proto;
        internal ClanUserListData(global::Mezon.Net.Internal.Api.ClanUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanUserList Proto => _proto;

        public ProtoListView<ClanUserData> ClanUsers => ProtoListView<ClanUserData>.FromRepeated(_proto.ClanUsers, x => new ClanUserData(x));
        public string Cursor => _proto.Cursor;
        public long ClanId => _proto.ClanId;
    }
}
