// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanUserListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ClanUserList _proto;
        internal ClanUserListResponse(global::Mezon.Net.Internal.Api.ClanUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanUserList Proto => _proto;

        public ProtoListView<ClanUserResponse> ClanUsers => ProtoListView<ClanUserResponse>.FromRepeated(_proto.ClanUsers, x => new ClanUserResponse(x));
        public string Cursor => _proto.Cursor;
        public long ClanId => _proto.ClanId;
    }
}
