// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanWebhookResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ClanWebhook _proto;
        internal ClanWebhookResponse(global::Mezon.Net.Internal.Api.ClanWebhook proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ClanWebhook Proto => _proto;

        public long Id => _proto.Id;
        public string WebhookName => _proto.WebhookName;
        public long ClanId => _proto.ClanId;
        public int Active => _proto.Active;
        public string Url => _proto.Url;
        public long CreatorId => _proto.CreatorId;
        public string Avatar => _proto.Avatar;
        public string CreateTime => _proto.CreateTime;
        public string UpdateTime => _proto.UpdateTime;
    }
}
