// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ClanJoinData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ClanJoin _proto;
        internal ClanJoinData(global::Mezon.Net.Internal.Realtime.ClanJoin proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ClanJoin Proto => _proto;

        public long ClanId => _proto.ClanId;
    }
}
