// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreateChannelTimelineResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.CreateChannelTimelineResponse _proto;
        internal CreateChannelTimelineResponseData(global::Mezon.Net.Internal.Api.CreateChannelTimelineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.CreateChannelTimelineResponse Proto => _proto;

        public ChannelTimelineData Event => new ChannelTimelineData(_proto.Event);
    }
}
