// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreateRoomChannelAppsResponse
    {
        private readonly global::Mezon.Net.Internal.Api.CreateRoomChannelApps _proto;
        internal CreateRoomChannelAppsResponse(global::Mezon.Net.Internal.Api.CreateRoomChannelApps proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.CreateRoomChannelApps Proto => _proto;

        public long ChannelId => _proto.ChannelId;
        public string RoomName => _proto.RoomName;
    }
}
