// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreatePollResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.CreatePollResponse _proto;
        internal CreatePollResponseData(global::Mezon.Net.Internal.Api.CreatePollResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.CreatePollResponse Proto => _proto;

        public long PollId => _proto.PollId;
        public long MessageId => _proto.MessageId;
        public string Question => _proto.Question;
        public ProtoListView<PollAnswerData> Answers => ProtoListView<PollAnswerData>.FromRepeated(_proto.Answers, x => new PollAnswerData(x));
        public ProtoListView<int> AnswerCounts => ProtoListView<int>.FromRepeated(_proto.AnswerCounts);
        public long Exp => _proto.Exp;
        public bool IsClosed => _proto.IsClosed;
        public long CreatorId => _proto.CreatorId;
        public global::Mezon.Net.Internal.Api.PollType Type => _proto.Type;
        public int TotalVotes => _proto.TotalVotes;
    }
}
