// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CreateChannelTimelineResponse
    {
        private readonly global::Mezon.Net.Internal.Api.CreateChannelTimelineResponse _proto;
        internal CreateChannelTimelineResponse(global::Mezon.Net.Internal.Api.CreateChannelTimelineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.CreateChannelTimelineResponse Proto => _proto;

        public ChannelTimelineResponse Event => new ChannelTimelineResponse(_proto.Event);
    }
}
