// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct CustomStatusEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.CustomStatusEvent _proto;
        internal CustomStatusEventResponse(global::Mezon.Net.Internal.Realtime.CustomStatusEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.CustomStatusEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long UserId => _proto.UserId;
        public string Username => _proto.Username;
        public string Status => _proto.Status;
        public int TimeReset => _proto.TimeReset;
        public bool NoClear => _proto.NoClear;
    }
}
