// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct DropdownBoxSelectedResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.DropdownBoxSelected _proto;
        internal DropdownBoxSelectedResponse(global::Mezon.Net.Internal.Realtime.DropdownBoxSelected proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.DropdownBoxSelected Proto => _proto;

        public long MessageId => _proto.MessageId;
        public long ChannelId => _proto.ChannelId;
        public string SelectboxId => _proto.SelectboxId;
        public long SenderId => _proto.SenderId;
        public long UserId => _proto.UserId;
        public ProtoListView<string> Values => ProtoListView<string>.FromRepeated(_proto.Values);
    }
}
