// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EditChannelCanvasResponse
    {
        private readonly global::Mezon.Net.Internal.Api.EditChannelCanvasResponse _proto;
        internal EditChannelCanvasResponse(global::Mezon.Net.Internal.Api.EditChannelCanvasResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EditChannelCanvasResponse Proto => _proto;

        public long Id => _proto.Id;
    }
}
