// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EmojiListedResponse
    {
        private readonly global::Mezon.Net.Internal.Api.EmojiListedResponse _proto;
        internal EmojiListedResponse(global::Mezon.Net.Internal.Api.EmojiListedResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EmojiListedResponse Proto => _proto;

        public ProtoListView<ClanEmojiResponse> EmojiList => ProtoListView<ClanEmojiResponse>.FromRepeated(_proto.EmojiList, x => new ClanEmojiResponse(x));
    }
}
