// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EmojiRecentListData
    {
        private readonly global::Mezon.Net.Internal.Api.EmojiRecentList _proto;
        internal EmojiRecentListData(global::Mezon.Net.Internal.Api.EmojiRecentList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EmojiRecentList Proto => _proto;

        public ProtoListView<EmojiRecentData> EmojiRecents => ProtoListView<EmojiRecentData>.FromRepeated(_proto.EmojiRecents, x => new EmojiRecentData(x));
    }
}
