// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EmojiRecentListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.EmojiRecentList _proto;
        internal EmojiRecentListResponse(global::Mezon.Net.Internal.Api.EmojiRecentList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EmojiRecentList Proto => _proto;

        public ProtoListView<EmojiRecentResponse> EmojiRecents => ProtoListView<EmojiRecentResponse>.FromRepeated(_proto.EmojiRecents, x => new EmojiRecentResponse(x));
    }
}
