// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EmojiRecentData
    {
        private readonly global::Mezon.Net.Internal.Api.EmojiRecent _proto;
        internal EmojiRecentData(global::Mezon.Net.Internal.Api.EmojiRecent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EmojiRecent Proto => _proto;

        public long EmojiRecentsId => _proto.EmojiRecentsId;
        public long EmojiId => _proto.EmojiId;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
    }
}
