// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EmojiListedResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.EmojiListedResponse _proto;
        internal EmojiListedResponseData(global::Mezon.Net.Internal.Api.EmojiListedResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EmojiListedResponse Proto => _proto;

        public ProtoListView<ClanEmojiData> EmojiList => ProtoListView<ClanEmojiData>.FromRepeated(_proto.EmojiList, x => new ClanEmojiData(x));
    }
}
