// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ErrorData
    {
        private readonly global::Mezon.Net.Internal.Realtime.Error _proto;
        internal ErrorData(global::Mezon.Net.Internal.Realtime.Error proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.Error Proto => _proto;

        public IReadOnlyDictionary<string, string> Context => _proto.Context;
        public int Code => _proto.Code;
        public string Message => _proto.Message;
    }
}
