// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EventListData
    {
        private readonly global::Mezon.Net.Internal.Api.EventList _proto;
        internal EventListData(global::Mezon.Net.Internal.Api.EventList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EventList Proto => _proto;

        public ProtoListView<EventManagementData> Events => ProtoListView<EventManagementData>.FromRepeated(_proto.Events, x => new EventManagementData(x));
    }
}
