// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EventListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.EventList _proto;
        internal EventListResponse(global::Mezon.Net.Internal.Api.EventList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EventList Proto => _proto;

        public ProtoListView<EventManagementResponse> Events => ProtoListView<EventManagementResponse>.FromRepeated(_proto.Events, x => new EventManagementResponse(x));
    }
}
