// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct EventManagementResponse
    {
        private readonly global::Mezon.Net.Internal.Api.EventManagement _proto;
        internal EventManagementResponse(global::Mezon.Net.Internal.Api.EventManagement proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.EventManagement Proto => _proto;

        public long Id => _proto.Id;
        public string Title => _proto.Title;
        public string Logo => _proto.Logo;
        public string Description => _proto.Description;
        public int Active => _proto.Active;
        public int StartEvent => _proto.StartEvent;
        public long CreatorId => _proto.CreatorId;
        public long ClanId => _proto.ClanId;
        public long ChannelVoiceId => _proto.ChannelVoiceId;
        public string Address => _proto.Address;
        public uint StartTimeSeconds => _proto.StartTimeSeconds;
        public uint EndTimeSeconds => _proto.EndTimeSeconds;
        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public int MaxPermission => _proto.MaxPermission;
        public long ChannelId => _proto.ChannelId;
        public int EventStatus => _proto.EventStatus;
        public int RepeatType => _proto.RepeatType;
        public bool IsPrivate => _proto.IsPrivate;
        public GenerateMezonMeetResponse MeetRoom => new GenerateMezonMeetResponse(_proto.MeetRoom);
    }
}
