// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct FCMTokensData
    {
        private readonly global::Mezon.Net.Internal.Realtime.FCMTokens _proto;
        internal FCMTokensData(global::Mezon.Net.Internal.Realtime.FCMTokens proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.FCMTokens Proto => _proto;

        public string DeviceId => _proto.DeviceId;
        public string TokenId => _proto.TokenId;
        public string Platform => _proto.Platform;
    }
}
