// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ForSaleItemData
    {
        private readonly global::Mezon.Net.Internal.Api.ForSaleItem _proto;
        internal ForSaleItemData(global::Mezon.Net.Internal.Api.ForSaleItem proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ForSaleItem Proto => _proto;

        public int Type => _proto.Type;
        public string PreviewUrl => _proto.PreviewUrl;
    }
}
