// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ForSaleItemListData
    {
        private readonly global::Mezon.Net.Internal.Api.ForSaleItemList _proto;
        internal ForSaleItemListData(global::Mezon.Net.Internal.Api.ForSaleItemList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ForSaleItemList Proto => _proto;

        public ProtoListView<ForSaleItemData> ForSaleItems => ProtoListView<ForSaleItemData>.FromRepeated(_proto.ForSaleItems, x => new ForSaleItemData(x));
    }
}
