// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ForSaleItemListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ForSaleItemList _proto;
        internal ForSaleItemListResponse(global::Mezon.Net.Internal.Api.ForSaleItemList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ForSaleItemList Proto => _proto;

        public ProtoListView<ForSaleItemResponse> ForSaleItems => ProtoListView<ForSaleItemResponse>.FromRepeated(_proto.ForSaleItems, x => new ForSaleItemResponse(x));
    }
}
