// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct FriendListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.FriendList _proto;
        internal FriendListResponse(global::Mezon.Net.Internal.Api.FriendList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.FriendList Proto => _proto;

        public ProtoListView<FriendResponse> Friends => ProtoListView<FriendResponse>.FromRepeated(_proto.Friends, x => new FriendResponse(x));
        public string Cursor => _proto.Cursor;
    }
}
