// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct FriendListData
    {
        private readonly global::Mezon.Net.Internal.Api.FriendList _proto;
        internal FriendListData(global::Mezon.Net.Internal.Api.FriendList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.FriendList Proto => _proto;

        public ProtoListView<FriendData> Friends => ProtoListView<FriendData>.FromRepeated(_proto.Friends, x => new FriendData(x));
        public string Cursor => _proto.Cursor;
    }
}
