// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateCDNSignatureResponse
    {
        private readonly global::Mezon.Net.Internal.Api.GenerateCDNSignatureResponse _proto;
        internal GenerateCDNSignatureResponse(global::Mezon.Net.Internal.Api.GenerateCDNSignatureResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GenerateCDNSignatureResponse Proto => _proto;

        public string Signature => _proto.Signature;
    }
}
