// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateMeetTokenResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.GenerateMeetTokenResponse _proto;
        internal GenerateMeetTokenResponseData(global::Mezon.Net.Internal.Api.GenerateMeetTokenResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GenerateMeetTokenResponse Proto => _proto;

        public string Token => _proto.Token;
    }
}
