// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateHashChannelAppsResponse
    {
        private readonly global::Mezon.Net.Internal.Api.GenerateHashChannelAppsResponse _proto;
        internal GenerateHashChannelAppsResponse(global::Mezon.Net.Internal.Api.GenerateHashChannelAppsResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GenerateHashChannelAppsResponse Proto => _proto;

        public string WebAppData => _proto.WebAppData;
    }
}
