// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateClanWebhookResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.GenerateClanWebhookResponse _proto;
        internal GenerateClanWebhookResponseData(global::Mezon.Net.Internal.Api.GenerateClanWebhookResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GenerateClanWebhookResponse Proto => _proto;

        public long ClanId => _proto.ClanId;
        public string Url => _proto.Url;
        public string WebhookName => _proto.WebhookName;
        public string Avatar => _proto.Avatar;
    }
}
