// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GenerateMezonMeetResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.GenerateMezonMeetResponse _proto;
        internal GenerateMezonMeetResponseData(global::Mezon.Net.Internal.Api.GenerateMezonMeetResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GenerateMezonMeetResponse Proto => _proto;

        public long MeetId => _proto.MeetId;
        public string RoomName => _proto.RoomName;
        public string ExternalLink => _proto.ExternalLink;
        public long CreatorId => _proto.CreatorId;
        public long EventId => _proto.EventId;
    }
}
