// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GetKeyServerRespData
    {
        private readonly global::Mezon.Net.Internal.Api.GetKeyServerResp _proto;
        internal GetKeyServerRespData(global::Mezon.Net.Internal.Api.GetKeyServerResp proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GetKeyServerResp Proto => _proto;

        public string Url => _proto.Url;
    }
}
