// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GetPollResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.GetPollResponse _proto;
        internal GetPollResponseData(global::Mezon.Net.Internal.Api.GetPollResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GetPollResponse Proto => _proto;

        public long PollId => _proto.PollId;
        public long MessageId => _proto.MessageId;
        public string Question => _proto.Question;
        public ProtoListView<PollAnswerData> Answers => ProtoListView<PollAnswerData>.FromRepeated(_proto.Answers, x => new PollAnswerData(x));
        public ProtoListView<int> AnswerCounts => ProtoListView<int>.FromRepeated(_proto.AnswerCounts);
        public long Exp => _proto.Exp;
        public bool IsClosed => _proto.IsClosed;
        public long CreatorId => _proto.CreatorId;
        public global::Mezon.Net.Internal.Api.PollType Type => _proto.Type;
        public int TotalVotes => _proto.TotalVotes;
        public ProtoListView<PollVoterDetailData> VoterDetails => ProtoListView<PollVoterDetailData>.FromRepeated(_proto.VoterDetails, x => new PollVoterDetailData(x));
    }
}
