// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GetPubKeysResponse
    {
        private readonly global::Mezon.Net.Internal.Api.GetPubKeysResponse _proto;
        internal GetPubKeysResponse(global::Mezon.Net.Internal.Api.GetPubKeysResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GetPubKeysResponse Proto => _proto;

        public ProtoListView<UserPubKeyResponse> PubKeys => ProtoListView<UserPubKeyResponse>.FromRepeated(_proto.PubKeys, x => new UserPubKeyResponse(x));
    }
}
