// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct GetPubKeysResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.GetPubKeysResponse _proto;
        internal GetPubKeysResponseData(global::Mezon.Net.Internal.Api.GetPubKeysResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GetPubKeysResponse Proto => _proto;

        public ProtoListView<UserPubKeyData> PubKeys => ProtoListView<UserPubKeyData>.FromRepeated(_proto.PubKeys, x => new UserPubKeyData(x));
    }
}
