// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct InviteUserResData
    {
        private readonly global::Mezon.Net.Internal.Api.InviteUserRes _proto;
        internal InviteUserResData(global::Mezon.Net.Internal.Api.InviteUserRes proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.InviteUserRes Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public string ClanName => _proto.ClanName;
        public string ChannelLabel => _proto.ChannelLabel;
        public bool UserJoined => _proto.UserJoined;
        public uint ExpiryTimeSeconds => _proto.ExpiryTimeSeconds;
        public string ClanLogo => _proto.ClanLogo;
        public int MemberCount => _proto.MemberCount;
        public string Banner => _proto.Banner;
        public string CommunityBanner => _proto.CommunityBanner;
        public bool IsCommunity => _proto.IsCommunity;
    }
}
