// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct IsBannedResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.IsBannedResponse _proto;
        internal IsBannedResponseData(global::Mezon.Net.Internal.Api.IsBannedResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.IsBannedResponse Proto => _proto;

        public bool IsBanned => _proto.IsBanned;
        public int ExpiredBanTime => _proto.ExpiredBanTime;
    }
}
