// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LastPinMessageEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.LastPinMessageEvent _proto;
        internal LastPinMessageEventData(global::Mezon.Net.Internal.Realtime.LastPinMessageEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.LastPinMessageEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public long MessageId => _proto.MessageId;
        public int Mode => _proto.Mode;
        public long UserId => _proto.UserId;
        public uint TimestampSeconds => _proto.TimestampSeconds;
        public int Operation => _proto.Operation;
        public bool IsPublic => _proto.IsPublic;
        public string MessageSenderAvatar => _proto.MessageSenderAvatar;
        public string MessageSenderId => _proto.MessageSenderId;
        public string MessageSenderUsername => _proto.MessageSenderUsername;
        public string MessageContent => _proto.MessageContent;
        public string MessageAttachment => _proto.MessageAttachment;
        public string MessageCreatedTime => _proto.MessageCreatedTime;
    }
}
