// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LinkInviteUserData
    {
        private readonly global::Mezon.Net.Internal.Api.LinkInviteUser _proto;
        internal LinkInviteUserData(global::Mezon.Net.Internal.Api.LinkInviteUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.LinkInviteUser Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long CreatorId => _proto.CreatorId;
        public long ChannelId => _proto.ChannelId;
        public string InviteLink => _proto.InviteLink;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public uint ExpiryTimeSeconds => _proto.ExpiryTimeSeconds;
        public long Id => _proto.Id;
    }
}
