// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListClanWebhookResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListClanWebhookResponse _proto;
        internal ListClanWebhookResponse(global::Mezon.Net.Internal.Api.ListClanWebhookResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListClanWebhookResponse Proto => _proto;

        public ProtoListView<ClanWebhookResponse> ListClanWebhooks => ProtoListView<ClanWebhookResponse>.FromRepeated(_proto.ListClanWebhooks, x => new ClanWebhookResponse(x));
    }
}
