// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListAuditLogData
    {
        private readonly global::Mezon.Net.Internal.Api.ListAuditLog _proto;
        internal ListAuditLogData(global::Mezon.Net.Internal.Api.ListAuditLog proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListAuditLog Proto => _proto;

        public int TotalCount => _proto.TotalCount;
        public string DateLog => _proto.DateLog;
        public ProtoListView<AuditLogData> Logs => ProtoListView<AuditLogData>.FromRepeated(_proto.Logs, x => new AuditLogData(x));
    }
}
