// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListChannelUsersBannedEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.ListChannelUsersBannedEvent _proto;
        internal ListChannelUsersBannedEventData(global::Mezon.Net.Internal.Realtime.ListChannelUsersBannedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ListChannelUsersBannedEvent Proto => _proto;

        public ProtoListView<long> BannedUserIds => ProtoListView<long>.FromRepeated(_proto.BannedUserIds);
    }
}
