// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListOnboardingStepResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListOnboardingStepResponse _proto;
        internal ListOnboardingStepResponseData(global::Mezon.Net.Internal.Api.ListOnboardingStepResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListOnboardingStepResponse Proto => _proto;

        public ProtoListView<OnboardingStepsData> ListOnboardingStep => ProtoListView<OnboardingStepsData>.FromRepeated(_proto.ListOnboardingStep, x => new OnboardingStepsData(x));
    }
}
