// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListClanWebhookResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListClanWebhookResponse _proto;
        internal ListClanWebhookResponseData(global::Mezon.Net.Internal.Api.ListClanWebhookResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListClanWebhookResponse Proto => _proto;

        public ProtoListView<ClanWebhookData> ListClanWebhooks => ProtoListView<ClanWebhookData>.FromRepeated(_proto.ListClanWebhooks, x => new ClanWebhookData(x));
    }
}
