// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListChannelBadgeCountResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListChannelBadgeCountResponse _proto;
        internal ListChannelBadgeCountResponseData(global::Mezon.Net.Internal.Api.ListChannelBadgeCountResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListChannelBadgeCountResponse Proto => _proto;

        public ProtoListView<ChannelDescriptionData> Channeldesc => ProtoListView<ChannelDescriptionData>.FromRepeated(_proto.Channeldesc, x => new ChannelDescriptionData(x));
        public int TotalCount => _proto.TotalCount;
    }
}
