// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListUserOnlineResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListUserOnlineResponse _proto;
        internal ListUserOnlineResponse(global::Mezon.Net.Internal.Api.ListUserOnlineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListUserOnlineResponse Proto => _proto;

        public ProtoListView<UserResponse> Users => ProtoListView<UserResponse>.FromRepeated(_proto.Users, x => new UserResponse(x));
        public int TotalCount => _proto.TotalCount;
    }
}
