// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListArchivedChannelDescsResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListArchivedChannelDescsResponse _proto;
        internal ListArchivedChannelDescsResponse(global::Mezon.Net.Internal.Api.ListArchivedChannelDescsResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListArchivedChannelDescsResponse Proto => _proto;

        public ProtoListView<ChannelDescriptionResponse> Channeldesc => ProtoListView<ChannelDescriptionResponse>.FromRepeated(_proto.Channeldesc, x => new ChannelDescriptionResponse(x));
    }
}
