// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListFavoriteChannelResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListFavoriteChannelResponse _proto;
        internal ListFavoriteChannelResponse(global::Mezon.Net.Internal.Api.ListFavoriteChannelResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListFavoriteChannelResponse Proto => _proto;

        public ProtoListView<long> ChannelIds => ProtoListView<long>.FromRepeated(_proto.ChannelIds);
    }
}
