// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListClanBadgeCountResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListClanBadgeCountResponse _proto;
        internal ListClanBadgeCountResponse(global::Mezon.Net.Internal.Api.ListClanBadgeCountResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListClanBadgeCountResponse Proto => _proto;

        public ProtoListView<ClanBadgeCountResponse> ListBadge => ProtoListView<ClanBadgeCountResponse>.FromRepeated(_proto.ListBadge, x => new ClanBadgeCountResponse(x));
    }
}
