// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListUserActivityResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListUserActivity _proto;
        internal ListUserActivityResponse(global::Mezon.Net.Internal.Api.ListUserActivity proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListUserActivity Proto => _proto;

        public ProtoListView<UserActivityResponse> Activities => ProtoListView<UserActivityResponse>.FromRepeated(_proto.Activities, x => new UserActivityResponse(x));
    }
}
