// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListChannelTimelineResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListChannelTimelineResponse _proto;
        internal ListChannelTimelineResponse(global::Mezon.Net.Internal.Api.ListChannelTimelineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListChannelTimelineResponse Proto => _proto;

        public ProtoListView<ChannelTimelineResponse> Events => ProtoListView<ChannelTimelineResponse>.FromRepeated(_proto.Events, x => new ChannelTimelineResponse(x));
    }
}
