// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListUserActivityData
    {
        private readonly global::Mezon.Net.Internal.Api.ListUserActivity _proto;
        internal ListUserActivityData(global::Mezon.Net.Internal.Api.ListUserActivity proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListUserActivity Proto => _proto;

        public ProtoListView<UserActivityData> Activities => ProtoListView<UserActivityData>.FromRepeated(_proto.Activities, x => new UserActivityData(x));
    }
}
