// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListChannelBadgeCountResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListChannelBadgeCountResponse _proto;
        internal ListChannelBadgeCountResponse(global::Mezon.Net.Internal.Api.ListChannelBadgeCountResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListChannelBadgeCountResponse Proto => _proto;

        public ProtoListView<ChannelDescriptionResponse> Channeldesc => ProtoListView<ChannelDescriptionResponse>.FromRepeated(_proto.Channeldesc, x => new ChannelDescriptionResponse(x));
        public int TotalCount => _proto.TotalCount;
    }
}
