// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListOnboardingStepResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListOnboardingStepResponse _proto;
        internal ListOnboardingStepResponse(global::Mezon.Net.Internal.Api.ListOnboardingStepResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListOnboardingStepResponse Proto => _proto;

        public ProtoListView<OnboardingStepsResponse> ListOnboardingStep => ProtoListView<OnboardingStepsResponse>.FromRepeated(_proto.ListOnboardingStep, x => new OnboardingStepsResponse(x));
    }
}
