// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListUserOnlineResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListUserOnlineResponse _proto;
        internal ListUserOnlineResponseData(global::Mezon.Net.Internal.Api.ListUserOnlineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListUserOnlineResponse Proto => _proto;

        public ProtoListView<UserData> Users => ProtoListView<UserData>.FromRepeated(_proto.Users, x => new UserData(x));
        public int TotalCount => _proto.TotalCount;
    }
}
