// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListClanBadgeCountResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListClanBadgeCountResponse _proto;
        internal ListClanBadgeCountResponseData(global::Mezon.Net.Internal.Api.ListClanBadgeCountResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListClanBadgeCountResponse Proto => _proto;

        public ProtoListView<ClanBadgeCountData> ListBadge => ProtoListView<ClanBadgeCountData>.FromRepeated(_proto.ListBadge, x => new ClanBadgeCountData(x));
    }
}
