// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListChannelTimelineResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListChannelTimelineResponse _proto;
        internal ListChannelTimelineResponseData(global::Mezon.Net.Internal.Api.ListChannelTimelineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListChannelTimelineResponse Proto => _proto;

        public ProtoListView<ChannelTimelineData> Events => ProtoListView<ChannelTimelineData>.FromRepeated(_proto.Events, x => new ChannelTimelineData(x));
    }
}
