// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListArchivedChannelDescsResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListArchivedChannelDescsResponse _proto;
        internal ListArchivedChannelDescsResponseData(global::Mezon.Net.Internal.Api.ListArchivedChannelDescsResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListArchivedChannelDescsResponse Proto => _proto;

        public ProtoListView<ChannelDescriptionData> Channeldesc => ProtoListView<ChannelDescriptionData>.FromRepeated(_proto.Channeldesc, x => new ChannelDescriptionData(x));
    }
}
