// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListOnboardingResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.ListOnboardingResponse _proto;
        internal ListOnboardingResponseData(global::Mezon.Net.Internal.Api.ListOnboardingResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListOnboardingResponse Proto => _proto;

        public ProtoListView<OnboardingItemData> ListOnboarding => ProtoListView<OnboardingItemData>.FromRepeated(_proto.ListOnboarding, x => new OnboardingItemData(x));
    }
}
