// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ListChannelAppsResponse
    {
        private readonly global::Mezon.Net.Internal.Api.ListChannelAppsResponse _proto;
        internal ListChannelAppsResponse(global::Mezon.Net.Internal.Api.ListChannelAppsResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.ListChannelAppsResponse Proto => _proto;

        public ProtoListView<ChannelAppResponse> ChannelApps => ProtoListView<ChannelAppResponse>.FromRepeated(_proto.ChannelApps, x => new ChannelAppResponse(x));
    }
}
