// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LogedDeviceListData
    {
        private readonly global::Mezon.Net.Internal.Api.LogedDeviceList _proto;
        internal LogedDeviceListData(global::Mezon.Net.Internal.Api.LogedDeviceList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.LogedDeviceList Proto => _proto;

        public ProtoListView<LogedDeviceData> Devices => ProtoListView<LogedDeviceData>.FromRepeated(_proto.Devices, x => new LogedDeviceData(x));
    }
}
