// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LogedDeviceListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.LogedDeviceList _proto;
        internal LogedDeviceListResponse(global::Mezon.Net.Internal.Api.LogedDeviceList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.LogedDeviceList Proto => _proto;

        public ProtoListView<LogedDeviceResponse> Devices => ProtoListView<LogedDeviceResponse>.FromRepeated(_proto.Devices, x => new LogedDeviceResponse(x));
    }
}
