// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LogedDeviceResponse
    {
        private readonly global::Mezon.Net.Internal.Api.LogedDevice _proto;
        internal LogedDeviceResponse(global::Mezon.Net.Internal.Api.LogedDevice proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.LogedDevice Proto => _proto;

        public string DeviceId => _proto.DeviceId;
        public string DeviceName => _proto.DeviceName;
        public uint LoginAtSeconds => _proto.LoginAtSeconds;
        public int Status => _proto.Status;
        public string Platform => _proto.Platform;
        public string Ip => _proto.Ip;
        public uint LastActiveSeconds => _proto.LastActiveSeconds;
        public string Location => _proto.Location;
        public bool IsCurrent => _proto.IsCurrent;
    }
}
