// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct LoginIdResponse
    {
        private readonly global::Mezon.Net.Internal.Api.LoginIDResponse _proto;
        internal LoginIdResponse(global::Mezon.Net.Internal.Api.LoginIDResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.LoginIDResponse Proto => _proto;

        public long LoginId => _proto.LoginId;
        public int Status => _proto.Status;
        public long CreateTimeSeconds => _proto.CreateTimeSeconds;
        public string Platform => _proto.Platform;
        public long UserId => _proto.UserId;
        public string Username => _proto.Username;
        public string Address => _proto.Address;
    }
}
