// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MentionUserResponse
    {
        private readonly global::Mezon.Net.Internal.Api.MentionUser _proto;
        internal MentionUserResponse(global::Mezon.Net.Internal.Api.MentionUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MentionUser Proto => _proto;

        public long Id => _proto.Id;
        public string Username => _proto.Username;
        public string DisplayName => _proto.DisplayName;
        public string AvatarUrl => _proto.AvatarUrl;
        public string ClanNick => _proto.ClanNick;
        public string ClanAvatar => _proto.ClanAvatar;
    }
}
