// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageMentionResponse
    {
        private readonly global::Mezon.Net.Internal.Api.MessageMention _proto;
        internal MessageMentionResponse(global::Mezon.Net.Internal.Api.MessageMention proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MessageMention Proto => _proto;

        public long Id => _proto.Id;
        public long UserId => _proto.UserId;
        public string Username => _proto.Username;
        public long RoleId => _proto.RoleId;
        public string Rolename => _proto.Rolename;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public int S => _proto.S;
        public int E => _proto.E;
    }
}
