// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageReactionResponse
    {
        private readonly global::Mezon.Net.Internal.Api.MessageReaction _proto;
        internal MessageReactionResponse(global::Mezon.Net.Internal.Api.MessageReaction proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MessageReaction Proto => _proto;

        public long Id => _proto.Id;
        public long EmojiId => _proto.EmojiId;
        public string Emoji => _proto.Emoji;
        public long SenderId => _proto.SenderId;
        public string SenderName => _proto.SenderName;
        public string SenderAvatar => _proto.SenderAvatar;
        public bool Action => _proto.Action;
        public int Count => _proto.Count;
        public long ChannelId => _proto.ChannelId;
        public long MessageId => _proto.MessageId;
        public long ClanId => _proto.ClanId;
        public int Mode => _proto.Mode;
        public long MessageSenderId => _proto.MessageSenderId;
        public bool IsPublic => _proto.IsPublic;
        public long TopicId => _proto.TopicId;
        public long EmojiRecentId => _proto.EmojiRecentId;
    }
}
