// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageTypingEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.MessageTypingEvent _proto;
        internal MessageTypingEventResponse(global::Mezon.Net.Internal.Realtime.MessageTypingEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.MessageTypingEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public long SenderId => _proto.SenderId;
        public int Mode => _proto.Mode;
        public bool IsPublic => _proto.IsPublic;
        public string SenderUsername => _proto.SenderUsername;
        public string SenderDisplayName => _proto.SenderDisplayName;
        public long TopicId => _proto.TopicId;
    }
}
