// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageButtonClickedResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.MessageButtonClicked _proto;
        internal MessageButtonClickedResponse(global::Mezon.Net.Internal.Realtime.MessageButtonClicked proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.MessageButtonClicked Proto => _proto;

        public long MessageId => _proto.MessageId;
        public long ChannelId => _proto.ChannelId;
        public string ButtonId => _proto.ButtonId;
        public long SenderId => _proto.SenderId;
        public long UserId => _proto.UserId;
        public string ExtraData => _proto.ExtraData;
    }
}
