// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageAttachmentResponse
    {
        private readonly global::Mezon.Net.Internal.Api.MessageAttachment _proto;
        internal MessageAttachmentResponse(global::Mezon.Net.Internal.Api.MessageAttachment proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MessageAttachment Proto => _proto;

        public string Filename => _proto.Filename;
        public int Size => _proto.Size;
        public string Url => _proto.Url;
        public string Filetype => _proto.Filetype;
        public int Width => _proto.Width;
        public int Height => _proto.Height;
        public string Thumbnail => _proto.Thumbnail;
        public int Duration => _proto.Duration;
    }
}
