// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MessageRefData
    {
        private readonly global::Mezon.Net.Internal.Api.MessageRef _proto;
        internal MessageRefData(global::Mezon.Net.Internal.Api.MessageRef proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MessageRef Proto => _proto;

        public long MessageId => _proto.MessageId;
        public long MessageRefId => _proto.MessageRefId;
        public string Content => _proto.Content;
        public bool HasAttachment => _proto.HasAttachment;
        public int RefType => _proto.RefType;
        public long MessageSenderId => _proto.MessageSenderId;
        public string MessageSenderUsername => _proto.MessageSenderUsername;
        public string MessageSenderAvatar => _proto.MessageSenderAvatar;
        public string MessageSenderClanNick => _proto.MessageSenderClanNick;
        public string MessageSenderDisplayName => _proto.MessageSenderDisplayName;
    }
}
