// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MezonOauthClientResponse
    {
        private readonly global::Mezon.Net.Internal.Api.MezonOauthClient _proto;
        internal MezonOauthClientResponse(global::Mezon.Net.Internal.Api.MezonOauthClient proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MezonOauthClient Proto => _proto;

        public string AccessTokenStrategy => _proto.AccessTokenStrategy;
        public ProtoListView<string> AllowedCorsOrigins => ProtoListView<string>.FromRepeated(_proto.AllowedCorsOrigins);
        public ProtoListView<string> Audience => ProtoListView<string>.FromRepeated(_proto.Audience);
        public string AuthorizationCodeGrantAccessTokenLifespan => _proto.AuthorizationCodeGrantAccessTokenLifespan;
        public string AuthorizationCodeGrantIdTokenLifespan => _proto.AuthorizationCodeGrantIdTokenLifespan;
        public string AuthorizationCodeGrantRefreshTokenLifespan => _proto.AuthorizationCodeGrantRefreshTokenLifespan;
        public bool BackchannelLogoutSessionRequired => _proto.BackchannelLogoutSessionRequired;
        public string BackchannelLogoutUri => _proto.BackchannelLogoutUri;
        public string ClientCredentialsGrantAccessTokenLifespan => _proto.ClientCredentialsGrantAccessTokenLifespan;
        public string ClientId => _proto.ClientId;
        public string ClientName => _proto.ClientName;
        public string ClientSecret => _proto.ClientSecret;
        public int ClientSecretExpiresAt => _proto.ClientSecretExpiresAt;
        public string ClientUri => _proto.ClientUri;
        public ProtoListView<string> Contacts => ProtoListView<string>.FromRepeated(_proto.Contacts);
        public uint CreatedAtSeconds => _proto.CreatedAtSeconds;
        public bool FrontchannelLogoutSessionRequired => _proto.FrontchannelLogoutSessionRequired;
        public string FrontchannelLogoutUri => _proto.FrontchannelLogoutUri;
        public ProtoListView<string> GrantTypes => ProtoListView<string>.FromRepeated(_proto.GrantTypes);
        public string ImplicitGrantAccessTokenLifespan => _proto.ImplicitGrantAccessTokenLifespan;
        public string ImplicitGrantIdTokenLifespan => _proto.ImplicitGrantIdTokenLifespan;
        public ProtoListView<string> Jwks => ProtoListView<string>.FromRepeated(_proto.Jwks);
        public string JwksUri => _proto.JwksUri;
        public string JwtBearerGrantAccessTokenLifespan => _proto.JwtBearerGrantAccessTokenLifespan;
        public string LogoUri => _proto.LogoUri;
        public string Owner => _proto.Owner;
        public string PolicyUri => _proto.PolicyUri;
        public ProtoListView<string> PostLogoutRedirectUris => ProtoListView<string>.FromRepeated(_proto.PostLogoutRedirectUris);
        public ProtoListView<string> RedirectUris => ProtoListView<string>.FromRepeated(_proto.RedirectUris);
        public string RefreshTokenGrantAccessTokenLifespan => _proto.RefreshTokenGrantAccessTokenLifespan;
        public string RefreshTokenGrantIdTokenLifespan => _proto.RefreshTokenGrantIdTokenLifespan;
        public string RefreshTokenGrantRefreshTokenLifespan => _proto.RefreshTokenGrantRefreshTokenLifespan;
        public string RegistrationAccessToken => _proto.RegistrationAccessToken;
        public string RegistrationClientUri => _proto.RegistrationClientUri;
        public string RequestObjectSigningAlg => _proto.RequestObjectSigningAlg;
        public ProtoListView<string> RequestUris => ProtoListView<string>.FromRepeated(_proto.RequestUris);
        public ProtoListView<string> ResponseTypes => ProtoListView<string>.FromRepeated(_proto.ResponseTypes);
        public string Scope => _proto.Scope;
        public string SectorIdentifierUri => _proto.SectorIdentifierUri;
        public bool SkipConsent => _proto.SkipConsent;
        public bool SkipLogoutConsent => _proto.SkipLogoutConsent;
        public string SubjectType => _proto.SubjectType;
        public string TokenEndpointAuthMethod => _proto.TokenEndpointAuthMethod;
        public string TokenEndpointAuthSigningAlg => _proto.TokenEndpointAuthSigningAlg;
        public string TosUri => _proto.TosUri;
        public uint UpdatedAtSeconds => _proto.UpdatedAtSeconds;
        public string UserinfoSignedResponseAlg => _proto.UserinfoSignedResponseAlg;
    }
}
