// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MultipartUploadAttachmentResponse
    {
        private readonly global::Mezon.Net.Internal.Api.MultipartUploadAttachment _proto;
        internal MultipartUploadAttachmentResponse(global::Mezon.Net.Internal.Api.MultipartUploadAttachment proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MultipartUploadAttachment Proto => _proto;

        public string Filename => _proto.Filename;
        public ProtoListView<string> Urls => ProtoListView<string>.FromRepeated(_proto.Urls);
        public string UploadId => _proto.UploadId;
    }
}
