// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct MutedChannelListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.MutedChannelList _proto;
        internal MutedChannelListResponse(global::Mezon.Net.Internal.Api.MutedChannelList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.MutedChannelList Proto => _proto;

        public ProtoListView<long> MutedList => ProtoListView<long>.FromRepeated(_proto.MutedList);
    }
}
