// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationResponse
    {
        private readonly global::Mezon.Net.Internal.Api.Notification _proto;
        internal NotificationResponse(global::Mezon.Net.Internal.Api.Notification proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.Notification Proto => _proto;

        public long Id => _proto.Id;
        public string Subject => _proto.Subject;
        public byte[] Content => _proto.Content.ToByteArray();
        public int Code => _proto.Code;
        public long SenderId => _proto.SenderId;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public bool Persistent => _proto.Persistent;
        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public int ChannelType => _proto.ChannelType;
        public string AvatarUrl => _proto.AvatarUrl;
        public ChannelDescriptionResponse Channel => new ChannelDescriptionResponse(_proto.Channel);
        public long TopicId => _proto.TopicId;
        public int Category => _proto.Category;
    }
}
