// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationChannelCategorySettingData
    {
        private readonly global::Mezon.Net.Internal.Api.NotificationChannelCategorySetting _proto;
        internal NotificationChannelCategorySettingData(global::Mezon.Net.Internal.Api.NotificationChannelCategorySetting proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.NotificationChannelCategorySetting Proto => _proto;

        public long Id => _proto.Id;
        public string ChannelCategoryLabel => _proto.ChannelCategoryLabel;
        public int NotificationSettingType => _proto.NotificationSettingType;
        public string ChannelCategoryTitle => _proto.ChannelCategoryTitle;
        public int Action => _proto.Action;
    }
}
