// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationListData
    {
        private readonly global::Mezon.Net.Internal.Api.NotificationList _proto;
        internal NotificationListData(global::Mezon.Net.Internal.Api.NotificationList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.NotificationList Proto => _proto;

        public ProtoListView<NotificationData> Notifications => ProtoListView<NotificationData>.FromRepeated(_proto.Notifications, x => new NotificationData(x));
        public string CacheableCursor => _proto.CacheableCursor;
    }
}
