// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationChannelCategorySettingListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.NotificationChannelCategorySettingList _proto;
        internal NotificationChannelCategorySettingListResponse(global::Mezon.Net.Internal.Api.NotificationChannelCategorySettingList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.NotificationChannelCategorySettingList Proto => _proto;

        public ProtoListView<NotificationChannelCategorySettingResponse> NotificationChannelCategorySettingsList => ProtoListView<NotificationChannelCategorySettingResponse>.FromRepeated(_proto.NotificationChannelCategorySettingsList, x => new NotificationChannelCategorySettingResponse(x));
    }
}
