// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationsResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.Notifications _proto;
        internal NotificationsResponse(global::Mezon.Net.Internal.Realtime.Notifications proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.Notifications Proto => _proto;

        public ProtoListView<NotificationResponse> Notifications => ProtoListView<NotificationResponse>.FromRepeated(_proto.Notifications_, x => new NotificationResponse(x));
    }
}
