// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationChannelCategorySettingListData
    {
        private readonly global::Mezon.Net.Internal.Api.NotificationChannelCategorySettingList _proto;
        internal NotificationChannelCategorySettingListData(global::Mezon.Net.Internal.Api.NotificationChannelCategorySettingList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.NotificationChannelCategorySettingList Proto => _proto;

        public ProtoListView<NotificationChannelCategorySettingData> NotificationChannelCategorySettingsList => ProtoListView<NotificationChannelCategorySettingData>.FromRepeated(_proto.NotificationChannelCategorySettingsList, x => new NotificationChannelCategorySettingData(x));
    }
}
