// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationUserChannelData
    {
        private readonly global::Mezon.Net.Internal.Api.NotificationUserChannel _proto;
        internal NotificationUserChannelData(global::Mezon.Net.Internal.Api.NotificationUserChannel proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.NotificationUserChannel Proto => _proto;

        public long Id => _proto.Id;
        public int NotificationSettingType => _proto.NotificationSettingType;
        public int TimeMuteSeconds => _proto.TimeMuteSeconds;
        public int Active => _proto.Active;
        public long ChannelId => _proto.ChannelId;
    }
}
