// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationSettingResponse
    {
        private readonly global::Mezon.Net.Internal.Api.NotificationSetting _proto;
        internal NotificationSettingResponse(global::Mezon.Net.Internal.Api.NotificationSetting proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.NotificationSetting Proto => _proto;

        public long Id => _proto.Id;
        public int NotificationSettingType => _proto.NotificationSettingType;
    }
}
