// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct NotificationListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.NotificationList _proto;
        internal NotificationListResponse(global::Mezon.Net.Internal.Api.NotificationList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.NotificationList Proto => _proto;

        public ProtoListView<NotificationResponse> Notifications => ProtoListView<NotificationResponse>.FromRepeated(_proto.Notifications, x => new NotificationResponse(x));
        public string CacheableCursor => _proto.CacheableCursor;
    }
}
