// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct OnboardingItemData
    {
        private readonly global::Mezon.Net.Internal.Api.OnboardingItem _proto;
        internal OnboardingItemData(global::Mezon.Net.Internal.Api.OnboardingItem proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.OnboardingItem Proto => _proto;

        public long Id => _proto.Id;
        public long ClanId => _proto.ClanId;
        public int GuideType => _proto.GuideType;
        public int TaskType => _proto.TaskType;
        public long ChannelId => _proto.ChannelId;
        public string Title => _proto.Title;
        public string Content => _proto.Content;
        public string ImageUrl => _proto.ImageUrl;
        public ProtoListView<OnboardingAnswerData> Answers => ProtoListView<OnboardingAnswerData>.FromRepeated(_proto.Answers, x => new OnboardingAnswerData(x));
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
    }
}
