// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct OnboardingStepsResponse
    {
        private readonly global::Mezon.Net.Internal.Api.OnboardingSteps _proto;
        internal OnboardingStepsResponse(global::Mezon.Net.Internal.Api.OnboardingSteps proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.OnboardingSteps Proto => _proto;

        public long Id => _proto.Id;
        public long UserId => _proto.UserId;
        public long ClanId => _proto.ClanId;
        public int OnboardingStep => _proto.OnboardingStep;
    }
}
