// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct OnboardingAnswerData
    {
        private readonly global::Mezon.Net.Internal.Api.OnboardingAnswer _proto;
        internal OnboardingAnswerData(global::Mezon.Net.Internal.Api.OnboardingAnswer proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.OnboardingAnswer Proto => _proto;

        public string Title => _proto.Title;
        public string Description => _proto.Description;
        public string Emoji => _proto.Emoji;
        public string ImageUrl => _proto.ImageUrl;
    }
}
