// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PermissionRoleChannelResponse
    {
        private readonly global::Mezon.Net.Internal.Api.PermissionRoleChannel _proto;
        internal PermissionRoleChannelResponse(global::Mezon.Net.Internal.Api.PermissionRoleChannel proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PermissionRoleChannel Proto => _proto;

        public long PermissionId => _proto.PermissionId;
        public bool Active => _proto.Active;
    }
}
