// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PermissionRoleChannelListEventResponse
    {
        private readonly global::Mezon.Net.Internal.Api.PermissionRoleChannelListEventResponse _proto;
        internal PermissionRoleChannelListEventResponse(global::Mezon.Net.Internal.Api.PermissionRoleChannelListEventResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PermissionRoleChannelListEventResponse Proto => _proto;

        public long RoleId => _proto.RoleId;
        public long ChannelId => _proto.ChannelId;
        public long UserId => _proto.UserId;
        public ProtoListView<PermissionRoleChannelResponse> PermissionRoleChannel => ProtoListView<PermissionRoleChannelResponse>.FromRepeated(_proto.PermissionRoleChannel, x => new PermissionRoleChannelResponse(x));
    }
}
