// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PermissionListData
    {
        private readonly global::Mezon.Net.Internal.Api.PermissionList _proto;
        internal PermissionListData(global::Mezon.Net.Internal.Api.PermissionList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PermissionList Proto => _proto;

        public ProtoListView<PermissionData> Permissions => ProtoListView<PermissionData>.FromRepeated(_proto.Permissions, x => new PermissionData(x));
        public int MaxLevelPermission => _proto.MaxLevelPermission;
    }
}
