// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PermissionData
    {
        private readonly global::Mezon.Net.Internal.Api.Permission _proto;
        internal PermissionData(global::Mezon.Net.Internal.Api.Permission proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.Permission Proto => _proto;

        public long Id => _proto.Id;
        public string Title => _proto.Title;
        public string Slug => _proto.Slug;
        public string Description => _proto.Description;
        public int Active => _proto.Active;
        public int Scope => _proto.Scope;
        public int Level => _proto.Level;
    }
}
