// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PinMessagesListData
    {
        private readonly global::Mezon.Net.Internal.Api.PinMessagesList _proto;
        internal PinMessagesListData(global::Mezon.Net.Internal.Api.PinMessagesList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PinMessagesList Proto => _proto;

        public ProtoListView<PinMessageData> PinMessagesList => ProtoListView<PinMessageData>.FromRepeated(_proto.PinMessagesList_, x => new PinMessageData(x));
    }
}
