// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PinMessageData
    {
        private readonly global::Mezon.Net.Internal.Api.PinMessage _proto;
        internal PinMessageData(global::Mezon.Net.Internal.Api.PinMessage proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PinMessage Proto => _proto;

        public long Id => _proto.Id;
        public long MessageId => _proto.MessageId;
        public long ChannelId => _proto.ChannelId;
        public long SenderId => _proto.SenderId;
        public string Content => _proto.Content;
        public string Username => _proto.Username;
        public string Avatar => _proto.Avatar;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public byte[] Attachment => _proto.Attachment.ToByteArray();
    }
}
