// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PinMessagesListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.PinMessagesList _proto;
        internal PinMessagesListResponse(global::Mezon.Net.Internal.Api.PinMessagesList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PinMessagesList Proto => _proto;

        public ProtoListView<PinMessageResponse> PinMessagesList => ProtoListView<PinMessageResponse>.FromRepeated(_proto.PinMessagesList_, x => new PinMessageResponse(x));
    }
}
