// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PollAnswerData
    {
        private readonly global::Mezon.Net.Internal.Api.PollAnswer _proto;
        internal PollAnswerData(global::Mezon.Net.Internal.Api.PollAnswer proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PollAnswer Proto => _proto;

        public int Index => _proto.Index;
        public string Label => _proto.Label;
    }
}
