// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PollVoterDetailData
    {
        private readonly global::Mezon.Net.Internal.Api.PollVoterDetail _proto;
        internal PollVoterDetailData(global::Mezon.Net.Internal.Api.PollVoterDetail proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PollVoterDetail Proto => _proto;

        public int AnswerIndex => _proto.AnswerIndex;
        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
    }
}
