// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PongResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.Pong _proto;
        internal PongResponse(global::Mezon.Net.Internal.Realtime.Pong proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.Pong Proto => _proto;

    }
}
