// <auto-generated />
#nullable enable
using System;
using System.Collections;
using System.Collections.Generic;
using Google.Protobuf.Collections;

namespace Mezon.Net.Models
{
    /// <summary>
    ///     Lightweight read-only view over protobuf repeated fields. Nested projections are materialized once.
    /// </summary>
    public readonly struct ProtoListView<TData> : IReadOnlyList<TData>
    {
        private readonly IReadOnlyList<TData> _items;

        internal ProtoListView(IReadOnlyList<TData> items) => _items = items ?? Array.Empty<TData>();

        public int Count => _items.Count;
        public TData this[int index] => _items[index];

        public IEnumerator<TData> GetEnumerator() => _items.GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();

        internal static ProtoListView<TData> FromRepeated(RepeatedField<TData> field)
            => field is null || field.Count == 0
                ? new ProtoListView<TData>(Array.Empty<TData>())
                : new ProtoListView<TData>(field);

        internal static ProtoListView<TData> FromRepeated<TProto>(
            RepeatedField<TProto> field,
            Func<TProto, TData> factory)
        {
            if (field is null || field.Count == 0)
                return new ProtoListView<TData>(Array.Empty<TData>());
            var arr = new TData[field.Count];
            for (var i = 0; i < field.Count; i++)
                arr[i] = factory(field[i]);
            return new ProtoListView<TData>(arr);
        }
    }
}
