// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct PubKeyResponse
    {
        private readonly global::Mezon.Net.Internal.Api.PubKey _proto;
        internal PubKeyResponse(global::Mezon.Net.Internal.Api.PubKey proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.PubKey Proto => _proto;

        public byte[] Encr => _proto.Encr.ToByteArray();
        public byte[] Sign => _proto.Sign.ToByteArray();
    }
}
