// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct QuickMenuAccessListData
    {
        private readonly global::Mezon.Net.Internal.Api.QuickMenuAccessList _proto;
        internal QuickMenuAccessListData(global::Mezon.Net.Internal.Api.QuickMenuAccessList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.QuickMenuAccessList Proto => _proto;

        public ProtoListView<QuickMenuAccessData> ListMenus => ProtoListView<QuickMenuAccessData>.FromRepeated(_proto.ListMenus, x => new QuickMenuAccessData(x));
    }
}
