// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct QuickMenuAccessListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.QuickMenuAccessList _proto;
        internal QuickMenuAccessListResponse(global::Mezon.Net.Internal.Api.QuickMenuAccessList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.QuickMenuAccessList Proto => _proto;

        public ProtoListView<QuickMenuAccessResponse> ListMenus => ProtoListView<QuickMenuAccessResponse>.FromRepeated(_proto.ListMenus, x => new QuickMenuAccessResponse(x));
    }
}
