// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct QuickMenuAccessResponse
    {
        private readonly global::Mezon.Net.Internal.Api.QuickMenuAccess _proto;
        internal QuickMenuAccessResponse(global::Mezon.Net.Internal.Api.QuickMenuAccess proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.QuickMenuAccess Proto => _proto;

        public long Id => _proto.Id;
        public long BotId => _proto.BotId;
        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public string MenuName => _proto.MenuName;
        public string Background => _proto.Background;
        public string ActionMsg => _proto.ActionMsg;
        public int MenuType => _proto.MenuType;
    }
}
