// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RegistFcmDeviceTokenResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.RegistFcmDeviceTokenResponse _proto;
        internal RegistFcmDeviceTokenResponseData(global::Mezon.Net.Internal.Api.RegistFcmDeviceTokenResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.RegistFcmDeviceTokenResponse Proto => _proto;

        public string Token => _proto.Token;
        public string DeviceId => _proto.DeviceId;
        public string Platform => _proto.Platform;
    }
}
