// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.RoleEvent _proto;
        internal RoleEventResponse(global::Mezon.Net.Internal.Realtime.RoleEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.RoleEvent Proto => _proto;

        public RoleResponse Role => new RoleResponse(_proto.Role);
        public int Status => _proto.Status;
        public long UserId => _proto.UserId;
        public ProtoListView<long> UserAddIds => ProtoListView<long>.FromRepeated(_proto.UserAddIds);
        public ProtoListView<long> UserRemoveIds => ProtoListView<long>.FromRepeated(_proto.UserRemoveIds);
        public ProtoListView<long> ActivePermissionIds => ProtoListView<long>.FromRepeated(_proto.ActivePermissionIds);
        public ProtoListView<long> RemovePermissionIds => ProtoListView<long>.FromRepeated(_proto.RemovePermissionIds);
    }
}
