// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleListEventResponse
    {
        private readonly global::Mezon.Net.Internal.Api.RoleListEventResponse _proto;
        internal RoleListEventResponse(global::Mezon.Net.Internal.Api.RoleListEventResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.RoleListEventResponse Proto => _proto;

        public int Limit => _proto.Limit;
        public int State => _proto.State;
        public string Cursor => _proto.Cursor;
        public long ClanId => _proto.ClanId;
        public RoleListResponse Roles => new RoleListResponse(_proto.Roles);
    }
}
