// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleData
    {
        private readonly global::Mezon.Net.Internal.Api.Role _proto;
        internal RoleData(global::Mezon.Net.Internal.Api.Role proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.Role Proto => _proto;

        public long Id => _proto.Id;
        public string Title => _proto.Title;
        public string Color => _proto.Color;
        public string RoleIcon => _proto.RoleIcon;
        public string Slug => _proto.Slug;
        public string Description => _proto.Description;
        public long CreatorId => _proto.CreatorId;
        public long ClanId => _proto.ClanId;
        public int Active => _proto.Active;
        public int DisplayOnline => _proto.DisplayOnline;
        public int AllowMention => _proto.AllowMention;
        public RoleUserListData RoleUserList => new RoleUserListData(_proto.RoleUserList);
        public PermissionListData PermissionList => new PermissionListData(_proto.PermissionList);
        public int RoleChannelActive => _proto.RoleChannelActive;
        public ProtoListView<long> ChannelIds => ProtoListView<long>.FromRepeated(_proto.ChannelIds);
        public int MaxLevelPermission => _proto.MaxLevelPermission;
        public int OrderRole => _proto.OrderRole;
    }
}
