// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleListData
    {
        private readonly global::Mezon.Net.Internal.Api.RoleList _proto;
        internal RoleListData(global::Mezon.Net.Internal.Api.RoleList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.RoleList Proto => _proto;

        public ProtoListView<RoleData> Roles => ProtoListView<RoleData>.FromRepeated(_proto.Roles, x => new RoleData(x));
        public int MaxLevelPermission => _proto.MaxLevelPermission;
    }
}
