// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleUserListData
    {
        private readonly global::Mezon.Net.Internal.Api.RoleUserList _proto;
        internal RoleUserListData(global::Mezon.Net.Internal.Api.RoleUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.RoleUserList Proto => _proto;

        public ProtoListView<RoleUserData> RoleUsers => ProtoListView<RoleUserData>.FromRepeated(_proto.RoleUsers, x => new RoleUserData(x));
        public string Cursor => _proto.Cursor;
    }
}
