// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleUserData
    {
        private readonly global::Mezon.Net.Internal.Api.RoleUserList.Types.RoleUser _proto;
        internal RoleUserData(global::Mezon.Net.Internal.Api.RoleUserList.Types.RoleUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.RoleUserList.Types.RoleUser Proto => _proto;

        public long Id => _proto.Id;
        public string Username => _proto.Username;
        public string DisplayName => _proto.DisplayName;
        public string AvatarUrl => _proto.AvatarUrl;
        public string LangTag => _proto.LangTag;
        public string Location => _proto.Location;
        public bool Online => _proto.Online;
    }
}
