// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleAssignedEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.RoleAssignedEvent _proto;
        internal RoleAssignedEventResponse(global::Mezon.Net.Internal.Realtime.RoleAssignedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.RoleAssignedEvent Proto => _proto;

        public string ClanId => _proto.ClanId;
        public long RoleId => _proto.RoleId;
        public ProtoListView<long> UserIdsAssigned => ProtoListView<long>.FromRepeated(_proto.UserIdsAssigned);
        public ProtoListView<long> UserIdsRemoved => ProtoListView<long>.FromRepeated(_proto.UserIdsRemoved);
    }
}
