// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RoleListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.RoleList _proto;
        internal RoleListResponse(global::Mezon.Net.Internal.Api.RoleList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.RoleList Proto => _proto;

        public ProtoListView<RoleResponse> Roles => ProtoListView<RoleResponse>.FromRepeated(_proto.Roles, x => new RoleResponse(x));
        public int MaxLevelPermission => _proto.MaxLevelPermission;
    }
}
