// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct RpcResponse
    {
        private readonly global::Mezon.Net.Internal.Api.Rpc _proto;
        internal RpcResponse(global::Mezon.Net.Internal.Api.Rpc proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.Rpc Proto => _proto;

        public string Id => _proto.Id;
        public string Payload => _proto.Payload;
        public string HttpKey => _proto.HttpKey;
    }
}
