// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct ScreenShareEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.ScreenShareEvent _proto;
        internal ScreenShareEventResponse(global::Mezon.Net.Internal.Realtime.ScreenShareEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.ScreenShareEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long VoiceChannelId => _proto.VoiceChannelId;
        public long UserId => _proto.UserId;
        public bool IsSharing => _proto.IsSharing;
    }
}
