// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SdTopicResponse
    {
        private readonly global::Mezon.Net.Internal.Api.SdTopic _proto;
        internal SdTopicResponse(global::Mezon.Net.Internal.Api.SdTopic proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.SdTopic Proto => _proto;

        public long Id => _proto.Id;
        public long CreatorId => _proto.CreatorId;
        public long MessageId => _proto.MessageId;
        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public int Status => _proto.Status;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
        public string Content => _proto.Content;
        public ChannelMessageHeaderResponse LastSentMessage => new ChannelMessageHeaderResponse(_proto.LastSentMessage);
    }
}
