// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SdTopicListData
    {
        private readonly global::Mezon.Net.Internal.Api.SdTopicList _proto;
        internal SdTopicListData(global::Mezon.Net.Internal.Api.SdTopicList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.SdTopicList Proto => _proto;

        public int Count => _proto.Count;
        public ProtoListView<SdTopicData> Topics => ProtoListView<SdTopicData>.FromRepeated(_proto.Topics, x => new SdTopicData(x));
    }
}
