// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SearchMessageDocumentData
    {
        private readonly global::Mezon.Net.Internal.Api.SearchMessageDocument _proto;
        internal SearchMessageDocumentData(global::Mezon.Net.Internal.Api.SearchMessageDocument proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.SearchMessageDocument Proto => _proto;

        public string MessageId => _proto.MessageId;
        public string ChannelId => _proto.ChannelId;
        public string ClanId => _proto.ClanId;
        public string SenderId => _proto.SenderId;
        public string Content => _proto.Content;
        public string Mentions => _proto.Mentions;
        public string Reactions => _proto.Reactions;
        public string Attachments => _proto.Attachments;
        public string References => _proto.References;
        public string CreateTime => _proto.CreateTime;
        public string UpdateTime => _proto.UpdateTime;
        public string ChannelLabel => _proto.ChannelLabel;
        public int ChannelType => _proto.ChannelType;
        public string ClanName => _proto.ClanName;
        public string Username => _proto.Username;
        public string DisplayName => _proto.DisplayName;
        public string AvatarUrl => _proto.AvatarUrl;
    }
}
