// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SearchMentionUsersResponse
    {
        private readonly global::Mezon.Net.Internal.Api.SearchMentionUsersResponse _proto;
        internal SearchMentionUsersResponse(global::Mezon.Net.Internal.Api.SearchMentionUsersResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.SearchMentionUsersResponse Proto => _proto;

        public ProtoListView<MentionUserResponse> Users => ProtoListView<MentionUserResponse>.FromRepeated(_proto.Users, x => new MentionUserResponse(x));
    }
}
