// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusData
    {
        private readonly global::Mezon.Net.Internal.Realtime.Status _proto;
        internal StatusData(global::Mezon.Net.Internal.Realtime.Status proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.Status Proto => _proto;

        public ProtoListView<UserPresenceData> Presences => ProtoListView<UserPresenceData>.FromRepeated(_proto.Presences, x => new UserPresenceData(x));
    }
}
