// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusUnfollowResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.StatusUnfollow _proto;
        internal StatusUnfollowResponse(global::Mezon.Net.Internal.Realtime.StatusUnfollow proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StatusUnfollow Proto => _proto;

        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
    }
}
