// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusPresenceEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.StatusPresenceEvent _proto;
        internal StatusPresenceEventResponse(global::Mezon.Net.Internal.Realtime.StatusPresenceEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StatusPresenceEvent Proto => _proto;

        public ProtoListView<UserPresenceResponse> Joins => ProtoListView<UserPresenceResponse>.FromRepeated(_proto.Joins, x => new UserPresenceResponse(x));
        public ProtoListView<UserPresenceResponse> Leaves => ProtoListView<UserPresenceResponse>.FromRepeated(_proto.Leaves, x => new UserPresenceResponse(x));
    }
}
