// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusFollowData
    {
        private readonly global::Mezon.Net.Internal.Realtime.StatusFollow _proto;
        internal StatusFollowData(global::Mezon.Net.Internal.Realtime.StatusFollow proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StatusFollow Proto => _proto;

        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
        public ProtoListView<string> Usernames => ProtoListView<string>.FromRepeated(_proto.Usernames);
    }
}
