// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusPresenceEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.StatusPresenceEvent _proto;
        internal StatusPresenceEventData(global::Mezon.Net.Internal.Realtime.StatusPresenceEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StatusPresenceEvent Proto => _proto;

        public ProtoListView<UserPresenceData> Joins => ProtoListView<UserPresenceData>.FromRepeated(_proto.Joins, x => new UserPresenceData(x));
        public ProtoListView<UserPresenceData> Leaves => ProtoListView<UserPresenceData>.FromRepeated(_proto.Leaves, x => new UserPresenceData(x));
    }
}
