// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StatusUpdateData
    {
        private readonly global::Mezon.Net.Internal.Realtime.StatusUpdate _proto;
        internal StatusUpdateData(global::Mezon.Net.Internal.Realtime.StatusUpdate proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StatusUpdate Proto => _proto;

        public string Status => _proto.Status ?? "";
    }
}
