// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StickerListedResponse
    {
        private readonly global::Mezon.Net.Internal.Api.StickerListedResponse _proto;
        internal StickerListedResponse(global::Mezon.Net.Internal.Api.StickerListedResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.StickerListedResponse Proto => _proto;

        public ProtoListView<ClanStickerResponse> Stickers => ProtoListView<ClanStickerResponse>.FromRepeated(_proto.Stickers, x => new ClanStickerResponse(x));
    }
}
