// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StickerListedResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.StickerListedResponse _proto;
        internal StickerListedResponseData(global::Mezon.Net.Internal.Api.StickerListedResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.StickerListedResponse Proto => _proto;

        public ProtoListView<ClanStickerData> Stickers => ProtoListView<ClanStickerData>.FromRepeated(_proto.Stickers, x => new ClanStickerData(x));
    }
}
