// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamingChannelUserResponse
    {
        private readonly global::Mezon.Net.Internal.Api.StreamingChannelUser _proto;
        internal StreamingChannelUserResponse(global::Mezon.Net.Internal.Api.StreamingChannelUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.StreamingChannelUser Proto => _proto;

        public long Id => _proto.Id;
        public long UserId => _proto.UserId;
        public long ChannelId => _proto.ChannelId;
        public string Participant => _proto.Participant;
    }
}
