// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.Stream _proto;
        internal StreamResponse(global::Mezon.Net.Internal.Realtime.Stream proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.Stream Proto => _proto;

        public int Mode => _proto.Mode;
        public long ChannelId => _proto.ChannelId;
        public long ClanId => _proto.ClanId;
        public string Label => _proto.Label;
    }
}
