// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamPresenceEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.StreamPresenceEvent _proto;
        internal StreamPresenceEventResponse(global::Mezon.Net.Internal.Realtime.StreamPresenceEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StreamPresenceEvent Proto => _proto;

        public StreamResponse Stream => new StreamResponse(_proto.Stream);
        public ProtoListView<UserPresenceResponse> Joins => ProtoListView<UserPresenceResponse>.FromRepeated(_proto.Joins, x => new UserPresenceResponse(x));
        public ProtoListView<UserPresenceResponse> Leaves => ProtoListView<UserPresenceResponse>.FromRepeated(_proto.Leaves, x => new UserPresenceResponse(x));
    }
}
