// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamDataData
    {
        private readonly global::Mezon.Net.Internal.Realtime.StreamData _proto;
        internal StreamDataData(global::Mezon.Net.Internal.Realtime.StreamData proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StreamData Proto => _proto;

        public StreamData Stream => new StreamData(_proto.Stream);
        public UserPresenceData Sender => new UserPresenceData(_proto.Sender);
        public string Data => _proto.Data;
        public bool Reliable => _proto.Reliable;
    }
}
