// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamDataResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.StreamData _proto;
        internal StreamDataResponse(global::Mezon.Net.Internal.Realtime.StreamData proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.StreamData Proto => _proto;

        public StreamResponse Stream => new StreamResponse(_proto.Stream);
        public UserPresenceResponse Sender => new UserPresenceResponse(_proto.Sender);
        public string Data => _proto.Data;
        public bool Reliable => _proto.Reliable;
    }
}
