// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamHttpCallbackResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.StreamHttpCallbackResponse _proto;
        internal StreamHttpCallbackResponseData(global::Mezon.Net.Internal.Api.StreamHttpCallbackResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.StreamHttpCallbackResponse Proto => _proto;

        public int Code => _proto.Code;
        public string Msg => _proto.Msg;
    }
}
