// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamingChannelUserListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.StreamingChannelUserList _proto;
        internal StreamingChannelUserListResponse(global::Mezon.Net.Internal.Api.StreamingChannelUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.StreamingChannelUserList Proto => _proto;

        public ProtoListView<StreamingChannelUserResponse> StreamingChannelUsers => ProtoListView<StreamingChannelUserResponse>.FromRepeated(_proto.StreamingChannelUsers, x => new StreamingChannelUserResponse(x));
    }
}
