// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct StreamingChannelUserListData
    {
        private readonly global::Mezon.Net.Internal.Api.StreamingChannelUserList _proto;
        internal StreamingChannelUserListData(global::Mezon.Net.Internal.Api.StreamingChannelUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.StreamingChannelUserList Proto => _proto;

        public ProtoListView<StreamingChannelUserData> StreamingChannelUsers => ProtoListView<StreamingChannelUserData>.FromRepeated(_proto.StreamingChannelUsers, x => new StreamingChannelUserData(x));
    }
}
