// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct SystemMessageData
    {
        private readonly global::Mezon.Net.Internal.Api.SystemMessage _proto;
        internal SystemMessageData(global::Mezon.Net.Internal.Api.SystemMessage proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.SystemMessage Proto => _proto;

        public long Id => _proto.Id;
        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public string WelcomeRandom => _proto.WelcomeRandom;
        public string WelcomeSticker => _proto.WelcomeSticker;
        public string BoostMessage => _proto.BoostMessage;
        public string SetupTips => _proto.SetupTips;
        public bool HideAuditLog => _proto.HideAuditLog;
    }
}
