// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct TopicInMessageEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.TopicInMessageEvent _proto;
        internal TopicInMessageEventResponse(global::Mezon.Net.Internal.Realtime.TopicInMessageEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.TopicInMessageEvent Proto => _proto;

        public long MessageId => _proto.MessageId;
        public int Rpl => _proto.Rpl;
        public long Lsnt => _proto.Lsnt;
        public string TpId => _proto.TpId;
    }
}
