// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateChannelTimelineResponse
    {
        private readonly global::Mezon.Net.Internal.Api.UpdateChannelTimelineResponse _proto;
        internal UpdateChannelTimelineResponse(global::Mezon.Net.Internal.Api.UpdateChannelTimelineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.UpdateChannelTimelineResponse Proto => _proto;

        public ChannelTimelineResponse Event => new ChannelTimelineResponse(_proto.Event);
    }
}
