// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UpdateChannelTimelineResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.UpdateChannelTimelineResponse _proto;
        internal UpdateChannelTimelineResponseData(global::Mezon.Net.Internal.Api.UpdateChannelTimelineResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.UpdateChannelTimelineResponse Proto => _proto;

        public ChannelTimelineData Event => new ChannelTimelineData(_proto.Event);
    }
}
