// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UploadAttachmentBatchData
    {
        private readonly global::Mezon.Net.Internal.Api.UploadAttachmentBatch _proto;
        internal UploadAttachmentBatchData(global::Mezon.Net.Internal.Api.UploadAttachmentBatch proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.UploadAttachmentBatch Proto => _proto;

        public ProtoListView<UploadAttachmentData> UploadedFiles => ProtoListView<UploadAttachmentData>.FromRepeated(_proto.UploadedFiles, x => new UploadAttachmentData(x));
    }
}
