// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UploadAttachmentData
    {
        private readonly global::Mezon.Net.Internal.Api.UploadAttachment _proto;
        internal UploadAttachmentData(global::Mezon.Net.Internal.Api.UploadAttachment proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.UploadAttachment Proto => _proto;

        public string Filename => _proto.Filename;
        public string Url => _proto.Url;
    }
}
