// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserChannelAddedResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.UserChannelAdded _proto;
        internal UserChannelAddedResponse(global::Mezon.Net.Internal.Realtime.UserChannelAdded proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.UserChannelAdded Proto => _proto;

        public ChannelDescriptionResponse ChannelDesc => new ChannelDescriptionResponse(_proto.ChannelDesc);
        public ProtoListView<UserProfileRedisResponse> Users => ProtoListView<UserProfileRedisResponse>.FromRepeated(_proto.Users, x => new UserProfileRedisResponse(x));
        public string Status => _proto.Status;
        public long ClanId => _proto.ClanId;
        public UserProfileRedisResponse Caller => new UserProfileRedisResponse(_proto.Caller);
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public int Active => _proto.Active;
    }
}
