// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserPubKeyData
    {
        private readonly global::Mezon.Net.Internal.Api.GetPubKeysResponse.Types.UserPubKey _proto;
        internal UserPubKeyData(global::Mezon.Net.Internal.Api.GetPubKeysResponse.Types.UserPubKey proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GetPubKeysResponse.Types.UserPubKey Proto => _proto;

        public long UserId => _proto.UserId;
        public PubKeyData PK => new PubKeyData(_proto.PK);
    }
}
