// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserData
    {
        private readonly global::Mezon.Net.Internal.Api.User _proto;
        internal UserData(global::Mezon.Net.Internal.Api.User proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.User Proto => _proto;

        public long Id => _proto.Id;
        public string Username => _proto.Username;
        public string DisplayName => _proto.DisplayName;
        public string AvatarUrl => _proto.AvatarUrl;
        public string LangTag => _proto.LangTag;
        public string Location => _proto.Location;
        public string Timezone => _proto.Timezone;
        public string UserStatus => _proto.UserStatus;
        public bool Online => _proto.Online;
        public string PhoneNumber => _proto.PhoneNumber;
        public int EdgeCount => _proto.EdgeCount;
        public uint CreateTimeSeconds => _proto.CreateTimeSeconds;
        public uint UpdateTimeSeconds => _proto.UpdateTimeSeconds;
        public string AboutMe => _proto.AboutMe;
        public uint JoinTimeSeconds => _proto.JoinTimeSeconds;
        public bool IsMobile => _proto.IsMobile;
        public uint DobSeconds => _proto.DobSeconds;
        public string MezonId => _proto.MezonId;
        public ProtoListView<string> ListNickNames => ProtoListView<string>.FromRepeated(_proto.ListNickNames);
        public string Status => _proto.Status;
    }
}
