// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserPermissionInChannelListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.UserPermissionInChannelListResponse _proto;
        internal UserPermissionInChannelListResponse(global::Mezon.Net.Internal.Api.UserPermissionInChannelListResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.UserPermissionInChannelListResponse Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long ChannelId => _proto.ChannelId;
        public PermissionListResponse Permissions => new PermissionListResponse(_proto.Permissions);
    }
}
