// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserPubKeyResponse
    {
        private readonly global::Mezon.Net.Internal.Api.GetPubKeysResponse.Types.UserPubKey _proto;
        internal UserPubKeyResponse(global::Mezon.Net.Internal.Api.GetPubKeysResponse.Types.UserPubKey proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.GetPubKeysResponse.Types.UserPubKey Proto => _proto;

        public long UserId => _proto.UserId;
        public PubKeyResponse PK => new PubKeyResponse(_proto.PK);
    }
}
