// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserPresenceData
    {
        private readonly global::Mezon.Net.Internal.Realtime.UserPresence _proto;
        internal UserPresenceData(global::Mezon.Net.Internal.Realtime.UserPresence proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.UserPresence Proto => _proto;

        public long UserId => _proto.UserId;
        public int SessionId => _proto.SessionId;
        public string Username => _proto.Username;
        public string Status => _proto.Status ?? "";
        public bool IsMobile => _proto.IsMobile;
        public string UserStatus => _proto.UserStatus;
    }
}
