// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserActivityResponse
    {
        private readonly global::Mezon.Net.Internal.Api.UserActivity _proto;
        internal UserActivityResponse(global::Mezon.Net.Internal.Api.UserActivity proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.UserActivity Proto => _proto;

        public long UserId => _proto.UserId;
        public string ActivityName => _proto.ActivityName;
        public int ActivityType => _proto.ActivityType;
        public string ActivityDescription => _proto.ActivityDescription;
        public uint StartTimeSeconds => _proto.StartTimeSeconds;
        public uint EndTimeSeconds => _proto.EndTimeSeconds;
        public long ApplicationId => _proto.ApplicationId;
        public int Status => _proto.Status;
    }
}
