// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserChannelRemovedResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.UserChannelRemoved _proto;
        internal UserChannelRemovedResponse(global::Mezon.Net.Internal.Realtime.UserChannelRemoved proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.UserChannelRemoved Proto => _proto;

        public long ChannelId => _proto.ChannelId;
        public ProtoListView<long> UserIds => ProtoListView<long>.FromRepeated(_proto.UserIds);
        public int ChannelType => _proto.ChannelType;
        public long ClanId => _proto.ClanId;
        public ProtoListView<int> BadgeCounts => ProtoListView<int>.FromRepeated(_proto.BadgeCounts);
    }
}
