// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserProfileRedisResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.UserProfileRedis _proto;
        internal UserProfileRedisResponse(global::Mezon.Net.Internal.Realtime.UserProfileRedis proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.UserProfileRedis Proto => _proto;

        public long UserId => _proto.UserId;
        public string Username => _proto.Username;
        public string Avatar => _proto.Avatar;
        public string DisplayName => _proto.DisplayName;
        public string UserStatus => _proto.UserStatus;
        public string Status => _proto.Status;
        public bool Online => _proto.Online;
        public ProtoListView<FCMTokensResponse> FcmTokens => ProtoListView<FCMTokensResponse>.FromRepeated(_proto.FcmTokens, x => new FCMTokensResponse(x));
        public ProtoListView<long> JoinedClans => ProtoListView<long>.FromRepeated(_proto.JoinedClans);
        public string AppToken => _proto.AppToken;
        public uint CreateTimeSecond => _proto.CreateTimeSecond;
        public string AppUrl => _proto.AppUrl;
        public bool IsBot => _proto.IsBot;
        public string VoipToken => _proto.VoipToken;
    }
}
