// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct UserStatusData
    {
        private readonly global::Mezon.Net.Internal.Api.UserStatus _proto;
        internal UserStatusData(global::Mezon.Net.Internal.Api.UserStatus proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.UserStatus Proto => _proto;

        public long UserId => _proto.UserId;
        public string Status => _proto.Status;
    }
}
