// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceJoinedEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.VoiceJoinedEvent _proto;
        internal VoiceJoinedEventResponse(global::Mezon.Net.Internal.Realtime.VoiceJoinedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.VoiceJoinedEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public string ClanName => _proto.ClanName;
        public string Id => _proto.Id;
        public string Participant => _proto.Participant;
        public long UserId => _proto.UserId;
        public string VoiceChannelLabel => _proto.VoiceChannelLabel;
        public long VoiceChannelId => _proto.VoiceChannelId;
        public string LastScreenshot => _proto.LastScreenshot;
    }
}
