// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceLeavedEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.VoiceLeavedEvent _proto;
        internal VoiceLeavedEventResponse(global::Mezon.Net.Internal.Realtime.VoiceLeavedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.VoiceLeavedEvent Proto => _proto;

        public string Id => _proto.Id;
        public long ClanId => _proto.ClanId;
        public long VoiceChannelId => _proto.VoiceChannelId;
        public long VoiceUserId => _proto.VoiceUserId;
    }
}
