// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceInteractiveEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.VoiceInteractiveEvent _proto;
        internal VoiceInteractiveEventResponse(global::Mezon.Net.Internal.Realtime.VoiceInteractiveEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.VoiceInteractiveEvent Proto => _proto;

        public long ClanId => _proto.ClanId;
        public long VoiceChannelId => _proto.VoiceChannelId;
        public long SenderId => _proto.SenderId;
        public long ReceiverId => _proto.ReceiverId;
        public int EventType => _proto.EventType;
        public string Params => _proto.Params;
    }
}
