// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceChannelUserData
    {
        private readonly global::Mezon.Net.Internal.Api.VoiceChannelUser _proto;
        internal VoiceChannelUserData(global::Mezon.Net.Internal.Api.VoiceChannelUser proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.VoiceChannelUser Proto => _proto;

        public ProtoListView<string> UserIds => ProtoListView<string>.FromRepeated(_proto.UserIds);
        public long ChannelId => _proto.ChannelId;
        public string RoomName => _proto.RoomName;
        public ProtoListView<string> ShareScreenIds => ProtoListView<string>.FromRepeated(_proto.ShareScreenIds);
    }
}
