// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceStartedEventData
    {
        private readonly global::Mezon.Net.Internal.Realtime.VoiceStartedEvent _proto;
        internal VoiceStartedEventData(global::Mezon.Net.Internal.Realtime.VoiceStartedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.VoiceStartedEvent Proto => _proto;

        public string Id => _proto.Id;
        public long ClanId => _proto.ClanId;
        public long VoiceChannelId => _proto.VoiceChannelId;
    }
}
