// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceChannelUserListResponse
    {
        private readonly global::Mezon.Net.Internal.Api.VoiceChannelUserList _proto;
        internal VoiceChannelUserListResponse(global::Mezon.Net.Internal.Api.VoiceChannelUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.VoiceChannelUserList Proto => _proto;

        public ProtoListView<VoiceChannelUserResponse> VoiceChannelUsers => ProtoListView<VoiceChannelUserResponse>.FromRepeated(_proto.VoiceChannelUsers, x => new VoiceChannelUserResponse(x));
    }
}
