// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceChannelUserListData
    {
        private readonly global::Mezon.Net.Internal.Api.VoiceChannelUserList _proto;
        internal VoiceChannelUserListData(global::Mezon.Net.Internal.Api.VoiceChannelUserList proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.VoiceChannelUserList Proto => _proto;

        public ProtoListView<VoiceChannelUserData> VoiceChannelUsers => ProtoListView<VoiceChannelUserData>.FromRepeated(_proto.VoiceChannelUsers, x => new VoiceChannelUserData(x));
    }
}
