// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VoiceEndedEventResponse
    {
        private readonly global::Mezon.Net.Internal.Realtime.VoiceEndedEvent _proto;
        internal VoiceEndedEventResponse(global::Mezon.Net.Internal.Realtime.VoiceEndedEvent proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Realtime.VoiceEndedEvent Proto => _proto;

        public long Id => _proto.Id;
        public long ClanId => _proto.ClanId;
        public string VoiceChannelId => _proto.VoiceChannelId;
    }
}
