// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct VotePollResponseData
    {
        private readonly global::Mezon.Net.Internal.Api.VotePollResponse _proto;
        internal VotePollResponseData(global::Mezon.Net.Internal.Api.VotePollResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.VotePollResponse Proto => _proto;

        public ProtoListView<int> MyAnswerIndices => ProtoListView<int>.FromRepeated(_proto.MyAnswerIndices);
    }
}
