// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct WebhookResponse
    {
        private readonly global::Mezon.Net.Internal.Api.Webhook _proto;
        internal WebhookResponse(global::Mezon.Net.Internal.Api.Webhook proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.Webhook Proto => _proto;

        public long Id => _proto.Id;
        public string WebhookName => _proto.WebhookName;
        public long ChannelId => _proto.ChannelId;
        public int Active => _proto.Active;
        public string Url => _proto.Url;
        public long CreatorId => _proto.CreatorId;
        public string CreateTime => _proto.CreateTime;
        public string UpdateTime => _proto.UpdateTime;
        public string Avatar => _proto.Avatar;
        public int Status => _proto.Status;
        public long ClanId => _proto.ClanId;
    }
}
