// <auto-generated />
#nullable enable
using System.Collections.Generic;

namespace Mezon.Net.Models
{
    public readonly struct WebhookGenerateResponse
    {
        private readonly global::Mezon.Net.Internal.Api.WebhookGenerateResponse _proto;
        internal WebhookGenerateResponse(global::Mezon.Net.Internal.Api.WebhookGenerateResponse proto) => _proto = proto;
        internal global::Mezon.Net.Internal.Api.WebhookGenerateResponse Proto => _proto;

        public string Url => _proto.Url;
        public string HookName => _proto.HookName;
        public long ChannelId => _proto.ChannelId;
        public string Avatar => _proto.Avatar;
    }
}
