<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../Mezon.Net.targets" />

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0;net9.0;net10.0;</TargetFrameworks>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <WarningsAsErrors>$(WarningsAsErrors);CS8600;CS8602;CS8603</WarningsAsErrors>
    <PackageId>Mezon.Net.Mmn</PackageId>
    <Description>Mezon Mainnet (MMN) and Zero-Knowledge (ZK) HTTP clients for Mezon.Net.</Description>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>
</Project>
