// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct AddClanUserEventEventData
    {
        private readonly AddClanUserEventResponse _data;
        internal AddClanUserEventEventData(AddClanUserEventResponse data) => _data = data;
        internal AddClanUserEventResponse Data => _data;

        public static implicit operator AddClanUserEventResponse(AddClanUserEventEventData e) => e._data;
        public static implicit operator AddClanUserEventEventData(AddClanUserEventResponse d) => new AddClanUserEventEventData(d);
    }
}
