// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ApiRequestEventEventData
    {
        private readonly ApiRequestEventData _data;
        internal ApiRequestEventEventData(ApiRequestEventData data) => _data = data;
        internal ApiRequestEventData Data => _data;

        public static implicit operator ApiRequestEventData(ApiRequestEventEventData e) => e._data;
        public static implicit operator ApiRequestEventEventData(ApiRequestEventData d) => new ApiRequestEventEventData(d);
    }
}
