// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ApiRequestEventEventData
    {
        private readonly ApiRequestEventResponse _data;
        internal ApiRequestEventEventData(ApiRequestEventResponse data) => _data = data;
        internal ApiRequestEventResponse Data => _data;

        public static implicit operator ApiRequestEventResponse(ApiRequestEventEventData e) => e._data;
        public static implicit operator ApiRequestEventEventData(ApiRequestEventResponse d) => new ApiRequestEventEventData(d);
    }
}
