// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageUpdateEventData
    {
        private readonly ChannelMessageUpdateData _data;
        internal ChannelMessageUpdateEventData(ChannelMessageUpdateData data) => _data = data;
        internal ChannelMessageUpdateData Data => _data;

        public static implicit operator ChannelMessageUpdateData(ChannelMessageUpdateEventData e) => e._data;
        public static implicit operator ChannelMessageUpdateEventData(ChannelMessageUpdateData d) => new ChannelMessageUpdateEventData(d);
    }
}
