// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelJoinEventData
    {
        private readonly ChannelJoinData _data;
        internal ChannelJoinEventData(ChannelJoinData data) => _data = data;
        internal ChannelJoinData Data => _data;

        public static implicit operator ChannelJoinData(ChannelJoinEventData e) => e._data;
        public static implicit operator ChannelJoinEventData(ChannelJoinData d) => new ChannelJoinEventData(d);
    }
}
