// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageRemoveEventData
    {
        private readonly ChannelMessageRemoveData _data;
        internal ChannelMessageRemoveEventData(ChannelMessageRemoveData data) => _data = data;
        internal ChannelMessageRemoveData Data => _data;

        public static implicit operator ChannelMessageRemoveData(ChannelMessageRemoveEventData e) => e._data;
        public static implicit operator ChannelMessageRemoveEventData(ChannelMessageRemoveData d) => new ChannelMessageRemoveEventData(d);
    }
}
