// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageEventData
    {
        private readonly ChannelMessageData _data;
        internal ChannelMessageEventData(ChannelMessageData data) => _data = data;
        internal ChannelMessageData Data => _data;

        public static implicit operator ChannelMessageData(ChannelMessageEventData e) => e._data;
        public static implicit operator ChannelMessageEventData(ChannelMessageData d) => new ChannelMessageEventData(d);
    }
}
