// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelEventData
    {
        private readonly ChannelData _data;
        internal ChannelEventData(ChannelData data) => _data = data;
        internal ChannelData Data => _data;

        public static implicit operator ChannelData(ChannelEventData e) => e._data;
        public static implicit operator ChannelEventData(ChannelData d) => new ChannelEventData(d);
    }
}
