// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelUpdatedEventEventData
    {
        private readonly ChannelUpdatedEventResponse _data;
        internal ChannelUpdatedEventEventData(ChannelUpdatedEventResponse data) => _data = data;
        internal ChannelUpdatedEventResponse Data => _data;

        public static implicit operator ChannelUpdatedEventResponse(ChannelUpdatedEventEventData e) => e._data;
        public static implicit operator ChannelUpdatedEventEventData(ChannelUpdatedEventResponse d) => new ChannelUpdatedEventEventData(d);
    }
}
