// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelCreatedEventEventData
    {
        private readonly ChannelCreatedEventData _data;
        internal ChannelCreatedEventEventData(ChannelCreatedEventData data) => _data = data;
        internal ChannelCreatedEventData Data => _data;

        public static implicit operator ChannelCreatedEventData(ChannelCreatedEventEventData e) => e._data;
        public static implicit operator ChannelCreatedEventEventData(ChannelCreatedEventData d) => new ChannelCreatedEventEventData(d);
    }
}
