// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageSendEventData
    {
        private readonly ChannelMessageSendResponse _data;
        internal ChannelMessageSendEventData(ChannelMessageSendResponse data) => _data = data;
        internal ChannelMessageSendResponse Data => _data;

        public static implicit operator ChannelMessageSendResponse(ChannelMessageSendEventData e) => e._data;
        public static implicit operator ChannelMessageSendEventData(ChannelMessageSendResponse d) => new ChannelMessageSendEventData(d);
    }
}
