// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelDeletedEventEventData
    {
        private readonly ChannelDeletedEventData _data;
        internal ChannelDeletedEventEventData(ChannelDeletedEventData data) => _data = data;
        internal ChannelDeletedEventData Data => _data;

        public static implicit operator ChannelDeletedEventData(ChannelDeletedEventEventData e) => e._data;
        public static implicit operator ChannelDeletedEventEventData(ChannelDeletedEventData d) => new ChannelDeletedEventEventData(d);
    }
}
