// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelPresenceEventEventData
    {
        private readonly ChannelPresenceEventResponse _data;
        internal ChannelPresenceEventEventData(ChannelPresenceEventResponse data) => _data = data;
        internal ChannelPresenceEventResponse Data => _data;

        public static implicit operator ChannelPresenceEventResponse(ChannelPresenceEventEventData e) => e._data;
        public static implicit operator ChannelPresenceEventEventData(ChannelPresenceEventResponse d) => new ChannelPresenceEventEventData(d);
    }
}
