// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelEventData
    {
        private readonly ChannelResponse _data;
        internal ChannelEventData(ChannelResponse data) => _data = data;
        internal ChannelResponse Data => _data;

        public static implicit operator ChannelResponse(ChannelEventData e) => e._data;
        public static implicit operator ChannelEventData(ChannelResponse d) => new ChannelEventData(d);
    }
}
