// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelArchiveEventEventData
    {
        private readonly ChannelArchiveEventData _data;
        internal ChannelArchiveEventEventData(ChannelArchiveEventData data) => _data = data;
        internal ChannelArchiveEventData Data => _data;

        public static implicit operator ChannelArchiveEventData(ChannelArchiveEventEventData e) => e._data;
        public static implicit operator ChannelArchiveEventEventData(ChannelArchiveEventData d) => new ChannelArchiveEventEventData(d);
    }
}
