// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageEventData
    {
        private readonly ChannelMessageResponse _data;
        internal ChannelMessageEventData(ChannelMessageResponse data) => _data = data;
        internal ChannelMessageResponse Data => _data;

        public static implicit operator ChannelMessageResponse(ChannelMessageEventData e) => e._data;
        public static implicit operator ChannelMessageEventData(ChannelMessageResponse d) => new ChannelMessageEventData(d);
    }
}
