// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelLeaveEventData
    {
        private readonly ChannelLeaveResponse _data;
        internal ChannelLeaveEventData(ChannelLeaveResponse data) => _data = data;
        internal ChannelLeaveResponse Data => _data;

        public static implicit operator ChannelLeaveResponse(ChannelLeaveEventData e) => e._data;
        public static implicit operator ChannelLeaveEventData(ChannelLeaveResponse d) => new ChannelLeaveEventData(d);
    }
}
