// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageRemoveEventData
    {
        private readonly ChannelMessageRemoveResponse _data;
        internal ChannelMessageRemoveEventData(ChannelMessageRemoveResponse data) => _data = data;
        internal ChannelMessageRemoveResponse Data => _data;

        public static implicit operator ChannelMessageRemoveResponse(ChannelMessageRemoveEventData e) => e._data;
        public static implicit operator ChannelMessageRemoveEventData(ChannelMessageRemoveResponse d) => new ChannelMessageRemoveEventData(d);
    }
}
