// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageUpdateEventData
    {
        private readonly ChannelMessageUpdateResponse _data;
        internal ChannelMessageUpdateEventData(ChannelMessageUpdateResponse data) => _data = data;
        internal ChannelMessageUpdateResponse Data => _data;

        public static implicit operator ChannelMessageUpdateResponse(ChannelMessageUpdateEventData e) => e._data;
        public static implicit operator ChannelMessageUpdateEventData(ChannelMessageUpdateResponse d) => new ChannelMessageUpdateEventData(d);
    }
}
