// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelMessageAckEventData
    {
        private readonly ChannelMessageAckData _data;
        internal ChannelMessageAckEventData(ChannelMessageAckData data) => _data = data;
        internal ChannelMessageAckData Data => _data;

        public static implicit operator ChannelMessageAckData(ChannelMessageAckEventData e) => e._data;
        public static implicit operator ChannelMessageAckEventData(ChannelMessageAckData d) => new ChannelMessageAckEventData(d);
    }
}
