// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelArchiveEventEventData
    {
        private readonly ChannelArchiveEventResponse _data;
        internal ChannelArchiveEventEventData(ChannelArchiveEventResponse data) => _data = data;
        internal ChannelArchiveEventResponse Data => _data;

        public static implicit operator ChannelArchiveEventResponse(ChannelArchiveEventEventData e) => e._data;
        public static implicit operator ChannelArchiveEventEventData(ChannelArchiveEventResponse d) => new ChannelArchiveEventEventData(d);
    }
}
