// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ChannelCreatedEventEventData
    {
        private readonly ChannelCreatedEventResponse _data;
        internal ChannelCreatedEventEventData(ChannelCreatedEventResponse data) => _data = data;
        internal ChannelCreatedEventResponse Data => _data;

        public static implicit operator ChannelCreatedEventResponse(ChannelCreatedEventEventData e) => e._data;
        public static implicit operator ChannelCreatedEventEventData(ChannelCreatedEventResponse d) => new ChannelCreatedEventEventData(d);
    }
}
