// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ClanJoinEventData
    {
        private readonly ClanJoinData _data;
        internal ClanJoinEventData(ClanJoinData data) => _data = data;
        internal ClanJoinData Data => _data;

        public static implicit operator ClanJoinData(ClanJoinEventData e) => e._data;
        public static implicit operator ClanJoinEventData(ClanJoinData d) => new ClanJoinEventData(d);
    }
}
