// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ClanJoinEventData
    {
        private readonly ClanJoinResponse _data;
        internal ClanJoinEventData(ClanJoinResponse data) => _data = data;
        internal ClanJoinResponse Data => _data;

        public static implicit operator ClanJoinResponse(ClanJoinEventData e) => e._data;
        public static implicit operator ClanJoinEventData(ClanJoinResponse d) => new ClanJoinEventData(d);
    }
}
