// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct CustomStatusEventEventData
    {
        private readonly CustomStatusEventResponse _data;
        internal CustomStatusEventEventData(CustomStatusEventResponse data) => _data = data;
        internal CustomStatusEventResponse Data => _data;

        public static implicit operator CustomStatusEventResponse(CustomStatusEventEventData e) => e._data;
        public static implicit operator CustomStatusEventEventData(CustomStatusEventResponse d) => new CustomStatusEventEventData(d);
    }
}
