// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct CustomStatusEventEventData
    {
        private readonly CustomStatusEventData _data;
        internal CustomStatusEventEventData(CustomStatusEventData data) => _data = data;
        internal CustomStatusEventData Data => _data;

        public static implicit operator CustomStatusEventData(CustomStatusEventEventData e) => e._data;
        public static implicit operator CustomStatusEventEventData(CustomStatusEventData d) => new CustomStatusEventEventData(d);
    }
}
