// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct DropdownBoxSelectedEventData
    {
        private readonly DropdownBoxSelectedResponse _data;
        internal DropdownBoxSelectedEventData(DropdownBoxSelectedResponse data) => _data = data;
        internal DropdownBoxSelectedResponse Data => _data;

        public static implicit operator DropdownBoxSelectedResponse(DropdownBoxSelectedEventData e) => e._data;
        public static implicit operator DropdownBoxSelectedEventData(DropdownBoxSelectedResponse d) => new DropdownBoxSelectedEventData(d);
    }
}
