// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ErrorEventData
    {
        private readonly ErrorResponse _data;
        internal ErrorEventData(ErrorResponse data) => _data = data;
        internal ErrorResponse Data => _data;

        public static implicit operator ErrorResponse(ErrorEventData e) => e._data;
        public static implicit operator ErrorEventData(ErrorResponse d) => new ErrorEventData(d);
    }
}
