// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ErrorEventData
    {
        private readonly ErrorData _data;
        internal ErrorEventData(ErrorData data) => _data = data;
        internal ErrorData Data => _data;

        public static implicit operator ErrorData(ErrorEventData e) => e._data;
        public static implicit operator ErrorEventData(ErrorData d) => new ErrorEventData(d);
    }
}
