// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct LastPinMessageEventEventData
    {
        private readonly LastPinMessageEventResponse _data;
        internal LastPinMessageEventEventData(LastPinMessageEventResponse data) => _data = data;
        internal LastPinMessageEventResponse Data => _data;

        public static implicit operator LastPinMessageEventResponse(LastPinMessageEventEventData e) => e._data;
        public static implicit operator LastPinMessageEventEventData(LastPinMessageEventResponse d) => new LastPinMessageEventEventData(d);
    }
}
