// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct LastSeenMessageEventEventData
    {
        private readonly LastSeenMessageEventData _data;
        internal LastSeenMessageEventEventData(LastSeenMessageEventData data) => _data = data;
        internal LastSeenMessageEventData Data => _data;

        public static implicit operator LastSeenMessageEventData(LastSeenMessageEventEventData e) => e._data;
        public static implicit operator LastSeenMessageEventEventData(LastSeenMessageEventData d) => new LastSeenMessageEventEventData(d);
    }
}
