// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct LastPinMessageEventEventData
    {
        private readonly LastPinMessageEventData _data;
        internal LastPinMessageEventEventData(LastPinMessageEventData data) => _data = data;
        internal LastPinMessageEventData Data => _data;

        public static implicit operator LastPinMessageEventData(LastPinMessageEventEventData e) => e._data;
        public static implicit operator LastPinMessageEventEventData(LastPinMessageEventData d) => new LastPinMessageEventEventData(d);
    }
}
