// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ListChannelUsersBannedEventEventData
    {
        private readonly ListChannelUsersBannedEventResponse _data;
        internal ListChannelUsersBannedEventEventData(ListChannelUsersBannedEventResponse data) => _data = data;
        internal ListChannelUsersBannedEventResponse Data => _data;

        public static implicit operator ListChannelUsersBannedEventResponse(ListChannelUsersBannedEventEventData e) => e._data;
        public static implicit operator ListChannelUsersBannedEventEventData(ListChannelUsersBannedEventResponse d) => new ListChannelUsersBannedEventEventData(d);
    }
}
