// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ListChannelUsersBannedEventEventData
    {
        private readonly ListChannelUsersBannedEventData _data;
        internal ListChannelUsersBannedEventEventData(ListChannelUsersBannedEventData data) => _data = data;
        internal ListChannelUsersBannedEventData Data => _data;

        public static implicit operator ListChannelUsersBannedEventData(ListChannelUsersBannedEventEventData e) => e._data;
        public static implicit operator ListChannelUsersBannedEventEventData(ListChannelUsersBannedEventData d) => new ListChannelUsersBannedEventEventData(d);
    }
}
