// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct MessageButtonClickedEventData
    {
        private readonly MessageButtonClickedResponse _data;
        internal MessageButtonClickedEventData(MessageButtonClickedResponse data) => _data = data;
        internal MessageButtonClickedResponse Data => _data;

        public static implicit operator MessageButtonClickedResponse(MessageButtonClickedEventData e) => e._data;
        public static implicit operator MessageButtonClickedEventData(MessageButtonClickedResponse d) => new MessageButtonClickedEventData(d);
    }
}
