// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct MessageReactionEventData
    {
        private readonly MessageReactionData _data;
        internal MessageReactionEventData(MessageReactionData data) => _data = data;
        internal MessageReactionData Data => _data;

        public static implicit operator MessageReactionData(MessageReactionEventData e) => e._data;
        public static implicit operator MessageReactionEventData(MessageReactionData d) => new MessageReactionEventData(d);
    }
}
