// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct MessageReactionEventData
    {
        private readonly MessageReactionResponse _data;
        internal MessageReactionEventData(MessageReactionResponse data) => _data = data;
        internal MessageReactionResponse Data => _data;

        public static implicit operator MessageReactionResponse(MessageReactionEventData e) => e._data;
        public static implicit operator MessageReactionEventData(MessageReactionResponse d) => new MessageReactionEventData(d);
    }
}
