// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct NotificationsEventData
    {
        private readonly NotificationsData _data;
        internal NotificationsEventData(NotificationsData data) => _data = data;
        internal NotificationsData Data => _data;

        public static implicit operator NotificationsData(NotificationsEventData e) => e._data;
        public static implicit operator NotificationsEventData(NotificationsData d) => new NotificationsEventData(d);
    }
}
