// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct PongEventData
    {
        private readonly PongResponse _data;
        internal PongEventData(PongResponse data) => _data = data;
        internal PongResponse Data => _data;

        public static implicit operator PongResponse(PongEventData e) => e._data;
        public static implicit operator PongEventData(PongResponse d) => new PongEventData(d);
    }
}
