// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct PongEventData
    {
        private readonly PongData _data;
        internal PongEventData(PongData data) => _data = data;
        internal PongData Data => _data;

        public static implicit operator PongData(PongEventData e) => e._data;
        public static implicit operator PongEventData(PongData d) => new PongEventData(d);
    }
}
