// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct RoleEventEventData
    {
        private readonly RoleEventResponse _data;
        internal RoleEventEventData(RoleEventResponse data) => _data = data;
        internal RoleEventResponse Data => _data;

        public static implicit operator RoleEventResponse(RoleEventEventData e) => e._data;
        public static implicit operator RoleEventEventData(RoleEventResponse d) => new RoleEventEventData(d);
    }
}
