// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct RoleAssignedEventEventData
    {
        private readonly RoleAssignedEventResponse _data;
        internal RoleAssignedEventEventData(RoleAssignedEventResponse data) => _data = data;
        internal RoleAssignedEventResponse Data => _data;

        public static implicit operator RoleAssignedEventResponse(RoleAssignedEventEventData e) => e._data;
        public static implicit operator RoleAssignedEventEventData(RoleAssignedEventResponse d) => new RoleAssignedEventEventData(d);
    }
}
