// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct RpcEventData
    {
        private readonly RpcData _data;
        internal RpcEventData(RpcData data) => _data = data;
        internal RpcData Data => _data;

        public static implicit operator RpcData(RpcEventData e) => e._data;
        public static implicit operator RpcEventData(RpcData d) => new RpcEventData(d);
    }
}
