// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct RpcEventData
    {
        private readonly RpcResponse _data;
        internal RpcEventData(RpcResponse data) => _data = data;
        internal RpcResponse Data => _data;

        public static implicit operator RpcResponse(RpcEventData e) => e._data;
        public static implicit operator RpcEventData(RpcResponse d) => new RpcEventData(d);
    }
}
