// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct ScreenShareEventEventData
    {
        private readonly ScreenShareEventResponse _data;
        internal ScreenShareEventEventData(ScreenShareEventResponse data) => _data = data;
        internal ScreenShareEventResponse Data => _data;

        public static implicit operator ScreenShareEventResponse(ScreenShareEventEventData e) => e._data;
        public static implicit operator ScreenShareEventEventData(ScreenShareEventResponse d) => new ScreenShareEventEventData(d);
    }
}
