// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusFollowEventData
    {
        private readonly StatusFollowData _data;
        internal StatusFollowEventData(StatusFollowData data) => _data = data;
        internal StatusFollowData Data => _data;

        public static implicit operator StatusFollowData(StatusFollowEventData e) => e._data;
        public static implicit operator StatusFollowEventData(StatusFollowData d) => new StatusFollowEventData(d);
    }
}
