// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusUnfollowEventData
    {
        private readonly StatusUnfollowResponse _data;
        internal StatusUnfollowEventData(StatusUnfollowResponse data) => _data = data;
        internal StatusUnfollowResponse Data => _data;

        public static implicit operator StatusUnfollowResponse(StatusUnfollowEventData e) => e._data;
        public static implicit operator StatusUnfollowEventData(StatusUnfollowResponse d) => new StatusUnfollowEventData(d);
    }
}
