// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusPresenceEventEventData
    {
        private readonly StatusPresenceEventData _data;
        internal StatusPresenceEventEventData(StatusPresenceEventData data) => _data = data;
        internal StatusPresenceEventData Data => _data;

        public static implicit operator StatusPresenceEventData(StatusPresenceEventEventData e) => e._data;
        public static implicit operator StatusPresenceEventEventData(StatusPresenceEventData d) => new StatusPresenceEventEventData(d);
    }
}
