// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusEventData
    {
        private readonly StatusResponse _data;
        internal StatusEventData(StatusResponse data) => _data = data;
        internal StatusResponse Data => _data;

        public static implicit operator StatusResponse(StatusEventData e) => e._data;
        public static implicit operator StatusEventData(StatusResponse d) => new StatusEventData(d);
    }
}
