// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusEventData
    {
        private readonly StatusData _data;
        internal StatusEventData(StatusData data) => _data = data;
        internal StatusData Data => _data;

        public static implicit operator StatusData(StatusEventData e) => e._data;
        public static implicit operator StatusEventData(StatusData d) => new StatusEventData(d);
    }
}
