// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusPresenceEventEventData
    {
        private readonly StatusPresenceEventResponse _data;
        internal StatusPresenceEventEventData(StatusPresenceEventResponse data) => _data = data;
        internal StatusPresenceEventResponse Data => _data;

        public static implicit operator StatusPresenceEventResponse(StatusPresenceEventEventData e) => e._data;
        public static implicit operator StatusPresenceEventEventData(StatusPresenceEventResponse d) => new StatusPresenceEventEventData(d);
    }
}
