// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusUpdateEventData
    {
        private readonly StatusUpdateData _data;
        internal StatusUpdateEventData(StatusUpdateData data) => _data = data;
        internal StatusUpdateData Data => _data;

        public static implicit operator StatusUpdateData(StatusUpdateEventData e) => e._data;
        public static implicit operator StatusUpdateEventData(StatusUpdateData d) => new StatusUpdateEventData(d);
    }
}
