// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StatusUnfollowEventData
    {
        private readonly StatusUnfollowData _data;
        internal StatusUnfollowEventData(StatusUnfollowData data) => _data = data;
        internal StatusUnfollowData Data => _data;

        public static implicit operator StatusUnfollowData(StatusUnfollowEventData e) => e._data;
        public static implicit operator StatusUnfollowEventData(StatusUnfollowData d) => new StatusUnfollowEventData(d);
    }
}
