// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StreamPresenceEventEventData
    {
        private readonly StreamPresenceEventResponse _data;
        internal StreamPresenceEventEventData(StreamPresenceEventResponse data) => _data = data;
        internal StreamPresenceEventResponse Data => _data;

        public static implicit operator StreamPresenceEventResponse(StreamPresenceEventEventData e) => e._data;
        public static implicit operator StreamPresenceEventEventData(StreamPresenceEventResponse d) => new StreamPresenceEventEventData(d);
    }
}
