// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StreamDataEventData
    {
        private readonly StreamDataResponse _data;
        internal StreamDataEventData(StreamDataResponse data) => _data = data;
        internal StreamDataResponse Data => _data;

        public static implicit operator StreamDataResponse(StreamDataEventData e) => e._data;
        public static implicit operator StreamDataEventData(StreamDataResponse d) => new StreamDataEventData(d);
    }
}
