// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StreamDataEventData
    {
        private readonly StreamDataData _data;
        internal StreamDataEventData(StreamDataData data) => _data = data;
        internal StreamDataData Data => _data;

        public static implicit operator StreamDataData(StreamDataEventData e) => e._data;
        public static implicit operator StreamDataEventData(StreamDataData d) => new StreamDataEventData(d);
    }
}
