// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct StreamPresenceEventEventData
    {
        private readonly StreamPresenceEventData _data;
        internal StreamPresenceEventEventData(StreamPresenceEventData data) => _data = data;
        internal StreamPresenceEventData Data => _data;

        public static implicit operator StreamPresenceEventData(StreamPresenceEventEventData e) => e._data;
        public static implicit operator StreamPresenceEventEventData(StreamPresenceEventData d) => new StreamPresenceEventEventData(d);
    }
}
