// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct TopicInMessageEventEventData
    {
        private readonly TopicInMessageEventData _data;
        internal TopicInMessageEventEventData(TopicInMessageEventData data) => _data = data;
        internal TopicInMessageEventData Data => _data;

        public static implicit operator TopicInMessageEventData(TopicInMessageEventEventData e) => e._data;
        public static implicit operator TopicInMessageEventEventData(TopicInMessageEventData d) => new TopicInMessageEventEventData(d);
    }
}
