// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct TopicInMessageEventEventData
    {
        private readonly TopicInMessageEventResponse _data;
        internal TopicInMessageEventEventData(TopicInMessageEventResponse data) => _data = data;
        internal TopicInMessageEventResponse Data => _data;

        public static implicit operator TopicInMessageEventResponse(TopicInMessageEventEventData e) => e._data;
        public static implicit operator TopicInMessageEventEventData(TopicInMessageEventResponse d) => new TopicInMessageEventEventData(d);
    }
}
