// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct UserChannelAddedEventData
    {
        private readonly UserChannelAddedResponse _data;
        internal UserChannelAddedEventData(UserChannelAddedResponse data) => _data = data;
        internal UserChannelAddedResponse Data => _data;

        public static implicit operator UserChannelAddedResponse(UserChannelAddedEventData e) => e._data;
        public static implicit operator UserChannelAddedEventData(UserChannelAddedResponse d) => new UserChannelAddedEventData(d);
    }
}
