// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct UserChannelAddedEventData
    {
        private readonly UserChannelAddedData _data;
        internal UserChannelAddedEventData(UserChannelAddedData data) => _data = data;
        internal UserChannelAddedData Data => _data;

        public static implicit operator UserChannelAddedData(UserChannelAddedEventData e) => e._data;
        public static implicit operator UserChannelAddedEventData(UserChannelAddedData d) => new UserChannelAddedEventData(d);
    }
}
