// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct UserChannelRemovedEventData
    {
        private readonly UserChannelRemovedResponse _data;
        internal UserChannelRemovedEventData(UserChannelRemovedResponse data) => _data = data;
        internal UserChannelRemovedResponse Data => _data;

        public static implicit operator UserChannelRemovedResponse(UserChannelRemovedEventData e) => e._data;
        public static implicit operator UserChannelRemovedEventData(UserChannelRemovedResponse d) => new UserChannelRemovedEventData(d);
    }
}
