// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceEndedEventEventData
    {
        private readonly VoiceEndedEventData _data;
        internal VoiceEndedEventEventData(VoiceEndedEventData data) => _data = data;
        internal VoiceEndedEventData Data => _data;

        public static implicit operator VoiceEndedEventData(VoiceEndedEventEventData e) => e._data;
        public static implicit operator VoiceEndedEventEventData(VoiceEndedEventData d) => new VoiceEndedEventEventData(d);
    }
}
