// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceInteractiveEventEventData
    {
        private readonly VoiceInteractiveEventResponse _data;
        internal VoiceInteractiveEventEventData(VoiceInteractiveEventResponse data) => _data = data;
        internal VoiceInteractiveEventResponse Data => _data;

        public static implicit operator VoiceInteractiveEventResponse(VoiceInteractiveEventEventData e) => e._data;
        public static implicit operator VoiceInteractiveEventEventData(VoiceInteractiveEventResponse d) => new VoiceInteractiveEventEventData(d);
    }
}
