// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceJoinedEventEventData
    {
        private readonly VoiceJoinedEventResponse _data;
        internal VoiceJoinedEventEventData(VoiceJoinedEventResponse data) => _data = data;
        internal VoiceJoinedEventResponse Data => _data;

        public static implicit operator VoiceJoinedEventResponse(VoiceJoinedEventEventData e) => e._data;
        public static implicit operator VoiceJoinedEventEventData(VoiceJoinedEventResponse d) => new VoiceJoinedEventEventData(d);
    }
}
