// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceStartedEventEventData
    {
        private readonly VoiceStartedEventData _data;
        internal VoiceStartedEventEventData(VoiceStartedEventData data) => _data = data;
        internal VoiceStartedEventData Data => _data;

        public static implicit operator VoiceStartedEventData(VoiceStartedEventEventData e) => e._data;
        public static implicit operator VoiceStartedEventEventData(VoiceStartedEventData d) => new VoiceStartedEventEventData(d);
    }
}
