// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceLeavedEventEventData
    {
        private readonly VoiceLeavedEventResponse _data;
        internal VoiceLeavedEventEventData(VoiceLeavedEventResponse data) => _data = data;
        internal VoiceLeavedEventResponse Data => _data;

        public static implicit operator VoiceLeavedEventResponse(VoiceLeavedEventEventData e) => e._data;
        public static implicit operator VoiceLeavedEventEventData(VoiceLeavedEventResponse d) => new VoiceLeavedEventEventData(d);
    }
}
