// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceEndedEventEventData
    {
        private readonly VoiceEndedEventResponse _data;
        internal VoiceEndedEventEventData(VoiceEndedEventResponse data) => _data = data;
        internal VoiceEndedEventResponse Data => _data;

        public static implicit operator VoiceEndedEventResponse(VoiceEndedEventEventData e) => e._data;
        public static implicit operator VoiceEndedEventEventData(VoiceEndedEventResponse d) => new VoiceEndedEventEventData(d);
    }
}
