// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceStartedEventEventData
    {
        private readonly VoiceStartedEventResponse _data;
        internal VoiceStartedEventEventData(VoiceStartedEventResponse data) => _data = data;
        internal VoiceStartedEventResponse Data => _data;

        public static implicit operator VoiceStartedEventResponse(VoiceStartedEventEventData e) => e._data;
        public static implicit operator VoiceStartedEventEventData(VoiceStartedEventResponse d) => new VoiceStartedEventEventData(d);
    }
}
