// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceJoinedEventEventData
    {
        private readonly VoiceJoinedEventData _data;
        internal VoiceJoinedEventEventData(VoiceJoinedEventData data) => _data = data;
        internal VoiceJoinedEventData Data => _data;

        public static implicit operator VoiceJoinedEventData(VoiceJoinedEventEventData e) => e._data;
        public static implicit operator VoiceJoinedEventEventData(VoiceJoinedEventData d) => new VoiceJoinedEventEventData(d);
    }
}
