// <auto-generated />
#nullable enable

namespace Mezon.Net.Models
{
    public readonly struct VoiceLeavedEventEventData
    {
        private readonly VoiceLeavedEventData _data;
        internal VoiceLeavedEventEventData(VoiceLeavedEventData data) => _data = data;
        internal VoiceLeavedEventData Data => _data;

        public static implicit operator VoiceLeavedEventData(VoiceLeavedEventEventData e) => e._data;
        public static implicit operator VoiceLeavedEventEventData(VoiceLeavedEventData d) => new VoiceLeavedEventEventData(d);
    }
}
