using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mezon.Net.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class MezonProtobufBoundaryGenerator : IIncrementalGenerator
{
    private const string AuthAttribute = "Mezon.Net.Client.Generation.GenerateMezonAuthApiFacadeAttribute";
    private const string SocketAttribute = "Mezon.Net.Client.Generation.GenerateMezonSocketApiFacadeAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var authTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AuthAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol?.Name ?? string.Empty)
            .Where(static name => !string.IsNullOrEmpty(name))
            .Collect();

        var socketTargets = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                SocketAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => ctx.TargetSymbol?.Name ?? string.Empty)
            .Where(static name => !string.IsNullOrEmpty(name))
            .Collect();

        context.RegisterSourceOutput(authTargets, static (spc, names) =>
        {
            if (names.IsDefaultOrEmpty)
            {
                return;
            }

            spc.AddSource(
                "MezonGenerator.AuthAnchor.g.cs",
                SourceText.From(
                    "// <auto-generated />\n// Facade output is generated by tools/generate_protobuf_boundary.py into Generated/ and Models/.\n",
                    Encoding.UTF8));
        });

        context.RegisterSourceOutput(socketTargets, static (spc, names) =>
        {
            if (names.IsDefaultOrEmpty)
            {
                return;
            }

            spc.AddSource(
                "MezonGenerator.SocketAnchor.g.cs",
                SourceText.From(
                    "// <auto-generated />\n// Facade output is generated by tools/generate_protobuf_boundary.py into Generated/ and Models/.\n",
                    Encoding.UTF8));
        });

        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
        {
            var iface = compilation.GetTypeByMetadataName("Mezon.Net.Abstractions.IMezonApiClient");
            if (iface is null)
            {
                return;
            }

            var methodCount = iface.GetMembers()
                .OfType<IMethodSymbol>()
                .Count(m => m.MethodKind == MethodKind.Ordinary && !m.IsStatic && m.DeclaredAccessibility == Accessibility.Public);

            spc.AddSource(
                "MezonGenerator.Manifest.g.cs",
                SourceText.From(
                    $"// <auto-generated />\ninternal static class MezonGeneratorManifest {{ internal const int ApiMethodCount = {methodCount}; }}\n",
                    Encoding.UTF8));
        });
    }
}
