<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0;net9.0;net10.0;</TargetFrameworks>
    <WarningLevel>5</WarningLevel>
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <IsTrimmable>false</IsTrimmable>
    <IsAotCompatible>false</IsAotCompatible>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>$(WarningsAsErrors);CS8600;CS8602;CS8603</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\" />
    <Folder Include="DependencyInjection\" />
    <Folder Include="Entities\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mezon.NET.Api\Mezon.NET.Api.csproj" />
    <ProjectReference Include="..\Mezon.NET.Core\Mezon.NET.Core.csproj" />
  </ItemGroup>

</Project>
