"""Generate socket API members in IMezonApiClient.cs and MezonApiClient.cs from MezonSocketApiClient."""
import re
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOCKET_CLIENT = os.path.join(ROOT, "src/Mezon.Net.Client/Clients/MezonSocketApiClient.cs")

def read_methods(path):
    if not os.path.exists(path):
        return []
    text = open(path, encoding="utf-8").read()
    # match public async Task / public Task method signatures until {
    pattern = re.compile(
        r"public\s+(?:async\s+)?(?:override\s+)?(Task(?:<[^>]+>)?)\s+(\w+Async)\s*\(([^)]*)\)",
        re.MULTILINE,
    )
    methods = []
    for m in pattern.finditer(text):
        ret, name, args = m.group(1), m.group(2), m.group(3).strip()
        if name in ("SendApiAsync", "SendApiEnvelopeAsync", "SendEnvelopeAsync"):
            continue
        methods.append((ret, name, args))
    return methods

def iface_line(ret, name, args):
    args_clean = re.sub(r"\boptions\s*=\s*null", "options = null", args)
    return f"        {ret} {name}({args_clean});"

def stub_body(ret, name, args):
    if ret == "Task":
        body = 'throw new NotSupportedException("Socket API is not available on REST-only client.");'
    else:
        body = 'throw new NotSupportedException("Socket API is not available on REST-only client.");'
    args_clean = args
    return f"""        public virtual {ret} {name}({args_clean})
        {{
            {body}
        }}"""

methods = read_methods(SOCKET_CLIENT)
seen = set()
unique = []
for m in methods:
    if m[1] not in seen:
        seen.add(m[1])
        unique.append(m)

iface_path = os.path.join(ROOT, "src/Mezon.Net.Client/Abstractions/IMezonApiClient.cs")
stubs_path = os.path.join(ROOT, "src/Mezon.Net.Client/MezonApiClient.cs")

iface_lines = [
    "// <auto-generated />",
    "#nullable enable",
    "using System.Collections.Generic;",
    "using System.Threading.Tasks;",
    "using Mezon.Net.Api;",
    "using Mezon.Net.Core;",
    "using Mezon.Net.Internal.Api;",
    "",
    "namespace Mezon.Net.Abstractions",
    "{",
    "    public interface IMezonApiClient",
    "    {",
]
for m in unique:
    iface_lines.append(iface_line(*m))
iface_lines.extend(["    }", "}"])
open(iface_path, "w", encoding="utf-8").write("\n".join(iface_lines) + "\n")

stub_lines = [
    "// <auto-generated />",
    "#nullable enable",
    "using System;",
    "using System.Collections.Generic;",
    "using System.Threading.Tasks;",
    "using Mezon.Net.Api;",
    "using Mezon.Net.Core;",
    "using Mezon.Net.Internal.Api;",
    "",
    "namespace Mezon.Net.Client",
    "{",
    "    internal class MezonApiClient",
    "    {",
]
for m in unique:
    stub_lines.append(stub_body(*m))
    stub_lines.append("")
stub_lines.extend(["    }", "}"])
open(stubs_path, "w", encoding="utf-8").write("\n".join(stub_lines) + "\n")

print(f"Generated {len(unique)} API members")
